### ISSUE TITLE
Make Colors page responsive

### ISSUE THREAD

**Issue by iuloshi** [cfpb/design-manual#109]
Hopefully Brad Frost's workshop today will have some insight into how to make those tables responsive! Also relates to Minicons page > Asset Library tables.

![style_sk_140321_v6_color mobile](https://cloud.githubusercontent.com/assets/1676307/2632956/2d5d955a-be69-11e3-89ba-8ce94abf3c01.png)

**Comment by iuloshi** [comment]
http://css-tricks.com/responsive-data-tables/

**Comment by Scotchester** [comment]
In this case, the color tables are individual tables, so we can stack them up as we move down to a narrow viewport like this with no issue.

I love the expandable concept in Stephen's mockup here, but it's probably fairly down the list of priorities. I will take on the task of making the page responsive at a basic level sooner rather than later.

**Comment by iuloshi** [comment]
Sounds good, thanks @Scotchester!

**Comment by iuloshi** [comment]
Noting that the Colors page is responsive, thanks to @Scotchester. 

Keeping this issue open for the further enhancement of the expandable color blocks for mobile.
