### ISSUE TITLE
Identity > Minicons > Asset Library: How can we hide "LESS variables" & "Icon class" h3 headers using Topcoat comments?

### ISSUE THREAD

**Issue by iuloshi** [cfpb/design-manual#115]
@himedlooff @Scotchester: On Friday, Mike taught Lee & I how to build the Minicon Asset Library using Topcoat and Jade templates to pull in the content from Capital Framework. See my unstyled demo page [here](http://iuloshi.github.io/design-manual/identity/minicons.html#asset-library).

In the Jade template, we're assigning `h3=component.name` to include the minicon category names, but the first two `h3`s, "LESS variables" and "Icon class", aren't relevant to the Design Manual.

How do you suggest we hide those first two `h3`s? Would you prefer assigning them different tags in the Topcoat comments or using plain ole' CSS? Thanks!!

![screen shot 2014-04-14 at 9 32 11 am](https://cloud.githubusercontent.com/assets/1676307/2695659/363ed39e-c3d9-11e3-9a7f-24d3970558f6.png)

**Comment by himedlooff** [comment]
@iuloshi I have an idea in the works for this. Will keep you posted.

**Comment by iuloshi** [comment]
Looks like this was taken care of in @himedlooff's [last PR](https://github.com/cfpb/design-manual/pull/118). Thanks for your help on this!! :smiley_cat:

**Comment by himedlooff** [comment]
Word. For more information read https://github.com/cfpb/design-manual/tree/gh-pages/front/topdoc-templates. Specifically the [section on Grunt tasks](front/topdoc-templates/includes/filter-components-without-markup.jade) because `front/topdoc-templates/includes/filter-components-without-markup.jade` is a reusable jade snippet we can use to weed out any Topdoc component that contains patterns with no markup examples.
