### ISSUE TITLE
UI toolkit > Buttons page

### ISSUE THREAD

**Issue by ohsk** [cfpb/design-manual#125]
- [x] update structure of the page to match the formatting described in issue #73 
- [x] write description content
- [x] integrate CF elements as example content

**Comment by iuloshi** [comment]
So, what you did in your PR (#126) is perfect! Just copy & paste the code from Capital Framework as you did, but then also wrap the example UI code snippet inside `{::nomarkdown}  ..... {:/nomarkdown}` tags so that the HTML renders instead of Markdown. 

For example on the buttons page:

```
{::nomarkdown}  
<button class="btn">Sign up</button>
<button class="btn btn-link">Log in</button>
{:/nomarkdown}
```

Will spit out:

![screen shot 2014-04-18 at 1 57 09 pm](https://cloud.githubusercontent.com/assets/1676307/2744257/e45c5c2a-c722-11e3-9057-38b0e399b467.png)

aka beautiful buttons! Check out on [my demo page](http://iuloshi.github.io/design-manual/ui-toolkit/buttons.html).
