### ISSUE TITLE
Expandable sections

### ISSUE THREAD

**Issue by mebates** [cfpb/design-manual#143]
Design and content for the Expandables page, edited from the DPG content. Sending source file to @iuloshi. Design or content critique welcome!

![expandables](https://cloud.githubusercontent.com/assets/6223901/2746119/af30d788-c740-11e3-8fdd-a292ddbf0836.png)

**Comment by mebates** [comment]
Hey @iuloshi - Took a look at the page. I was imagining the live example in the 'Style' section and static images in the 'States' section (just the bars).

**Comment by iuloshi** [comment]
Since we show the different Links, Buttons, and Forms states as coded examples (as they also exist in Capital Framework), I'm inclined to say that we shouldn't use images to illustrate the examples in the UI toolkit. The coded examples on the other pages set the expectation that all of the UI elements are interactive and I think it would be frustrating/confusing to the user if some were arbitrarily images. I was going to try to hack the code so that the Hover state example was the correct hover color for the expandable.

**Comment by himedlooff** [comment]
Add the class "open" to `.expandable-header`. That should give you a live example of the expandable with the hover state active.

``` html
<div class="expandable">
    <header class="expandable-header open">
```

Although I'm noticing that there is a hover for both the expandable header bar and a different one for the show/hide link.

**Comment by iuloshi** [comment]
Hey thanks @himedlooff!! 
- [x] Content audit/review

**Comment by mebates** [comment]
Hey @iuloshi - I just reviewed the page and it looks good. Closing!

**Comment by benguhin** [comment]
Re-opening this guy because of the awesome work that Owning a Home and Flapjack teams have done with expandable sections in the past year. Here's a screenshot from the about site of a two-column list section that becomes expandable on the smallest breakpoint:

![screen shot 2015-03-23 at 11 39 45 am](https://cloud.githubusercontent.com/assets/6953063/6783674/82321ffa-d151-11e4-8a88-34762a9b419d.png)

@stephanieosan I think y'alls we also working on spacing rules?

**Comment by stephanieosan** [comment]
Linking off to this gray issue: https://github.com/cfpb/design-manual/issues/295
If we're changing to 5% grey instead of 10% to make links accessible, we should definitely do the same for expandables, since they include links. The other question I see, is whether we should include rules above or below or both on grey expandables.

**Comment by stephanieosan** [comment]
Another topic: what about the black-lined expandable table pattern that Flapjack and Owning a Home have been using recently? Is that considered an "expandable" or is that style part of a different bucket of patterns?

![screen shot 2015-03-31 at 10 48 00 am](https://cloud.githubusercontent.com/assets/6433178/6921524/71a1fea6-d793-11e4-8b1e-83f61fdc65a9.png)

**Comment by stephanieosan** [comment]
@benguhin I will assess what we've been doing about spacing.

**Comment by Scotchester** [comment]
@stephanieosan We call those "expandable groups". Groups that only allow one to be open at a time are given the additional descriptor of "accordion-style". Code-wise, they are a part of [cf-expandables](http://cfpb.github.io/cf-expandables/docs/#expandable-groups), as they merely style combinations of multiple single expandables.

**Comment by duelj** [comment]
I will say I prefer the grey lines on all expandables as we do not use full black lines in other areas of FJ (tables, rules, section dividers, etc.) not really sure how the black lines got in there.  As for the type, I know we modified ours a bit for a FAQ section and bumped it up to h4 to create better hierarchy with the answers, but had been using the link style for most. 

![screen shot 2015-03-31 at 1 30 52 pm](https://cloud.githubusercontent.com/assets/6873734/6925010/9de8e530-d7aa-11e4-92d2-a9ae2dce69fd.png)

The example @benguhin on the about the bureau page (http://beta.consumerfinance.gov/the-bureau/) with the blue text is also a bit of a fluke as we are moving towards using black title text as the default I believe. The History section (http://beta.consumerfinance.gov/the-bureau/history/) also makes use of the grey background style expandable (this one would need to updated to the 5% grey as @stephanieosan mentioned).

![screen shot 2015-03-31 at 1 36 08 pm](https://cloud.githubusercontent.com/assets/6873734/6925169/95ef16a0-d7ab-11e4-8bf3-611019077b24.png)

**Comment by duelj** [comment]
I wanted to add another example of a custom expandable situation we have in flapjack to see if there is a way the default expandable might be used to make it more consistent. The "show 40 contacts" expands to reveal an expandable table style with all the contacts. The button format was used to help differentiate it from the contact expendables, but we would like it bring it more in line if possible. 

| current style | attempted design manual style (w/ 5% grey) |
| --- | --- |
| ![screen shot 2015-04-01 at 4 29 50 pm](https://cloud.githubusercontent.com/assets/6873734/6951958/cacf63de-d88c-11e4-9e86-74befb718a46.png) | ![screen shot 2015-04-01 at 4 34 50 pm](https://cloud.githubusercontent.com/assets/6873734/6952009/0dce5230-d88d-11e4-95b3-80a23b9925e9.png) |

**Comment by benguhin** [comment]
@stephanieosan I think we should definitely consider the "black-lined expandable table pattern" and "background gray expandable" styles at the same time – it can make sense for them to be styled differently because they're used for different purposes, but we should (a) try to make them as similar as possible (b) update the guidelines based on the more advanced amounts of content that you guys have been expandifying and (c) provide more guidelines about how the patterns should adjust for responsiveness and accessibility 

As @Scotchester mentioned, we already have versions of both in cf-expandables:
![screen shot 2015-04-02 at 6 57 40 pm](https://cloud.githubusercontent.com/assets/6953063/6975451/49f439cc-d96a-11e4-965f-4931a9a165eb.png)

http://cfpb.github.io/cf-expandables/docs/#recommended-expandable-pattern

@duelj I am also torn about those options. The button is so much cleaner.

**Comment by duelj** [comment]
#### Things we could leave open?

Two tweaks that I would propose we maintain as "designer discretion" would be: 

• ability to remove the stroke between header and content in the expanded version. I think sometimes it makes sense to include but other times it doesn't help the hierarchy and adds visual clutter (on both grey and white versions).
![screen shot 2015-04-03 at 10 46 19 am](https://cloud.githubusercontent.com/assets/6873734/6983690/d98f53d0-d9ee-11e4-80d3-a7ac4a3745cc.png)

• Ability to use grey lines on the white background version (also in example above). I think this helps to reduce complexity in a long list of expandables. We also haven't used many full black lines in Flapjack (most are 50% grey) and it would be nice to be able to do this to maintain consistency. 

#### Questions

• Do we think there is a case where it would be ok to have the plus/minus minicon in the expandable format without the "show" or "hide" text? I know it is preferred for accessibility but we have found instances on mobile where having it makes headings break into multiple line prematurely, and looks very cluttered. 

| with show text | w/o show text |
| --- | --- |
| ![screen shot 2015-04-03 at 10 58 54 am](https://cloud.githubusercontent.com/assets/6873734/6983854/8e111252-d9f0-11e4-99f7-ebe72363b737.png) | ![screen shot 2015-04-03 at 10 54 36 am](https://cloud.githubusercontent.com/assets/6873734/6983861/b3909dfe-d9f0-11e4-8125-aa1e4f0c4337.png) |

• Are there other instances people have like the example of the button expand that differ from that standard styles but seem like they have valid user cases? 
![screen shot 2015-04-01 at 4 29 50 pm](https://cloud.githubusercontent.com/assets/6873734/6983898/f7049572-d9f0-11e4-938a-d5f2176b8434.png)

**Comment by stephanieosan** [comment]
If we think the lines should be grey instead of black, that's fine with me, I do think that's more in line with our normal brand styling. 

We were only using black lines because we got a file from AJ that used black lines for that type of table, so we thought we were matching the existing Flapjack pattern and code.

**Comment by duelj** [comment]
@stephanieosan - we had some inconsistency on our part with a black line version (not your fault) just thought it would be nice to have some freedom in that line coloring (who knows maybe we will have use cases for both). I think they work and look nice either way. 

**Apart from the button question I raised above, is there anything else that we need to do to have this approved?** @nataliafitzgerald, @elizbond, or @Dnpizarro

**Comment by elizbond** [comment]
Since this is UI, I think it needs @benguhin's official stamp of approval.

For publishing, @duelj can you put together the content for the expandables section of the manual?

**Comment by duelj** [comment]
Yes I am happy to mock up a design to work it into the design manual will try to post here ASAP, thanks for the help @elizbond

**Comment by nataliafitzgerald** [comment]
I'm curious as to @benguhin's thoughts on the words "Show" "Hide" in the mobile view. It definitely looks less cluttered without these words but it sounds like there's an accessibility reasoning for including? 

I far prefer the gray lines over the black. Rule lines should recede into the background and allow the type to hold its own. The black rule lines start to compete/crowd the text which is not what they should do. 

@duelj - Based on this discussion, can you compile the exact expandable standards you are proposing? There has been a lot of back and forth (and discussion) so I want to be sure that the standards are clear. That way we can more quickly push through the approvals and get the updates onto the manual.

**Comment by duelj** [comment]
Below is my proposal for the updated design manual page for expandables, it includes new sections, examples and content. Not sure if all the sections or examples are necessary but I tried to reorganize so that it was as efficient as possible. Could use feedback from design and UX if this documentation makes sense.

@nataliafitzgerald @benguhin 

![dm_expandables_v1](https://cloud.githubusercontent.com/assets/6873734/7144519/1197396e-e2b4-11e4-80d1-96c397738b2a.png)

**Comment by JenniferHoran** [comment]
I know that someone has probably already checked this box, but for Section 508 can we please ensure that the expandable links are tagged to show both current status (expanded/collapsed) and given a unique naming convention that ties them clearly to the section of content to which they belong? Otherwise a screenreader user (for example) will only hear "hide hide hide show show hide show show hide....." as they navigate through the page. Thank you!

**Comment by duelj** [comment]
@JenniferHoran great thoughts! I am not sure how or if this is currently documented in the design manual but it seems like it should be. I am open to any thoughts people ave about how/where to include this accessibility documentation in the design manual.

_My initial impression is it could be additional content for the "use" section._

**Comment by JenniferHoran** [comment]
Thank you! This is a very common problem with expandable sections, they all need to be tagged for 508 so that the assistive technology user knows where they are and what they are doing in relation to the content.

**Comment by Dnpizarro** [comment]
@nataliafitzgerald @benguhin we are looking for approval on @duelj proposal for an updated Design Manual page for expandables. 

Thanks @Scotchester for looking into the accessibility issue!

**Comment by Scotchester** [comment]
@JenniferHoran @duelj I will investigate the accessibility of these as soon as I can. Thanks for bringing it up!

**Comment by JenniferHoran** [comment]
Thanks all!

**Comment by efortiz** [comment]
@Scotchester re: accessibility/508 compliance for any item; you can provide the proper role(s) via wai-aria and assign a hidden label to the field/action itself to reflect the full action "expand [title]" or "collapse [title]" this would meet WCAG 2.0 Level AA as well as 508 – while you're at it, ensure that the call to action includes the image as well, so that when the user tabs (with assistive technology) into it the action is read once and not twice. In my opinion, exposing the full name for all users is not necessary to meet the requirements, and for seeing users may actually be a visual hindrance.

Sources:
- [WCAG](http://www.w3.org/WAI/GL/wiki/Using_the_WAI-ARIA_aria-expanded_state_to_mark_expandable_and_collapsible_regions)
- [WCAG Principle 4: Robust](http://www.w3.org/TR/WCAG20/#ensure-compat) see section 4.1.2's definition for programmatically determined (for assistive technologies) this in turns aligns to WCAG's Principle 3 - Understandable's section 3.1.2 which addresses the [language of parts](http://www.w3.org/TR/WCAG20/#meaning)

Note: 508's build-up is heavily reliant on WCAG 1.0 (as noted in http://www.section508.gov/section-508-standards-guide#Web) which is considered to be deprecated by WCAG 2.0, so meeting WCAG 2.0 (which you can run tests against) guarantees that you'll have met and exceeded original guidelines as set forth by 508.

Unrelated; hi, friends!

**Comment by JenniferHoran** [comment]
Awesome!

**Comment by duelj** [comment]
The ghost of Eduardo! Thanks @efortiz sounds like some pretty comprehensive insight! 

Also, after talking with Daniel today it sounds like we should look to move forward with the design manual layout of this here and the FEWDs can open another task if needed to resolve the accessibility questions raised by @JenniferHoran. The expandable design updates have been approved (from my understanding) but I am still awaiting approval on the updated design manual page layouts to document this new adjustments from @nataliafitzgerald and/or @benguhin

**Comment by efortiz** [comment]
@duelj my pleasure - glad to see y'all still making awesome stuff!

**Comment by benguhin** [comment]
Two questions:
1. Do we need option to have the stroke on the left and right of the expandable? At smaller screen resolutions, I think the having the stroke on all four sides makes it look less expand-able and more like an inset text box. 
2. Like @nataliafitzgerald I prefer the gray stroke, and I don't think we need to include the option for black. Is there a usecase that you've noticed where gray wouldn't work?

And here's a proposed update: I've included text changes in red, and pushed the "Use" section below the styles because I think it makes more sense in that order. I've moved the content about non-javascript users and finding hidden content to an "Accessibility" section, which can also be a good place for the information about roles and tagging. Looking ahead, it could make sense to have an "Accessibility" section for each of the UI toolkit pages.

![dm_expandables_v2-02](https://cloud.githubusercontent.com/assets/6953063/7382451/f34f4486-eddc-11e4-97ff-5865a5e1e412.png)

**Comment by duelj** [comment]
@benguhin  I think most of this sounds great. But I do have some thoughts around the questions you raised.

**1) Do we need option to have the stroke on the left and right of the expandable?**

I think we should keep this option as I can't see any reason it would hurt to have this as part of the guidelines either. FJ had just been tweaking our filter style based on user testing and have been trying to move it more inline with the expandable style. In this format we liked how the filter module seemed self contained with the boarder al the way around it. Additionally, the added freedom around stroke or background color use could allow for more flexible application in the future. For example, a stripped grouping (if there ever was a use case).

##### FJ filter expandable

![screen shot 2015-05-01 at 12 12 15 pm](https://cloud.githubusercontent.com/assets/6873734/7433044/6a0e0aba-effb-11e4-997f-9a9c9e55d09c.png)

##### Striped expandable (w/ or w/o strokes)

![screen shot 2015-05-01 at 12 17 22 pm](https://cloud.githubusercontent.com/assets/6873734/7433113/118ac1d4-effc-11e4-9311-1427c192d649.png)

**2)Is there a usecase that you've noticed where gray wouldn't work?**

I can't say that I feel the black is necessary either, but I don't mind the added flexibility that it offers by including it. There are already some tables using black stroke and some with grey, and I think they both work alright.

#### maybe we can just frame both this and the stroke use as default states and allow for added flexibility in both instances?

**Comment by benguhin** [comment]
@duelj the filter expandable is a good example – having it boxed does separate it nicely from the list of results below it. 

For the striped example, removing the strokes probably removes too much contrast, so it might be best to leave that option out. @JenniferHoran is that true?

For gray vs black, my concern is that we'll eventually end up with both styles being used on the same page, which will look odd/inconsistent, so we'll have to keep track of using only gray on some pages and only black on others. It's not a pressing issue, but keeping it to one option will help us avoid that issue in the future.

**Comment by duelj** [comment]
@benguhin I don't that we need to explicitly outline the striped version, I was more trying to make an example of how being to prescriptive in the design manual, not only makes things exceedingly complex but may eliminate some freedom that creates helpful use cases.

**Comment by duelj** [comment]
Sounds like we are super close on wrapping this up and wanted to see if anyone else had thoughts on what specifics we should include in the design manual guidelines. @Dnpizarro @nataliafitzgerald 

#### These were the areas I was thinking we pull back on the specifics of to allow more freedom:

**_Revert back to allowing strokes, top, bottom, both, or all around (maybe different wording) and mention the top and bottom stroke style as the default state.**_
![screen shot 2015-05-06 at 9 39 26 am](https://cloud.githubusercontent.com/assets/6873734/7494313/d98732e0-f3d4-11e4-99d1-ccbbe2405871.png)

**_Revert back to defining the look of a default style for multiple expandables but allow for the stroke and backgrounds to be used/adjusted as needed.**_
![screen shot 2015-05-06 at 9 40 27 am](https://cloud.githubusercontent.com/assets/6873734/7494351/199dc808-f3d5-11e4-9d52-ba7a16f13dd1.png)

**_I am on board with the grey only strokes (instead of allowing black) if that is what everyone else is happy with.**_

**Comment by mebates** [comment]
All sounds good, @duelj! I think the defaults are what should be coded in Capital Framework, right? Then designers can deviate from there at their discretion, but it'll take a bit of extra work.

**Comment by duelj** [comment]
Yup! That sounds right to me. I just wanted to make sure @benguhin was cool with the edits I mentioned above, and if anyone had input on adjusting some of the wording for those sections?

**Comment by benguhin** [comment]
This all sounds good to me! One thing I just noticed – is the "Avenir hyperlink (black)" style mentioned anywhere else in the manual? I think it works better than the Avenir paragraph for expandable header text because it's slightly heavier; with it, we could probably benefit from removing Avenir paragraph as an option for the expandable header.

That said, "Avenir hyperlink (black)" does not seem to appear in our Typography or Links sections.

**Comment by duelj** [comment]
"Avenir hyperlink (black)" doesn't appear with that specific label anywhere else that I know of. 

We do have our Avenir hyperlink style though and I just wanted to make sure that people understood that in this case it should be black. Didn't think it would be cause for concern. It could just read hyperlink and leave the color choice up to the designer too.  

If you feel that  the black color variation needs to be added to the type hierarchy I suppose that option can be removed from this discussion until you get that into the DM (so it doesn't cause confusion in the meantime) or we can run with it here as an option now. @benguhin let me know how you'd like to approach this (add hyperlink black? Remove Avenir paragraph expandable? etc.)

**Comment by mebates** [comment]
Who wants to help take this issue to the finish line?
- [ ] Add to the Design Manual
- [ ] Update Capital Framework
- [ ] Update .ai template(s) to reflect new standard

**Comment by Scotchester** [comment]
@mebates @duelj So, in the end, the only CF update that was needed was to change the color of the borders from @gray-80 to @gray-50, correct? If so, with the merging of cfpb/generator-cf#92, the "Update Capital Framework" step is complete.

**Comment by duelj** [comment]
@Scotchester  - did the updates also include the 
- 5% grey background fill
- Remove background color change on expansion (or hover)

_Sorry I didn't know how to tell from the link you included._

**Comment by Scotchester** [comment]
@duelj Crap! No, those weren't updated. Should have asked before I committed that update. Alrighty, those updates coming soon.

**Comment by duelj** [comment]
no worries! Those were the main updates I could think of, not sure if @mebates or @benguhin know of others (I was comparing to the current UI toolkit page). The only other thing I can think of is I know we show it with Georgia paragraph right now and the [use of Georgia is currently being discussed](https://github.com/cfpb/design-manual/issues/347) we will probably want flexibility there. But, maybe that is a conversation that should wait?

**Comment by benguhin** [comment]
I'm going to put together a google doc version of this DM page today so we can work out the final details

**Comment by benguhin** [comment]
Ok here's a google doc for the page: https://docs.google.com/a/cfpb.gov/document/d/1Cb4TSTokq556p3oNr69KX6M3XgO0j4HFAogvkb4xEIU/edit?usp=sharing

**Comment by Dnpizarro** [comment]
#### Update on expandable section

@benguhin and @nataliafitzgerald below is the DM page for this section. I still have to work through the examples, but I will probably need some help from a front-end to push that through. 

http://dnpizarro.github.io/design-manual/ui-toolkit/expandables.html

**Comment by duelj** [comment]
#### Trying to bring this to the finish line and it seems really close, this is my understanding of where things stand:
- Content for DM page has been created and agreed upon. [Content can be found here](https://docs.google.com/a/cfpb.gov/document/d/1Cb4TSTokq556p3oNr69KX6M3XgO0j4HFAogvkb4xEIU/edit?usp=sharing)
- There are a few design questions that are in the content doc that we need to settle before design approval @nataliafitzgerald does this sound correct?
  - Do we need a title text options other than Avenir paragraph or H4?
  - Do we need a white and grey version? 
  - Will there actually be 15px of space under the label text? Is this because of how space is measured?
  - Do we need the option to have a rule line under title in the expanded state?
- After design approval is given DM page should be ready for coding. 

#### If there are any other outstanding design questions that aren't listed above please add by the morning of Friday 2/19/16 as I plan to move on to addressing questions and prepping page on Friday

**Comment by nataliafitzgerald** [comment]
@duelj 
Thanks for reaching out! Glad we're working to wrap this one out and incorporate it into the DM. I went through the remaining open questions and commented below. Regarding style options, we should define the proper use cases for the different options. The more consistent we can get with this pattern the better.  

<strong>1. Do we need title text options other than Avenir Next paragraph or H4?</strong> I gathered up some use cases and they seem to all be using either H4 or Paragraph Medium. Are there use cases for Paragraph Regular? I don't know of a need for any other title text options.   
- Numbered list of steps (uses H4)
  http://www.consumerfinance.gov/owning-a-home/process/prepare/
- Numbered list of key facts (Paragraph Medium)
  http://www.consumerfinance.gov/know-before-you-owe/real-estate-professionals/learn-what-changed-about-mortgage-process/
- Filtering (Paragraph Medium)
  http://beta.consumerfinance.gov/blog/
  <br>

<strong>2. Do we need a white and grey version?</strong>
Are the two coloring approaches (gray versus white) unique in terms of their intended usage or are they merely stylistic options? If they have unique use cases let's be sure to define these use cases in the DM. If they are merely stylistic options, we should narrow this down to one or the other.  

Here's one possible way to define these (what do you think @duelj?): 
- Single expandables have a gray background and a 50% gray stroke all around (example: http://beta.consumerfinance.gov/blog/)
- Multiple expandables have a white background and a 50% gray stroke above and below (example:  http://www.consumerfinance.gov/owning-a-home/process/prepare/)
  <br>

<strong>3. Will there actually be 15px of space under the label text? Is this because of how space is measured?</strong>
I talked this over with @Scotchester and it sounds like we are using 10px of padding above and below based on the new spacing. We've used the new pattern in some of the recently built intermediaries pages. Does this align with what's happening on the V1 build side? @jimmynotjim  

<strong>4. Do we need the option to have a rule line under title in the expanded state?</strong>
Instead of making this optional, let's make it the standard. 

#### Additional edit
- Remove the black stroke option for the rule line above and below. The 50% gray line above and below should satisfy our needs.

**Comment by duelj** [comment]
I was looking at updating the documentation for this today and came across a couple of things that felt like they needed to be sorted before updating the page. 

**1. Do we need title text options other than Avenir Next paragraph or H4?**
Looking at removing the Avenir paragraph title because it is not differentiated enough from the expandable content.
Originally we had talked about moving away from the Avenir medium because it wasn't part of our type hierarchy but as @nataliafitzgerald pointed out it is being used and seems to be working well. [Here is the comment where this is discussed.](https://github.com/cfpb/design-manual/issues/143#issuecomment-102552208)

**2. Do we need a white and grey version?** 
I think there is a case to be made for a white and grey version at least for individual expandables. The use case would be like the filter (as mentioned on V1's blog page) where you want to highlight the expandable from the page's background color. When expandables are used in a group it makes sense to have them match the pages background. I have crafted some text around this in the page mock up I will post. 

**3. Will there actually be 15px of space under the label text? Is this because of how space is measured?**
V1 is using 15px of space (top and bottom) for our atomic expandables. I cannot speak for other projects, but according to our FEWDs there are three expandables in existence: CF expandables, atomic expandables, and the filter expandables (on blog, etc.), which is like a modified CF expandable." The last example exists since blog pages are not atomic because they were build before V1's Wagtail CMS was put into place. If they get moved over they would match the atomic expandable style (when they get moved is TBD). 

@nataliafitzgerald - You mentioned the 10px was due to updated spacing, but I am not sure i understand that reference, could you elaborate? If you are referring to the header spacing, my understanding was that the header spacing would only impact flowing passages of text not spacing in or between components. So the space between the expandable header and description copy should follow these guidelines but I didn't think they would influence space between the header and stokes or other elements. Maybe this isn't the spacing updates you were referring to though.

**4. Do we need the option to have a rule line under title in the expanded state?**
I do not think they are necessary but could be a useful option. In past conversations the general impression was to get rid of them as shown below. 
<img width="1267" alt="screen shot 2016-03-03 at 6 19 37 pm" src="https://cloud.githubusercontent.com/assets/6873734/13513071/898df752-e16c-11e5-9e74-ba4112516180.png">

@nataliafitzgerald - curious on your answer about this one, in the content doc you said lets get rid of them but on [your last comment](https://github.com/cfpb/design-manual/issues/143#issuecomment-186390025) it sounded like you wanted to keep them. Just wanted to double-check where you landed on this.

**Comment by duelj** [comment]
#### Here is an updated DM expandable page mock up reflecting some of the adjustments mentioned [above](https://github.com/cfpb/design-manual/issues/143#issuecomment-192017120)

![dm_expandables_v2](https://cloud.githubusercontent.com/assets/6873734/13513139/f8cd7192-e16c-11e5-9e3b-d4596d37c9b2.png)

**Comment by Scotchester** [comment]
**Re: item 2:** Do we have a clear use case for when a single expandable should have a white background? If so, can we specify that in the DM page?

**Re: item 3:** The spacing issue is about the top/bottom padding in the collapsed state. The spacing update that Natalia is referring to is the shift from discussing vertical padding with respect to the cap height and baseline of a line of text, to discussing it with respect to the CSS `line-height` of that line of text (so that the padding values in our design specs match what we're actually coding in CSS).

From your latest page mockup, it looks like the design intent is 15px from top to cap height, and from baseline to bottom. In which case, we'd need to code it in the CSS as about 10px. If that's the case, we should update the spec here to be 10px, and adjust your bracket diagram accordingly.

**Comment by duelj** [comment]
It could have a white background if it was on a grey well to stand out as a highlight. I felt the choice of when to use a contrasting background could be left to designer discretion. 

If the the 10px is the best way to represent our current spacing that works for me. The spacing thing confuses me, is it that in code 10px is used to mimic what 15px looks like in illustrator? Wouldn't the increment we choose cater to either devs or designers if that's the case?

**Comment by Scotchester** [comment]
Ah, expandable in a well. That makes sense.

Yes, 10px in CSS approximates what 15px from baseline to cap height (between two lines of text) would be in Illustrator. It's true that it will cater to one or the other, in a sense. But we did, in the course of the big spacing overhaul, determine that it was best for our design specs to match how they are implemented in code.

To remember why we made this decision, think of a large running text field scenario. If you have two paragraphs of text in the same frame in Illustrator, and you use Space After on the first to give them some separation, _that value_ in Illustrator will match what you want the value in CSS to be, because each line of text will also have a little built-in line height. It's only in scenarios like this one, where you're lining text up against a border or some other kind of structural boundary, that it's more natural for you to manually line it up _x_ pixels from that boundary.

**Comment by nataliafitzgerald** [comment]
@duelj 
In our updated character and paragraph style palettes for illustrator (which I will be adding to the master web template file) we are using space after values that match the code values. So, this will be consistent.

**Comment by schaferjh** [comment]
This is all looking great to me, and since it is only  the UI approval label on it, I suspect I have been a blocker. Apologies.

The interaction and UX look good to me. My main edit to the way you're presenting the information is that I suggest calling the "Types" section "Interactions" to differentiate from the "Styles" section above and more clear identify the information about default vs. accordion behaviors. (I would also be up for "Behavior" as the label).

With that change, I approve!

@caheberer Etiquette question: do I wait to see the change before removing the UI approval tag?

**Comment by caheberer** [comment]
@schaferjh I'll leave that decision to the approvers. Whatever you feel comfortable with works for me.

**Comment by duelj** [comment]
### Below are adjustments made after feedback from the design meeting (green text shows content updates and is not part of design)

**1. Updated text for when to use background color on individual expandables**
<img width="940" alt="screen shot 2016-03-10 at 4 10 28 pm" src="https://cloud.githubusercontent.com/assets/6873734/13684647/a1a08800-e6da-11e5-9e45-02fc744975be.png">

**2. Update spacing for top and bottom of expandable section**
<img width="937" alt="screen shot 2016-03-10 at 4 15 34 pm" src="https://cloud.githubusercontent.com/assets/6873734/13684795/5bc2c586-e6db-11e5-9086-66c6541f359b.png">

**3. Add content and example for title stroke**
<img width="953" alt="screen shot 2016-03-10 at 4 12 26 pm" src="https://cloud.githubusercontent.com/assets/6873734/13684707/f16e308a-e6da-11e5-8e49-27bcf8a24c5d.png">

**4. Update section heading from "Types" to "Interactions"**
<img width="951" alt="screen shot 2016-03-10 at 4 13 41 pm" src="https://cloud.githubusercontent.com/assets/6873734/13684747/179397e6-e6db-11e5-91dc-20155d50f642.png">

**Comment by schaferjh** [comment]
Looks great. Tag removed!

**Comment by jimmynotjim** [comment]
@Scotchester from what I remember about our discussions, we were going to just match what designers spec'd, even if it didn't match exactly visually. So if it looks more like 10px in CSS, we'd ignore that and still code it to the spec'd 15px, because trying to make things match perfectly is nearly impossible in Ai (other apps like Sketch handle text more like CSS)

**Comment by duelj** [comment]
#### Following up:

@nataliafitzgerald is the design end of the this good to go? @Scotchester and @jimmynotjim - where do you think we should land on the spacing thing? I will admit I understood the spacing discussion differently after the header spacing adjustments, but am happy to include what ever spacings the rest of the DM is using in their specifications. Just want to make sure I have the right measurement.

**Comment by Scotchester** [comment]
@jimmynotjim Yep, that's essentially what I was saying.

@duelj Looks good to me, now!

**Comment by duelj** [comment]
#### notes from DM meeting 3/21/16
- DM page design needs sign off
- Expandables are mostly in Capital Framework but updates/additions have not been made by V1 devs.
- Blocker: V1 devs do not have time available to make updates to DM page before regroup due to Project demands.
- Availability of V1 devs to code DM page is TBD.

**Comment by nataliafitzgerald** [comment]
@duelj 
This is looking good! 

Just a few final tweaks to the Design Manual page mock-up and we should be all set. 
- For the "Expanded" examples, can you check the padding on the left and make sure it's set to 15px? 
- In the "Group H4 with title stroke expanded state" what is the padding under the rule line? It looks like we could afford to tighten that space up a bit. 
- In the "Individual" section the expandable headings are Avenir paragraph. Should they be Avenir paragraph (medium) instead or is there a use case for Avenir paragraph (regular)?
- In the "Specifications" section, change Avenir medium to Avenir paragraph (medium).

**Comment by duelj** [comment]
@nataliafitzgerald - I have made the updates you suggested and have noted the changes below. [You can see an example of the full page here.](https://cloud.githubusercontent.com/assets/6873734/13934635/8fc5214c-ef89-11e5-8f02-05eb6d0438cb.png)

**For the "Expanded" examples, can you check the padding on the left and make sure it's set to 15px?**
Adjusted spacing on expanded group to 15px 

**In the "Group H4 with title stroke expanded state" what is the padding under the rule line?**
The space was set to 30px but I have revised it to match the 10px from the collapsed state. 

![screen shot 2016-03-21 at 5 15 12 pm](https://cloud.githubusercontent.com/assets/6873734/13934431/922b0204-ef88-11e5-9ed1-9af6de005a69.png)

**In the "Individual" section the expandable headings are Avenir paragraph. Should they be Avenir paragraph (medium) instead or is there a use case for Avenir paragraph (regular)?**
Good catch! Yes they should be Avenir paragraph (medium) I have update the titles.

![screen shot 2016-03-21 at 5 19 23 pm](https://cloud.githubusercontent.com/assets/6873734/13934539/206527d4-ef89-11e5-8007-96feed46aa22.png)

**In the "Specifications" section, change Avenir medium to Avenir paragraph (medium).**
Updated the wording in the specification as well as the wording in a couple of the example titles.
![screen shot 2016-03-21 at 5 19 37 pm](https://cloud.githubusercontent.com/assets/6873734/13934569/46470490-ef89-11e5-84f3-b76c9dadd4cf.png)

**Comment by nataliafitzgerald** [comment]
@duelj 
This looks good to go on the GD side. Make sure to add the 2 new sections to the jump link menu at the top (Interactions and Accessibility). Thanks!

**Comment by duelj** [comment]
#### [Ready to build Expandables page](https://cloud.githubusercontent.com/assets/6873734/13964561/b44d304c-f040-11e5-9651-fd1ece3b88de.png) with updates to jump links as mentioned by @nataliafitzgerald

**Comment by stephanieosan** [comment]
This is soooooo done!
