### ISSUE TITLE
Download links on logos 

### ISSUE THREAD

**Issue by ell0ell0** [cfpb/design-manual#169]
It'd be great if we could add download links for each proper log treatment. We'll be linking to the design manual from the press resources page for anyone who wants our logo. At least this way they can also see our instructions for proper useage.

**Comment by iuloshi** [comment]
Yep, there was originally a download section that was backlogged. Will add this to "release 2" -- thanks for the reminder!

**Comment by iuloshi** [comment]
@elizbond I don't know that providing our _entire_ logo suite is necessary, so which versions of the logos and what file types do you think we should provide for download in the Design Manual? I think the primary use case would be for journalists/PR people who might mention CFPB in articles, etc. 

If you list out which logo types, I'll compile a zip file for users to download. Thanks!

**Comment by Scotchester** [comment]
Bumpty-bump.

We'd like to have this available on the DM logos page so that we can link to it from the Newsroom's Press Resources page. Agreed with Mehgan that it should probably be limited to a few common formats.

Here is my suggestion:
- For print: a 300dpi CMYK JPEG (uncompressed) at 3 inches wide. (Can we foresee anyone other than ourselves using the logo any larger than that in print?)
- For web: a 72dpi RGB 8-bit PNG at 800px wide. (Just pulling that number out of thin air. Again, if anyone foresees a third party needing a larger one, speak up.)
- Mayyyyybe a WMF for PowerPoint presentations? Pretty unlikely scenario for a third party, though.

Frankly, if they need anything more than that, I say let them convert it from those themselves.

**Comment by Dnpizarro** [comment]
@elizbond I want to queue this up for Monday's meeting. Any thoughts on the above comments? I would agree with @Scotchester suggestions, they seem good to me. Let us know, If you think that there would be any additional use cases.

**Comment by nataliafitzgerald** [comment]
For print, let's provide a 300dpi CMYK EPS file. In terms of the dimensions, we can provide the standard size for an 8.5 x 11 document. This standard is is 0.5"H (and roughly 2" wide). There are instances where external vendors, like Treasury, will use larger formats for event signage and such but they should be able to create the sizes as their need arises.

**Comment by nataliafitzgerald** [comment]
Also, we use an EPS logo in our PowerPoints. We could provide an RGB EPS for PowerPoints at the same size and dimensions that we currently use in our PowerPoint template.

**Comment by mebates** [comment]
Provide: 
(cross check with what's on the Design Intranet)
- RGB and CMYK .eps
- RGB white background .png

@mebates will gather assets and deliver to @Scotchester and @himedlooff. We will take a look to see where a download link can go.

**Comment by mebates** [comment]
The current newsroom page has a png only, half way down this page on the right: http://www.consumerfinance.gov/newsroom/

**Comment by doguin** [comment]
Let's provide the same png that's available on the newsroom page for now unless there is a specific use case for other formats.

**Comment by stephanieosan** [comment]
Nope!
