### ISSUE TITLE
Style Guide PDF

### ISSUE THREAD

**Issue by iuloshi** [cfpb/design-manual#217]
@nataliafitzgerald expressed a need for a printable/PDF version of the Style Guide. Is there a way to create a PDF that pulls from the print style sheet of the Design Manual? Ideally we'd only have to make updates in one place. :)

(Side note: We'll still remove the link to the PDF Style Guide from the Design Manual for now since the printable version would only be distributed internally anyway.)

cc: @Scotchester @ohsk @stephanieosan @mebates

**Comment by benguhin** [comment]
This would be pretty sweet. I imagine that it also might be pretty difficult to do well, but if we can get learn how to rock out print/PDF stylesheets it could be a killer feature for a lot of future content on cf.gov

**Comment by Scotchester** [comment]
I have a fair bit of experience with print stylesheets and would be happy to take this on.

Auto-generation of a PDF is a different story, but I believe we have some software called PDFReactor that can help with that. I doubt it can run on GitHub Pages, though. @danny8000, can you provide any advice on this?

**Comment by mebates** [comment]
The SES team worked with PDF Reactor. I would ask David or Virginia.

**Comment by vz3** [comment]
Didn't @atbaker do something with this right before moving on? cc @gboone

**Comment by gboone** [comment]
The big thing he did before leaving a configuration change that caused it to not take _forever_ to generate a PDF. @davidakennedy is a good source for PDFReactor wisdom.

**Comment by atbaker** [comment]
And that page I added to the internal cf.gov wiki about PDFReactor! (p.s. hey everybody!)

**Comment by davidakennedy** [comment]
Oh man, it makes me sad that I am the first person people think of when they think of PDFs.

Also: Hey @atbaker! 

That said, here are my thoughts:
- PDFreactor isn't a possibility here because it requires server-side processing and **isn't** open source.
- Why PDFs? I mean, let me be honest and say that I hate PDFs. Hate isn't a strong enough word really. They have their use cases, but they add one more step to the accessibility process, are a pain to work with and are not an open format.

As an alternative, what if:

We added a Grunt task that generated the flat HTML files, with minimal CSS styles and print styles in the `head` of each page and zipped them all up in a directory with https://github.com/twolfson/grunt-zip. HTML files can be opened anywhere! Plus, with the print styles, they could be printed out.

Just a thought... I recognize that everyone isn't as anti-PDF as me. :smile:

**Comment by vz3** [comment]
I'd note that the Open Gov community seems to be moving in the anti-PDF direction as well. I can't think of any features we'd be missing by not going with a well executed print style sheet.

**Comment by mebates** [comment]
@nataliafitzgerald after reviewing this issue, it seems that many team members prefer not to produce a PDF version of the Design Manual. Is this okay? If so, please close the issue.

**Comment by ohsk** [comment]
Perhaps we could work on a print stylesheet to sidestep the need of producing and updating a bound, printed version. You could print any given part of the design manual that you like to reference offline as a formatted cheat sheet.

Right now, not so hot...

![image](https://cloud.githubusercontent.com/assets/1689222/4218221/b0da3bbc-38ef-11e4-9ed2-8ab79354e1ac.png)

**Comment by mebates** [comment]
I am going to create a new issue to work on the print styles.

We should also remove the Style Guide PDF from the Design Toolkit on the Intranet.
