### ISSUE TITLE
Paycheck illustration

### ISSUE THREAD

**Issue by ohsk** [cfpb/design-manual#220]
Hey all, here's the latest version of a paycheck illustration (originally designed by @dnpizarro) that has been used for the Community Education [Library Campaign](https://github.cfpb.gov/design-ops/library-campaign/issues/3#issuecomment-25677).

![image](https://cloud.githubusercontent.com/assets/1689222/3220189/656b6da8-effd-11e3-8c02-60c6d760897c.png)

Let us know if you have any feedback, otherwise I think this one is pretty close!

**Comment by jehlers** [comment]
Lookin good!

**Comment by mebates** [comment]
I love the squiggles.

**Comment by mebates** [comment]
@nataliafitzgerald is this approved? Should we add it to the Illustrations Library on Drive?

**Comment by mebates** [comment]
@nataliafitzgerald I will add this to the Illustration library if it is approved!

**Comment by Dnpizarro** [comment]
I'll queue this up for Monday's Design Manual Review meeting. I'll also bring up the checkbook illustration from #246 to get additional thoughts.

**Comment by nataliafitzgerald** [comment]
To clarify the issue, these are the final options for the check illustration, yes? I believe thus far we have been using "Option 2". @Dnpizarro - have we used "Option 1" yet? In comparing the two, something I like about Option 1 is that it feels less cartoonish. The cartoon element for me in Option 2 is the dollar sign in the oval. Thoughts? The gray box and lines on "Option 1" may be too light (in terms of stroke weight) to reflect our illustration style standards, however.

Thoughts from @ajbush, @elizbond, @Dnpizarro, @RKelly, or @LocraftL? 

_Option 1_ 
![screen shot 2014-11-14 at 5 02 46 pm](https://cloud.githubusercontent.com/assets/6887128/5054213/2d63a69c-6c20-11e4-922e-a949b0b730fc.png)

_Option 2_ 
![screen shot 2014-11-14 at 5 04 05 pm](https://cloud.githubusercontent.com/assets/6887128/5054229/4b274c38-6c20-11e4-81cb-950f7280a1c0.png)

**Comment by Dnpizarro** [comment]
@nataliafitzgerald Option 1 hasn't been used. I only pulled it into the discussion because @mebates was asking about a checkbook. Option 1 is supposed to be a "personal check" whereas option 2 is a "paycheck." They both have different use cases depending on the topic we are looking to address. 

In my opinion option 2 should definitely go into the illustration library since we have already used it in several different instances and option 2 (#246) could use some more discussion.

**Comment by nataliafitzgerald** [comment]
@Dnpizarro  - I do not believe that there is a widespread understanding (yet) among designers on the team that "Option 2" is a paycheck and that "Option 1" is a personal check. At least in terms of how it has been used so far. For example, in the "Immigrant Checklist" handout, we used the Option 2 check with the pen which would indicate that it is a personal check. If we are going to include a paycheck and a personal check, perhaps it would make sense to differentiate both in the illustration styling (as we are already doing) and in the coloring (so that both are not green)? The coloring of the personal check in the light tone green makes sense. But, I could also see it working in the light teal or light blue. As for the paycheck, we could look at light gray or light blue as an alternative.  

![screen shot 2014-11-14 at 6 30 09 pm](https://cloud.githubusercontent.com/assets/6887128/5055136/a176ad02-6c2c-11e4-97cf-e019c573434f.png)

**Comment by Dnpizarro** [comment]
Design Manual Review meeting 11/17/14:
- Need to make a color distinction between a paycheck and a personal check.
- @mebates volunteered to rework the existing artwork to make this distinction clearer.

**Comment by mebates** [comment]
Hey all - here's my stab at differentiating the personal check and the paycheck. Mostly I just synced up the styles and sizes and changed colors. 

![screen shot 2015-01-09 at 4 06 08 pm](https://cloud.githubusercontent.com/assets/6223901/5687356/bf2f7c3e-9819-11e4-9224-9a9e18c8a5f0.png)

**Comment by nataliafitzgerald** [comment]
I like the way these are being differentiated by color and stylistic details. 

Personal check 
On the personal check the lines along the top feel a little narrow (could be wider). The line under the top line feels particularly short (I prefer the relative dimensions of what you've done on the blue check). 

I believe the 2 lighter green lines in the middle are the "Pay to the order of" line. If so it seems, based on the example below, that the bottom line "order of" should be a little longer.  

Should we use gray for the box outline since we use gray for the lines on the check? They use a lighter gray in this example.  
![screen shot 2015-01-13 at 6 48 40 pm](https://cloud.githubusercontent.com/assets/6887128/5731712/d7a4c574-9b54-11e4-8f3d-22bc08bd7538.png)

Paycheck
On the paycheck, could we extend the line in the middle so that it is left aligned?

**Comment by mebates** [comment]
Here are @nataliafitzgerald's requested changes. Hope we can close this once she approves!

![screen shot 2015-01-21 at 3 30 40 pm](https://cloud.githubusercontent.com/assets/6223901/5844631/7b21931a-a183-11e4-9754-8265a7dd3794.png)

**Comment by Dnpizarro** [comment]
@mebates do you think we should change the "squiggly" pattern for one of the checks to reinforce the difference?

**Comment by nataliafitzgerald** [comment]
@Dnpizarro I am realizing that this was never approved. Did we still want to adjust the line pattern of one of these?

**Comment by mebates** [comment]
Using a check in an illustration today, and came back to this issue. We can remove the squiggly pattern from the personal check:

![screen shot 2015-08-17 at 12 02 48 pm](https://cloud.githubusercontent.com/assets/6223901/9309486/f31c43c2-44d7-11e5-8bed-527deb403022.png)

**Comment by mebates** [comment]
@nataliafitzgerald - would love to get approval for this illustration. What is the process now? It's on 'for review' on drive. Should we move this off of the Design Manual public repo and into our graphic design brand repo?

**Comment by designlanguage** [comment]
@mebates - I think this is a good example to include in the level of detail discussion in the graphic design repo. 

Currently the line weights are thin compared to some of our other illustrations. If it appeared in a composition with our dollar bill, it would look much more detailed. For the Reverse Mortgage booklet, I used this to represent a personal check, trying to align the amount of detail:

![screen shot 2015-06-01 at 3 03 21 pm](https://cloud.githubusercontent.com/assets/10562544/7920814/62454b4a-086f-11e5-97d6-2877f870e86d.png)

Maybe we could do something similar for the paycheck.

There's also an open question as to whether we would need a couple levels of detail in some of our illustrations. For example, a coin that takes up most of a hero space might need more detail than a coin used as a small part of a larger illustration. If you have thoughts about that, let me know.

**Comment by mebates** [comment]
You make a great point, @designlanguage. I'll add this version to the 'in progress' check, for now. I agree that we may need tiers of detail, but oof that makes things complicated!

**Comment by stephanieosan** [comment]
We don't approve illustrations through the design manual anymore.
