### ISSUE TITLE
Money Jar Illustration

### ISSUE THREAD

**Issue by nataliafitzgerald** [cfpb/design-manual#222]
The Design Ops Team has been working on this money jar illustration as a part of the community education/library) campaign. This will serve as an alternative to the piggy bank. If you are interested in earlier discussions, check out the following issues on the Design Ops repo: https://GHE/design-ops/library-campaign/issues/3
https://GHE/design-ops/library-campaign/issues/3

I worked on updates to the money jar based on the feedback we received from CE. My goal was to add in some front facing coins, simplify the styling of the side facing coins, and simplify the pattern of the side facing coins.

**_BEFORE**_
![screen shot 2014-06-12 at 1 13 32 pm](https://cloud.githubusercontent.com/assets/6887128/3261216/e51a0fc2-f256-11e3-981d-f5d5106c0de4.png)

**_AFTER**_
![screen shot 2014-06-12 at 1 08 04 pm](https://cloud.githubusercontent.com/assets/6887128/3261218/ef729976-f256-11e3-9e82-48d9f401b328.png)

**Comment by iuloshi** [comment]
The frontal view of a few of the coins definitely helps! 

I liked the ridges of the coins in the first version -- I think they add nice a subtle texture and would help identify the side profiles of the different coins, ie just some of the silver coins for dimes/quarters perhaps could have the side grooves.

**Comment by nataliafitzgerald** [comment]
AJ suggested curved corners for the coins. I also tried an alternative for the reflection on the left side of the jar. @iuloshi - In terms of adding the ridges, the issue we are having is that this illustration is quite complex and when you add other objects to the mix it starts to look very busy. But, as we move forward with developing this illustration I will keep this suggestion and mind and see if there is a way to represent it. 

Here's the jar with the curved coins:

![screen shot 2014-06-12 at 4 49 43 pm](https://cloud.githubusercontent.com/assets/6887128/3263538/30e0e1ee-f273-11e3-8e15-716f09608942.png)

**Comment by nataliafitzgerald** [comment]
I still have remaining concerns on this illustration, perhaps someone has ideas on how to address them? 
- Now that someone gave the feedback that they see this as a pill bottle, I can't stop seeing it that way too. 
- The different colors of coins starts to feel busy to me and this is without working other objects into the layout. 

In the event that we can't find a solution that works, there is still the option of bringing back the piggy bank here. This solution adds a level of friendliness and playfulness that the jar doesn't have (I will still need to make adjustments for relative sizing).   

![screen shot 2014-06-13 at 10 44 06 am](https://cloud.githubusercontent.com/assets/6887128/3271210/5cdca83c-f309-11e3-8028-ce2d183d6da3.png)

**Comment by ajbush** [comment]
Here are a few tweaks to Natalia's latest pass on this...

-I tried making the width of the coins a littler thinner
-made the pennies even thinner than the quarters to give more variation in size
-still struggled with the highlighting but tried having a highlight that sat on the front of the jar and then another in back of the jar to help show depth/transparency
-I also added in triangle shaped ridges for the side view of the coins that are pulled back to 30% so they don't jump out too much.
</br>
![jug_w_change](https://cloud.githubusercontent.com/assets/6931351/3287898/bdf03f98-f55d-11e3-8807-0236fa6ca4b9.png)
</br>

-then I tried changing the sides of the coins back to flat instead of rounded with the triangle ridges. Which I think this is working better, the rounded edges in the version above started to look like ritz crackers.
</br>
![jug_w_change_v2](https://cloud.githubusercontent.com/assets/6931351/3288689/253d3294-f565-11e3-9557-1bff64dcebf9.png)

**Comment by elizbond** [comment]
#### Feedback from the 6/24 branding meeting
- try the coins closer together
- overall, the team believes the ridges aren't necessary
- do all the $ signs have to be straight up?

**Comment by Dnpizarro** [comment]
The coin jar illustration won't be used in the library campaign materials. However, that's not to say we won't find a use for it in the future. For now I'm going to close this out, but if we find a use case in the future, feel free to reopen this issue up.
