### ISSUE TITLE
Mobile radio buttons

### ISSUE THREAD

**Issue by benguhin** [cfpb/design-manual#232]
For Consumer Response we've been trying out ways for make radio buttons more tappable / thumb-accessible on mobile phones. So far, we've attempted this by adding a background color for the full width of the tappable area:

![screen shot 2014-06-27 at 5 54 09 pm](https://cloud.githubusercontent.com/assets/6953063/3418360/e8b82e0c-fe45-11e3-8795-7250911f9c79.png)

![screen shot 2014-06-27 at 5 53 37 pm](https://cloud.githubusercontent.com/assets/6953063/3418358/e1046bbc-fe45-11e3-95fb-7a335889f3bd.png)

The second/green version is our latest, which also has a slightly taller tappable area. Anyone else trying to solve for this?

**Comment by jehlers** [comment]
@benguhin, @stephanieosan and I have been working on radio buttons for owning a home!

On desktop, they look like this:

![screen shot 2014-08-06 at 5 00 08 pm](https://cloud.githubusercontent.com/assets/4267825/3834026/b39db2f6-1dac-11e4-9d8a-a86f807aa350.png)

So for mobile, following your style above, they would look like this:

![screen shot 2014-08-06 at 5 01 30 pm](https://cloud.githubusercontent.com/assets/4267825/3834044/dfc84cd8-1dac-11e4-8df1-ad43369ce063.png)

The blue works for us here because we are following what will be the new radio button standard from issue #236

**Comment by benguhin** [comment]
Replaced by #290
