### ISSUE TITLE
Illustration hierarchy

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-manual#237]
Lots of great thoughts about our overall illustration hierarchy came up when we were talking about these illustrations: https://github.com/cfpb/design-manual/issues/208

I'm moving the broader conversation to this issue so that we can share more examples from different projects and usecases.

**Comment by nataliafitzgerald** [comment]
From a Brand 2.0 perspective, we are discussing a number of brand-specific issues here: 

**1. The addition of a level (similar to the isocon level) where illustrations live in circles.**

As a group we have discussed that adding illustration to tier 2 adds a level of flexibility and it marries well with the top level illustrations (found mainly in hero graphics). Pending questions include: Where do circle illustrations live in the hierarchy? Are the circle illustrations on the same level as isocon? If yes, how do we define when we use an isocon and when we use a circle illustration?  

**2. Illustration styling**
We should iron out any styling adjustments as part of this discussion. Some stylistic elements I see include: 
- Bleeding the illustration to the edge of the circle versus objects in the center of the circle.- Both approaches seem to work.
- A still life/scene/collection of objects versus an object. I see this mainly in the "CFPB Internship" example where a computer is shown sitting on a desk. My preference would be to preserve still life/scenes to the top tier illustration level. I feel that the tier two illustration level should be less complex given the smaller scale and where it falls in the visual hierarchy. 
- Figure/ground inclusion versus an object floating in a color field. 
- How do we determine background colors? Do we stick to a certain tint level or levels? In the Careers Page example we are only using the light tint of the green and the lighter teals and blues (the only exception is the White House where we go up one level in the blues). I don't know that we can determine any pattern with such a small set as a test group but we should keep this in mind as we move forward with developing more circle illustrations.

**3. Illustrations of people**

As we move forward, how do we define when people are the right solution and when they are not? People have been included in our illustration library for some time but we have been very careful about using them because they portray something very specific. Additionally, they add a lightheartedness to the content which may not always be appropriate. Where there has been an object-based solution that works just as well, we have used objects. We have tended towards objects illustrations because they serve more as archetypes and can speak to a larger audience in a universal way. In the same way that we steer away from stock photography of people because a photo of a person cannot universally represent all people, we have steered away from people illustrations for the same reason.

**Comment by duelj** [comment]
**1. Tier 1 vs. tier 2 ilustrations:** 

#### Where do circle illustrations live in the hierarchy?

I think that hero illustrations can be the basis for tier 1 illustrations examples. This seems like a primary place for the full illustration style to be used. The rest of the illustration usage on the site might be considered tier two since they should not draw more attention than the hero section of a page. I think circle illustrations can be a part of level two but would not have to necessarily be the only format for a level two illustration. 

#### Are the circle illustrations on the same level as isocon?

It seems like these could sit on a similar level of the hierarchy and perhaps context makes the most sense on when to use one vs. the other. Isocons seem to cover topics that are repeatedly covered on our site (complaint status, paying for college, owing a home, etc.) and that is why there is a limited library. However, illustrations can be bespoke visuals to meet a specific need and have a more niche use case (Director's Financial Analyst Program, Brandeis Honor Attorney Program). Illustrations also seem to be part of our more consumer focused visual language so perhaps they are only used there an not on more industry facing pages as well.

**Comment by nataliafitzgerald** [comment]
I have moved the discussions regarding Tier 2 Illustration Styling #240 and Illustrations of people #241 to their own issues. On this issue, let's continue the discussion about the specific of where circle illustrations fit into the illustration hierarchy. 

I agree with @duelj that it makes sense for the circle illustrations to live on the same level as the isocons. Continuing to define exactly when we use isocons is quite helpful. I am not sure whether the consumer versus industry facing distinction currently makes sense across the board since we do have an industry facing illustration library/style (the green/gray color palette, simplified styling) and since isocons are used for consumer facing content for topics repeatedly covered on our site (as @duelj mentioned).

**Comment by elizbond** [comment]
@nataliafitzgerald is this resolved? How does it relate to issue #141 ?

**Comment by Dnpizarro** [comment]
These issues have been moved to #240 and #241
