### ISSUE TITLE
Credit repair minicon

### ISSUE THREAD

**Issue by Dnpizarro** [cfpb/design-manual#247]
Consumer Response is now taking complaints for "Credit repair" amongst some other new additions. Due to these new changes I had to update a previous handout that used minicons next to every type of financial complaint they accept. Below is the minicon I came up with to represent the new topic.

![screen shot 2014-09-08 at 5 49 02 pm](https://cloud.githubusercontent.com/assets/6852363/4193701/74a6528a-37a4-11e4-92bc-748b08b345f3.png)

**Comment by nataliafitzgerald** [comment]
@Dnpizarro This is a nice approach. Where will this minicon be used? Were there other options that you came up with? I especially like the minicon in a circle. Outside of the circle the credit card feels chopped off on the top right (but maybe that interpretation is ok since we're talking about repair?). I'd like to see these to scale to see how they work at a true minicon size.

**Comment by stephanieosan** [comment]
We don't make and approve minicons in the design manual anymore!
