### ISSUE TITLE
Small Execution Logo section needs some fixin'

### ISSUE THREAD

**Issue by Scotchester** [cfpb/design-manual#259]
See: http://cfpb.github.io/design-manual/identity/logo.html#small-execution

A width of 54px on the 'cfpb' portion of the logo is far too small. The width of the 'cfpb' at the recommended desktop height (50px, given [further down the page](http://cfpb.github.io/design-manual/identity/logo.html#web-scale)), is almost 100px.

I'm guessing the 54px notion was computed from 72dpi \* 0.75", but the vast majority of computer monitors these days have much denser pixels than 72dpi. I'd suggest simply rewriting this section to say:

> The small execution lockup is used when the logo needs to scale down to less than **80**px tall. The small execution logo allows “Consumer Financial Protection Bureau” to remain legible."

I just took a pot-shot at the 80 number. Anyone know what it should actually be?

**Comment by mebates** [comment]
This issue should be solved with @klocraft's work on the new logo standards.

**Comment by klocraft** [comment]
@Scotchester, only just seeing this. But this is the perfect time to address and update. I've placed an updated small execution logo in the asset folder (the logo is now called Primary logo, not Small execution). I mainly focused on updating the color for accessibility. However, the Ai file is set as to match the standards outlined in the Design Manual:
- Logo height: 50px
- Art board (Padding): 25px
- The CFPB portion of the logo is about 100px long. The text is roughly 130 px long.

This will be the primary logo now used for all web products. Since we will be updating the design manual to reflect this change, we should set a new minimum size and confirm if the above dimensions are appropriate for our benchmark desktop size. 

I would like to reach out to all of you who are much more familiar with using the logo on the web in order to set and confirm the size standards.

To track progress, see #330

**Comment by stephanieosan** [comment]
Closing this, all logo work can be tracked here: https://github.com/cfpb/design-manual/issues/330
