### ISSUE TITLE
Button type size

### ISSUE THREAD

**Issue by mebates** [cfpb/design-manual#263]
18 months ago during our initial button exploration, we decided that button text should be 14 px. Today, it doesn't seem that many of us are using that in practice; we're sticking with the 16 px size.

@Scotchester and @himedlooff, can you confirm that button text is 16 px Avenir medium in Capital Framework?

If we all agree that this change should be made, it should be updated in the Design Manual. Perhaps issue #256 will fix it automatically?

**Comment by himedlooff** [comment]
cf-buttons are currently 14px, as noted in the docs: http://cfpb.github.io/cf-buttons/docs/

**Comment by himedlooff** [comment]
super buttons are 18px. if we change default buttons to 16px should we also change super buttons to something larger?

**Comment by himedlooff** [comment]
if you change the font-size it would make the button larger, and this could impact other patterns like the size of normal inputs, inputs next to buttons, pagination, the custom select menu...

**Comment by mebates** [comment]
The plot thickens. Thanks for all the info @himedlooff. Maybe it should stay 14 px? In Owning a Home, the 'Sign up' button on the home page is 14 px. 

@stephanieosan @duelj

**Comment by duelj** [comment]
@himedlooff - I am curious what the "normal inputs" are that you mentioned (drawing a blank on examples). 

I feel like changing the button size should not impact the other items mentioned unless the button height impacts a corresponding form field or something closely related. Super buttons are rare and usually alone which will help them stand out from standard buttons. They also have more generous padding, and a medium text weight which I think differentiates them enough that they could remain as is. 

I was under the impression that standard button text height was 16px and have been designing that way up to this point. The text at that size seems to work pretty well in the flapjack designs but I can't speak for other projects. If anything our user testing has shown that people find our 16px body copy on the small side, so I would think we would want at least 16px in our buttons. From a mobile standpoint, the 16px text with the 10px vertical padding would get us closer to the 40px touch "sweet spot" (even if only by a couple pixels ;). Pagination is already different than our button height on FJ so this shouldn't be an issue unless we want to make them match.

Ultimately, I yield to your knowledge of the coding impact but stylistically I think 16px would be a fairly smooth transition.

**Comment by himedlooff** [comment]
In Capital Framework buttons are 14px and use a medium font-weight. Super buttons are 18px and use the same font-weight. We used Design Manual/Digital Product Guide specs when they were created and haven't updated them much since. The Design manual shows these same specs currently. If you used 16px buttons in Flapjack then as FEWD's we either missed that or we figured that we already had established buttons and 2px wasn't a big enough deal to deviate from the Design Manual.

Here's how updating the font-size could affect things:
- Consider buttons next to inputs. Currently they are the same size. If the button font-size changes then it will now be bigger than an input.
- As I pointed out above buttons and super buttons are using the same font-weight, so use that to re-think the difference between super and regular buttons. It might not change your mind but I just wanted to point it out.
- Pagination uses the super button font-size and vertical padding. My point was that if you change the standard button size and as a result you also change super buttons, then pagination will be affected... unless we decide the buttons in that pattern will use its own non-standard-sized buttons.

These are all things we can deal with. I am just pointing out how some of them are currently connected.

Here's a quick screencap of some 14px vs 16px button scenarios. 
![image](https://cloud.githubusercontent.com/assets/1093373/5713869/fcd2b50c-9a8e-11e4-8fad-eb2b893f086d.png)
And the HTML version: http://codepen.io/himedlooff/pen/JoWPmj

**Comment by duelj** [comment]
great points @himedlooff, sounds like there are some good thoughts around keeping it 14px. 

*I do think the 16 & 18px set up could work. Colors and button use cases I think still allow for enough differentiation. But I am not sure of the benefit to time spent making the change is worth it. 
- I still like the legibility of the 16px versions, but the 14px doesn't  bother me either. 

| 16px medium | 14px medium | 16 & 18px together |
| --- | --- | --- |
| ![screen shot 2015-01-13 at 9 49 18 am](https://cloud.githubusercontent.com/assets/6873734/5722353/8b30ed80-9b09-11e4-9090-f7cc2e7bb800.png) | ![screen shot 2015-01-13 at 9 48 32 am](https://cloud.githubusercontent.com/assets/6873734/5722355/92e7cea4-9b09-11e4-8d07-62b4cd9c9bf6.png) | ![screen shot 2015-01-13 at 10 01 45 am](https://cloud.githubusercontent.com/assets/6873734/5722585/4bc24af2-9b0b-11e4-86a1-7db63dce2270.png) |

**Comment by mebates** [comment]
We've decided to go with a 16 px for button type size. Inputs should also increase in height to match. This work will be completed through Capital Framework. The illustrator templates will be updated.  

We'll also need to update the description in the Design Manual. The rest should pipe in through Capital Framework.

**Comment by stephanieosan** [comment]
I just updated the design manual to read 16px for button type size instead of 14px. Is Capital Framework already correct, or is it still a to-do item to update Capital Framework?

@mebates @Scotchester @himedlooff

**Comment by mebates** [comment]
The illustrator template has been updated. The total height of the button will be 33 px.

**Comment by elizbond** [comment]
@Scotchester Has this been updated in Capital Framework?

**Comment by mebates** [comment]
Pulling this into the July sprint. It has been approved but needs to be executed upon. 
- [ ] Add to the Design Manual (The words are correct, but the actual buttons still show 14 px type. I think this is because Capital Framework is not updated.)
- [ ] Update in Capital Framework
- [x] Update .ai templates to reflect new standard

**Comment by mebates** [comment]
This issue could use some quick front-end help! All we need you to do is change the type size on the button from 14 px to 16 px in Capital Framework, then make sure it's pushing through to the sample in the Design Manual.

**Comment by jimmynotjim** [comment]
@mebates I can jump on this. Does the super size get bumped up as well? https://github.com/cfpb/cf-buttons/blob/gh-pages/src/cf-buttons.less#L86

(fixed link)

**Comment by jimmynotjim** [comment]
PR opened and awaiting review in CF Buttons - https://github.com/cfpb/cf-buttons/pull/47

**Comment by ascott1** [comment]
I think this is a :clock1: record.

**Comment by stephanieosan** [comment]
Now that @jimmynotjim's PR is merged, can someone check that the button example in the design manual correctly pulled from Capital Framework and is now updated? Then we can close this issue out?

**Comment by jimmynotjim** [comment]
@stephanieosan I don't know that it auto-updates. I'm working on getting the project running locally and have an issue w/ the build process. I may try to push this whole project to cf-v1 (using @imports with versions @Scotchester :smile: ) so that we can be sure each of the components is working together correctly.

~~I should note that I've already found and fixed a bug in cf-core that needs to be merged (https://github.com/cfpb/cf-core/pull/42), so maybe someone else in @cfpb/front-end-team-admin can do that for me today~~

**Comment by jimmynotjim** [comment]
Yep, we need to update the project to CF v1 to before we can update with the button change. PR opened  -> https://github.com/cfpb/design-manual/pull/341

**Comment by Scotchester** [comment]
What about updating the standard input height to match?

**Comment by jimmynotjim** [comment]
@Scotchester good point. When an input and button are next to each other they'll no longer be the same height.

**Comment by mebates** [comment]
The button on the design manual still has 14 px size. Can we get this fixed, please? (I am asking a HMDA developer to match the standard and the standard is not correct)

**Comment by jimmynotjim** [comment]
Finally figured out what was going on here and have a fix in #373

**Comment by mebates** [comment]
WOO HOO!!! Thank you! :tada: :star: :jack_o_lantern: :ghost:
