### ISSUE TITLE
Logo placement on PDFs viewed digitally

### ISSUE THREAD

**Issue by mebates** [cfpb/design-manual#272]
Flagging this for future discussion (though I know it throws a wrench in all of our templates):

Recently, I've been noticing that whenever PDF assets are pulled up on small screens (even our standard issue Dells), the CFPB logo is at the bottom of the page is not visible. In December, at the eClosing pilot event, 3rd party software includes links to items like our OAH Closing Checklist and Form Explainers. When a user firsts opens these, they may not realize that it's a CFPB resource until they scroll down. 

Should we reconsider logo placement on PDFs intended for electronic access?

**Comment by klocraft** [comment]
Suggestions: We can set the default on all PDFs so that the full page is always visible. This would ensure the logo (and full page) is always seen when a PDF is first open. When preparing your final PDF, go to File, Properties, Initial view, Page layout, Single page. Save. This will also help provide view predictability from computer to computer.

**Comment by Scotchester** [comment]
:+1: :heavy_plus_sign::100: 

The longstanding PDF default of Fit Width was always a terrible idea. Can't believe Adobe hasn't changed it yet.

**Comment by stephanieosan** [comment]
Seems like this might still be a problem.

**Comment by caheberer** [comment]
Options:
- Move logo to top
- Check Full page on export of PDF (How does this apply to printed out PDFs)

Next steps:
- In the interim, GD's should start checking the box
- Add to GD repo about moving the logo
