### ISSUE TITLE
Isocon sizing standard 

### ISSUE THREAD

**Issue by mebates** [cfpb/design-manual#276]
Our isocon standard states that isocons shouldn't be used any larger than 200 px or 2". However, the handout template is often being used with larger iscons; closer to 2.5 or 3". Is this a violation of our standard, or should our standard be adjusted?

![screen shot 2015-02-03 at 4 28 03 pm](https://cloud.githubusercontent.com/assets/6223901/6029994/22ec7cc0-abc2-11e4-9274-ed5a4592f2f7.png)
![screen shot 2015-02-03 at 4 28 30 pm](https://cloud.githubusercontent.com/assets/6223901/6029995/22ee273c-abc2-11e4-87eb-eb51410cbac4.png)

**Comment by Dnpizarro** [comment]
@mebates have you spotted other use cases where we are going larger with our isocons. I think the handouts is where we probably go the largest. 

Also, I feel like we're probably treating the encircled versions differently than the non-circle isocons. My guess would be that the encircled isocons I've seen in some of our other work tends to be more compliant with our standards.

**Comment by nataliafitzgerald** [comment]
@mebates @Dnpizarro @klocraft - This is an important topic to bring up. It may be helpful to identify why and when we use isocons for handouts. We have some handouts that use illustration and some that use isocons. When working on a handout, do we have a reason for picking one approach or the other? Isocons are a tier 2 illustration style and tend to be used Interchangeably between consumer facing and industry facing audiences.

**Comment by Dnpizarro** [comment]
Generally speaking, we don't have many examples of using illustrations in handouts, but when we have I feel it was because our illustration library had a more accessible range of objects than our isocon library. In looking at the illustration version, I actually feel that the splash of color adds a warmth that the isocon lacks. Something to consider as we seek to resolve this issue.

![screen shot 2015-03-19 at 12 08 42 pm](https://cloud.githubusercontent.com/assets/6852363/6734835/be8b8e38-ce30-11e4-9da7-e2ac5d7cec53.png)

**Comment by klocraft** [comment]
### Identifying why and when we use isocons vs. illustrations on Handouts:

Tone has been the main factor when deciding between an isocon or an illustration.

If the tone is more serious or pragmatic, isocons fit nicely. If the tone is friendlier, or trying to create a sense of welcoming/belonging, illustrations feel more appropriate.

### Size of isocons

@mebates  brings up a good point. In addition to defining when we use isocons vs. illustrations, we also need to address size of the isocons themselves. 

I agree with @Dnpizarro, the non-circle isocons that are most often used at a larger size. 

The handouts are the biggest offender. Given the space dedicated for the image, the 2in max for the isocon is proportionality too small for the width of the Handout’s column.

**If we feel there’s a strong enough argument to continue using isocons, I recommend updating the standards to reflect the usage.**

### Pros & cons as related to Handouts:

**Illustrations**
From a hierarchy and size standpoint, the illustrations make more sense in the Handouts. However, the turn around time for Handouts is often very short, which makes custom illustrations risky. We can pull from the asset library, but we risk over-using our illustrations on smaller scale projects. (Although, these may be more visible across the Bureau?)

**Isocons**
Pro: Because there are so may minicon options, it increases the variety of isocon combinations. And, at times we want to create a more serious tone so isocons feel more appropriate. 

Cons: Sometimes the isocons feel too sterile for the tone we want to create. We would need to update the size usage standard.

**Comment by Dnpizarro** [comment]
@klocraft what if we moved forward with the illustrations, but instead of using full color we keep them to just our primary colors? I'm just trying to offer a suggestion that would still offer a distinction from the full color illustrations that we use for all of our top level materials.

**Comment by klocraft** [comment]
Good timing. I just finished up a handout project that used illustrations in our primary color palette. @nataliafitzgerald provided the same feedback suggested by @Dnpizarro. 

Moving towards an illustration-only approach solves several of the issues above, and will not result in a changes to our isocon standards.

If there's no objection, I am all for updating the handout template to include illustration "guidelines." And will close out this issue. (How lawyerly do I sound?).

Examples from recent project:
![screen shot 2015-06-01 at 2 51 35 pm](https://cloud.githubusercontent.com/assets/8646678/7920590/1f580fe4-086e-11e5-8fac-ee35ef77771e.png)
![screen shot 2015-06-01 at 2 51 12 pm](https://cloud.githubusercontent.com/assets/8646678/7920591/1f596948-086e-11e5-993d-9beac6daa568.png)
![screen shot 2015-06-01 at 2 51 24 pm](https://cloud.githubusercontent.com/assets/8646678/7920589/1f5798f2-086e-11e5-9a9c-f57bf56f2ed6.png)

**Comment by Dnpizarro** [comment]
Yes I definitely think this works! Glad we arrived at the same point. One question, the pencil in the middle is using a secondary color, was that intentional or a mistake since we're moving towards using the primary palette for the handouts?

**Comment by klocraft** [comment]
@Dnpizarro, a mistake? me? never! These illustrations were actually developed a year ago before we started exploring patterns and standards for Handout images. But, now that I'm looking at these images together, perhaps the yellow isn't needed after all.

We can use this series of document to help set illustration standards for Handouts. How much of the secondary palette should be incorporated? Should we be consistent with front face vs top facing across all handouts, or just within a series? How should we handle shadows (given the gray background)? 

This will probably end up being explored on a case by case bases. But for now, I think if we stick to the primary palette, using the secondary colors for accents, we can probably create a pretty strong foundation. @nataliafitzgerald, thoughts?

**Comment by mebates** [comment]
I think this issue can close, because we've determined not to increase the size standard of isocons. @nataliafitzgerald, if you disagree, please comment and reopen.
