### ISSUE TITLE
Official core identity language

### ISSUE THREAD

**Issue by nataliafitzgerald** [cfpb/design-manual#284]
Moving this portion of the discussion from issue https://github.com/cfpb/design-manual/issues/254

From a content perspective, there appears to be variation in our core identity language. On the Design Team, we come across a lot of use cases so it would be helpful for us to have an understanding of what is the most updated version of all of this content so that we can help spot instances where old language is still being used. This would also help us to better identify the correct visual hierarchy for this content. 

Our eventual goal down the road is to bring our editorial voice and style guide into the larger manual. So, this is a good first step.

@jameshupp - Can you read over this issue and provide your expertise?
I am looking to achieve the following: 
- Confirm the official language for "Our Mission"
- Clarify the difference between the bullet points under out mission (collateral materials - see below) and the Educate, Enforce, Empower.
- Receive final or working language for Educate, Enforce, Empower.  
- Confirm that the "How we will achieve our mission" content (used in the GPRA report) is correct and up-to-date. 
- Confirm that the "Our Vision" content (shown below) is the most up-to-date.  
- Confirm that the "Our Values" content (shown below) is the most up-to-date. 

I explored our existing materials and identified different ways that our mission is written: 
#### Our Mission in collateral materials

The CFPB is focused on making the consumer financial markets work for families by empowering consumers to take more control over their financial lives.
We are working to foster a marketplace:
- Where customers can see prices and risks upfront and where they can easily make product comparisons.
- In which no one can build a business model around unfair, deceptive, or abusive practices.
- That works for American consumers, responsible providers, and the economy as a whole. 
#### Our Mission on posters at CFPB headquarters

The consumer bureau is a 21st century agency that helps consumer finance markets work: 
- By making rules more effective,
- By consistently and fairly enforcing those rules, and
- By empowering consumers to take more control of their economic lives. 
#### Our Mission on the CFPB website

Our mission is to make markets for consumer financial products and services work for Americans — whether they are applying for a mortgage, choosing among credit cards, or using any number of other consumer financial products.
#### Our Mission in the GPRA / Strategic Budget

The CFPB is a 21st century agency that helps consumer finance markets work by making rules more effective, by consistently and fairly enforcing those rules, and by empowering consumers to take more control over their economic lives.
###### Educate

An informed consumer is the first line of defense against abusive practices.
###### Enforce

We supervise banks, credit unions, and other financial companies, and we enforce federal consumer financial laws.
###### Empower

Isocon is in development. 
##### Data-driven analysis

The CFPB is a data-driven agency. We take in data, manage it, store it, share it appropriately, and protect it from unauthorized access. Our aim is to use data purposefully, to analyze and distill data to enable informed decision-making in all internal and external functions.
##### Innovative use of technology

Technology is core to the CFPB accomplishing its mission. This means developing and leveraging technology to enhance the CFPB’s reach, impact, and effectiveness. We strive to be recognized as an innovative, 21st century agency whose approach to technology serves as a model within government.

 ##### Valuing the best people and great teamwork (not final artwork)
 At the CFPB, we believe our people are our greatest asset. Therefore, we invest in world-class training and support in order to create an environment that encourages employees at all levels to tackle complex challenges. We also believe effective teamwork extends outside the walls of the CFPB. We seek input from and collaborate with consumers, industry, government entities, and other external stakeholders.
#### Our Vision

Our vision is a consumer finance marketplace where customers can see prices and risks up front and where they can easily make product comparisons; in which no one can build a business model around unfair, deceptive, or abusive practices; that works for American consumers, responsible providers and the economy as a whole. 
#### Our Values

 We took a look at creating isocons for these but were not entirely successful. If the mission imagery (i.e. missioncons) is isometric, the values should be too.
###### Serve with integrity

Our mission begins with service to the consumer and our country. We serve our colleagues by listening to one another and by sharing our collective knowledge and experience.
###### Develop passionate leaders

Fostering leadership and collaboration at all levels is at the core of our success. We believe in investing in the growth of our colleagues and in creating an organization that is accountable to the American people.
###### Adapt, improve, and create

Our organization embraces new ideas and technology. We are focused on continuously improving, learning, and pushing ourselves to be great.

**Comment by jameshupp** [comment]
@nataliafitzgerald I am super glad you have asked about this. These feel like unforced loose ends and I'm glad to start thinking about tightening them. I think there's some value in the distinctions but not convinced they're well considered yet.

## Responses you requested (though ordered a bit differently)

### 1. GPRA language

First things first: if it's in GPRA, it's official. We follow that as the official mission of the CFPB. That version, in turn, is identical to the posters at HQ, though with slightly different punctuation. Ditto the How, Vision, and Values. That language has been through quite a bit of internal scrutiny; it is canonical. The strategic plan is supposed to be reviewed periodically (I believe every two years) but to my knowledge has not yet received a review since the existing version was created. I hereby confirm that to the best of my knowledge your 1st, 4th, 5th, and 6th bullets are correct and reflected in our GPRA language.

### 2. How the Educate, Enforce, Empower triptych is distinct from GPRA and from print material

The Educate/Enforce/Empower language is not a statement of mission but an extension of it. It is, for lack of a better way to put it, a user-centered description of the relationship we have with the public. The first prong of the official mission (HQ posters and GPRA) doesn't really give the consumer anything to _do_. E/E/E is a triptych suggested by the front office as an alternative to the website's existing Educate/Enforce/Study triptych. (The thinking here is that while analysis--study--underlies all actions we take, it is not itself an action that changes the public's experience).

The "How we achieve..." portion of the plan under GPRA is operational, an internal-facing set of tactics (analyze intelligently, use great technology, value people) in support of the mission. One could use this same internal-facing set of tactics to produce a different set of relationships with the public, e.g. "Streamline, Liberate, Enrich". So that clearly is a distinct set of information.

The distinction against print collateral is accidental, as I don't know how the collateral language came to read that way (see below). I guess they could be read as parallel, though the third collateral bullet describes outcome rather than capability. Again, it gives the consumer nothing to do. And the second bullet doesn't really emphasize the power we hold to take action.

E/E/E loosely reflects back on the three key messages that marketing research has told us consumers need to get from us: We were created in response to the crisis rather than part of it, so we are a more trustworthy source of information. We have authority to change the law if necessary for consumers and to take action against people who violate the law, and we do just that. We have tools that can help you as you move through tough financial decisions in your life.

If this all seems too loose, suggestions to tighten the relationship back to the marketing messages or back to the official mission are welcome, which I think we should be happy to work through with the front office.

### 3. Working E/E/E language

Educate: Help people understand the prices and risks of the financial products and services available to them
Enforce: Supervise companies to ensure compliance with federal financial rules, and take action to stop unfair, deceptive, or abusive practices
Empower: Provide tools and resources that help people resolve financial issues and take greater control of their financial lives

## Bonus responses!

### 4. Current website "mission" language

The language current on the site is out of date. That mission was written in 2011 as a very simple way to describe why we exist at all without committing to specific policy priorities or describing specific problems (as we had not defined any positions for ourselves yet). The "we work to" portion just below that on /the-bureau/ is likewise. This should have been addressed a long time ago, but various efforts to update this page ended prematurely as we just never had the capacity to focus on it. Since the start of Flapjack, we mostly left this alone in waiting for the newer version to come together (which includes the E/E/E language currently getting isocon treatment).

### 5. Current collateral language

This is a loose restatement of a couple other paragraphs on /the-bureau/. The principles described have at various points been how we talk about ourselves, but when put in that order and that structure I honestly don't know the origin.

**Comment by nataliafitzgerald** [comment]
It feels like this content may one day have a place in the editorial style guide. For now, there is not a clear next step.

**Comment by nataliafitzgerald** [comment]
Update: I shared this with Matt Garber (in CE) and Dan Rutherford (in Fin Ed) in today's CFPB identity portfolio meeting. 

Some recent examples of our identity language: 

Linked in Careers Page: 
https://www.linkedin.com/company/consumer-financial-protection-bureau/careers?trk=top_nav_careers

Refresh:
http://beta.consumerfinance.gov/the-bureau/

You have the right 
http://www.consumerfinance.gov/you-have-the-right/?gclid=CNeP7KDf88UCFdgRgQodvpcAtQ

**Comment by marteki** [comment]
Closing this as not relevant to the Design Manual (as we're reviewing the content strategy tasks)
