### ISSUE TITLE
Inline tooltips

### ISSUE THREAD

**Issue by marteki** [cfpb/design-manual#335]
Moving this part of the discussion from issue #139.

There's use cases for having tooltips inline, possibly in paragraph text. When this happens, our traditional methods of placing a icon after the text to be explained might not work as well.

The tooltips might be in a single line, surrounded by text.

![screen shot 2015-06-29 at 11 10 43 am](https://cloud.githubusercontent.com/assets/1183435/8419090/4205b424-1e85-11e5-80a2-ff79faec5399.png)

![screen shot 2015-06-29 at 11 11 05 am](https://cloud.githubusercontent.com/assets/1183435/8419094/47ba0f82-1e85-11e5-8635-7fcf76b0825e.png)

Or, they might be in a paragraph of text. Ideally, we'd be using plain language that wouldn't require explanations of terms outside the textual content. Due to various reasons, that doesn't always occur.

![screen shot 2015-06-29 at 9 55 33 am](https://cloud.githubusercontent.com/assets/1183435/8419108/5cf455c4-1e85-11e5-90d3-e5c1ce489083.png)

![screen shot 2015-06-29 at 9 55 02 am](https://cloud.githubusercontent.com/assets/1183435/8419110/60756116-1e85-11e5-8a01-47a519e70a21.png)

We have instances where rather than a icon, the text to be defined is underlined. However, in those instances, the interaction of tapping on that underlined text currently doesn't result in a tooltip or a pushover. The definition is given in a frame-like panel of the webpage.

![eregs](https://cloud.githubusercontent.com/assets/6953063/8412791/4372f9dc-1e5a-11e5-8008-21d1dafbf0ad.png)

Rephrased comments and questions from the previous issue that this was discussed in:
- The blue color for the tooltip could be a little distracting. We use blue consistently to show something can be activated, but should we consider toning down the impact? When used inline with text, it can disrupt the flow. Would gray or a lighter blue solve that and still maintain accessibility? (Answer given: White is only accessible on full-on Pacific Blue. The question mark would have to change to black to use a lighter blue.)
- When a tooltip icon is inline with radio buttons, it might seem at first glance like an additional option.
- Should inline tooltips follow a pattern of using a simple underline with a background color change on hover? If so, what would the indication that it's different from a link be for touch devices? And are there accessibility considerations in making it look so similar to a link? Are there concerns with having a gray underline on a white background?
- How successfully can users determine the difference between a blue underline and gray underline (and their expected behavior)?

**Comment by ielerol** [comment]
For what it's worth, we do have an outstanding issue in eRegs to differentiate the underlines for definitions from the underlines for links. It wasn't a high enough priority to make it into the changes that will be rolled out in the next month, so we haven't done a lot of exploration, but the initial thought was to change the definition links to a dotted underline style. Which only works in this case because the eRegs unvisited hyperlinks are solid rather than dotted. 

Although eRegs might not be the ideal model currently, I do think some kind of text-based visual distinction is less obtrusive than the minicon icons, when inline in text paragraphs. We've discussed also adding a faint background gray to the defined terms, lighter than the hover state gray.

**Comment by nataliafitzgerald** [comment]
DM Styling edits: 
- For content under the H3's, the width of the content should be 560 px (to match the DM styling). Update intro paragraph under "Style", "Special cases..."Inline" (also, it looks like you have skipped a header level here, was that intentional?)
- The space under the rule line that comes after "Style" should be the same as the space under the rule line that comes after "Use".
  <img width="849" alt="screen shot 2015-09-15 at 12 19 31 pm" src="https://cloud.githubusercontent.com/assets/6887128/9882700/0e90dd24-5ba4-11e5-923a-0ec9cb7c5dcb.png">
  <img width="624" alt="screen shot 2015-09-15 at 12 19 51 pm" src="https://cloud.githubusercontent.com/assets/6887128/9882711/17c34b02-5ba4-11e5-8ac1-7d6cf3c2ca86.png">
- How are you aligning the images that come to the right of the bullet lists? It looks like some are top aligned to the header for that list and some are lower down. For example, "hover" (top aligned) versus "activated" (lower down). 
  <img width="881" alt="screen shot 2015-09-15 at 12 10 57 pm" src="https://cloud.githubusercontent.com/assets/6887128/9882539/1427e800-5ba3-11e5-8314-635bbcfa7973.png">

**Comment by caheberer** [comment]
Similar to tabs, are they needed and how do we want to document on the manual?

**Comment by caheberer** [comment]
This will be documented in #139
