### ISSUE TITLE
Responsive Grid updates

### ISSUE THREAD

**Issue by mebates** [cfpb/design-manual#342]
Per our discussion on (internalgithub)/CFPB/Design-Development-Team/issues/58, we have a few small tweaks to the grid standard. 
- [x] Update the Capital Framework grid, to be **1170 width with 30 pixels of padding on each side for a total of 1230 pixel width**. It is currently 1140 width with 30 pixels of padding on each side. This update syncs it with the Illustrator template and provides even 70 pixel wide columns. 
- [x] Update the copy in the Design Manual in the following ways:
- Max width ~~1200px~~ **1230px**, background colors may bleed to edge
- Desktop: 60px **total** padding
- Portrait tablet: 30px **total** padding
- Portrait phone: 15px **total** padding

@Scotchester can you please confirm that the values for Portrait tablet and Portrait phone padding are also **total**?

Is the illustration on the Design Manual still clear and helpful?
Is there anything else that we can add to this standard to make it better?

**Comment by mebates** [comment]
One enhancement we could add is to make the grid responsive, as they're doing on the gov't style guide:
https://github.com/18F/govt-wide-patternlibrary/issues/256

**Comment by stephanieosan** [comment]
I don't understand...isn't our grid responsive?

**Comment by mebates** [comment]
Indeed it is @stephanieosan! Doh.

**Comment by duelj** [comment]
Just wanted to share a screenshot from our design template file, as we have been including 60px on either side of the grid (doesn't really change anything) just make the designs feel a little different so our total width is 1290px on our files. 

![screen shot 2015-08-05 at 5 04 11 pm](https://cloud.githubusercontent.com/assets/6873734/9097858/48110c7a-3b94-11e5-9d3d-53b32b044e02.png)

**Comment by marteki** [comment]
One note: 15px total padding on portrait phone doesn't split evenly between the two margins.

**Comment by Scotchester** [comment]
Oops, sorry I didn't respond to @mebates on the OP, but no, that's incorrect. Those numbers are for each side.

**Comment by mebates** [comment]
So the clearest way to say this may be this:
- Desktop: 30px padding on each side
- Portrait tablet: 30px padding on each side
- Portrait phone: 15px padding on each side

**Comment by Scotchester** [comment]
Exactly. Describing "total padding" is a recipe for confusion and should be avoided :)

**Comment by marteki** [comment]
Is there value in calling out what "portrait phone" and "portrait tablet" means in terms of pixel sizes, since we're using pixels explicitly to set the padding for that width?

FYI, our team is using 480px max for portrait phone (based off the phone values reported at http://viewportsizes.com/).

**Comment by duelj** [comment]
@marteki what is your min value for phone portrait? for FJ we have been using 320px as our min screen width assuming we aren't the only people stuck on BlackBerry Bold's and that lower income consumers might be on equally low res. screens. 

![screen shot 2015-08-14 at 4 54 48 pm](https://cloud.githubusercontent.com/assets/6873734/9284000/2daae090-42a6-11e5-8056-19d8c33fd128.png)

I also wonder if we are doing ourselves a disservice by labeling viewport sizes with devices? This great [article](http://alistapart.com/article/language-of-modular-design) @jimmynotjim shared makes some good points around the language we use. I wonder if it would be more helpful to speak to something like small, medium, and large viewport (not a final solution) so that we don't get caught in thinking to heavily on a 480px screen only being a mobile phone in portrait orientation (iPhone 3's & 4's landscape width is 480px). Just an idea, but I think it could offer some clarity on how we talk about the grid sizes. **Curious what others think!**

**Comment by jimmynotjim** [comment]
mobile max and tablet min are defined in CF https://github.com/cfpb/cf-core/blob/f9e72f8480289e4678119f2fef364d5a3c094c63/src/cf-vars.less#L52-L53 and we expanded that to include other sizes https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/css/cf-theme-overrides.less#L14-L18

As far as language goes, I personally use spatial labeling I picked up from Harry Roberts (palm, lap, desk, wall) https://github.com/wp-evolved/evolved-theme/blob/master/themes/evolved-child-theme/assets/src/scss/_settings.scss#L42-L47 because it's less device specific and more about the place those devices are most often used.

**Comment by duelj** [comment]
A thought came up in the hero issue around breakpoints that different teams are using (some use 7,5, or 3 from what I understand) Natalia had mentioned this to me in the [super hero issue](https://github.com/cfpb/design-manual/issues/348#issuecomment-131931289)

> In terms of the breakpoints (and I don't want to veer off into a conversation about that in this issue), it appears that there have been discussions on this in various places - and there is perhaps some inconsistency between different projects (OaH, FJ, etc.). On KBYO it sounds like the code is spec'ed for 5 breakpoints.  https://[GHE]/CFGOV/know-before-you-owe/blob/master/src/static/css/cf-theme-overrides.less @Scotchester or @danny8000 could provide more details if you want to add them to an issue that specifically discusses breakpoints. For the purposes of the hero exploration I will only use the breakpoints that are spec'ed in this issue:  https://[GHE]/flapjack/Getting-started->with-Flapjack/issues/45

I was wondering if standardizing breakpoints was something that would fall into this issue or seems like something that should be another issue? @nataliafitzgerald mentioned maybe firing up a new issue but wanted to check here first as it seemed like it might be part of this discussion.

**Comment by mebates** [comment]
@duelj yes, this seems like a great issue and time to get breakpoints settled, and to rethink the words we're using to describe each break, per @jimmynotjim. Can we document where KBYO, OaH, Retirement and cf.gov refresh have breakpoints?

| CF name | OaH breaks | cf.gov breaks | retire breaks | kbyo breaks | ccdb breaks |
| --- | --- | --- | --- | --- | --- |
| mobile | XXXpx | 0-599px | 0-480 | 0–599px | 0–599px |
| tablet portrait | XXXpx | 600-800px | 480-850 | 600–800px | 600–800px |
| tablet landscape |  |  | 940? | 801–1024px | 801–1024px |
| desktop | XXXpx | 801-1200px | 940-1190 |  | 1025px+ |
| wall | XXXpx | 1200px++ | XXXpx | 1367px+ |  |

**Comment by jimmynotjim** [comment]
@mebates Updated your table with cf-gov refresh's breakpoints

**Comment by Scotchester** [comment]
Updated @mebates's table with info from KBYO. These are the breakpoints defined with named variables, but they are _not_ all actually in use. Nothing above tablet landscape is used, in fact.

**Comment by Scotchester** [comment]
Capital Framework's grid with has been updated with the merging of cfpb/generator-cf#92. Leaving this open to continue the breakpoint discussion?

**Comment by mebates** [comment]
Great @Scotchester! Yes, let's leave it open so we can finish the breakpoint discussion. Hoping to move this along during the Monday meeting (cc: @benguhin)

**Comment by mistergone** [comment]
@mebates asked me to post our recent project breakpoints, and they are:

**Before You Claim (Social Security)**: 1190px, 850px, 480px (major breakpoints). We also have some minor handling at 1130px and 940px. Then there are lots of responsive menu breakpoints (`.nemo` stuff).

**CCDB (/complaintdatabase/)**: _These are, I believe, mostly inherited from Capital Framework, although possibly an older version. These are in ems, and I believe the HTML font-size is 16px, so I'll translate to px as best I can. I might be wrong._ 64em (1024px), 56.1875em (899px), 50.0625em (801px), 50em (800px), 47.9375em (767px), 37.5em (600px).

**Comment by nataliafitzgerald** [comment]
OaH can you post your breakpoints to the table above? Thanks! @cfarm @virginiacc @stephanieosan

**Comment by Scotchester** [comment]
Bump, @cfpb/oah-team-admin! Please provide your breakpoints so we can move forward with settling this issue.

**Comment by stephanieosan** [comment]
Our breakpoints are a little all over the map. From what I can tell, 

The journey breaks at 800 and 600.
Our current landing page breaks at 700 and 400.
The form explainer small project breaks at 600.
The explore rates tool breaks at 700.

**Comment by mebates** [comment]
The current cf.gov breakpoint scheme has four breakpoints. The big remaining question is whether or not we want to add a fifth breakpoint between 800 px and 1200 px, like KBYO, Retirement, and CCDB have. 

We may need to reference the hero discussions to see where and when breaks are necessary specifically for heros (KBYO built in some specific breaks just for the hero). 
ex: at 1024 width, the hero adjusts to a reduced type hierarchy and illustration size, so the hero is not so dominant on a tablet held in landscape form. (Scott will add screenshots below)

@Scotchester recommends major layout changes (switching to mobile menu, moving the sidebar from the side to stacked) stay on simple breaks, like the 4 that cf.gov currently reflects. There maybe specific content-based things that require more sensitive breakpoints. He thinks we should add the tablet landscape width in at around 1024. (and this would be for subtle changes, not major layout changes)

**Comment by mebates** [comment]
We also want to propose going with @jimmynotjim's device-agnostic naming convention change. The five breakpoints would be called:
- palm
- lap-portrait
- lap-landscape
- desk
- wall

The two 'lap' names are up for debate; would love other ideas!

**Comment by schaferjh** [comment]
Re: naming convention -- I met a guy at a conference who uses the Jackson Five members to name his widths. So there's that. What about t-shirt sizes?
- extra small
- small
- medium
- large
- extra large

Though it may be that those words are too common.

**Comment by Scotchester** [comment]
Here's the reason why we used the 1024px breakpoint on the guide for real estate professionals:

## With our breakpoint, the view of the site on an iPad in landscape:

![screen shot 2015-09-21 at 12 12 05](https://cloud.githubusercontent.com/assets/1044670/9997612/2b35c244-605b-11e5-9940-a67542e84bb9.png)

## Without our breakpoint (faked in this shot by just bumping the width to 1025):

![screen shot 2015-09-21 at 12 13 21](https://cloud.githubusercontent.com/assets/1044670/9997634/438dc04e-605b-11e5-9e6f-001c72acc712.png)

Notice how dominant the hero would be if we didn't scale down the text at this width and instead let it scale down as usual at the portrait tablet width. (And this doesn't even take into account the vertical space lost to the device's status bar and the browser's toolbar.)

**Comment by benguhin** [comment]
+1 to @schaferjh's suggestion for using t-shirt sizes (i.e., small vs medium vs large). Using words like "palm" and "desk" could get tricky as the standard resolutions for handhelds and desktops change over time

**Comment by Scotchester** [comment]
Here's a recap of our tentative proposal:

| Name | Range | Comments |
| --- | --- | --- |
| palm | 0–599px | When moving from 600 to 599, heading levels 1–3 drop down to the next smallest level. |
| lap-portrait | 600–800px | When moving from 801 to 800, all multi-column layouts stack into a single column, and standard desktop navigation switches to its mobile variants. |
| lap-landscape | 801–1024px | No significant universal changes at this breakpoint. Used as needed for important content-based shifts, like in the real estate pro's hero example given above. |
| desk | 1025–1200px | Standard full desktop/laptop layout |
| desk-wide | 1200px+ | No significant universal use at this time. Could be used to add additional rules for wider desktop/laptop displays. |

I'm proposing changing "wall" to "desk-wide" because I don't really see writing a media query and saying to myself "well, if this is the kind of display that's on a wall, it should do this". Additionally, practically-speaking, the vast majority of consumer laptops these days are 1376px wide, so they're already in that range, so I think a name that takes those into consideration would be wise.

I don't love the idea of t-shirt sizes. Wanting to be device agnostic is great, but when it comes down to practical implementation, people want to know, "What kinds of devices will this affect?" Changing it to something abstract will just mean more time and cognitive load spent remembering which breakpoints correspond to which pixel values.

While we want to be forward looking and be aware that common resolutions are subject to change, if the goal is to create common conventions that can be easily used across a large team and many projects, I think simplicity and ease of use reign.

**Comment by KimberlyMunoz** [comment]
The current proposal just feels like we're changing the names of phone/tablet/desktop to something that's just a little trickier to remember. Right now the breakpoints in v1 align with a one-column and two-column layout in most circumstances and I think that would work well with a small/medium/large format.

If we do go with the palm/desk thing, can we change `lap` to almost anything else? Maybe `hand` or `arm`.

**Comment by Scotchester** [comment]
I understand where you're coming from, and in fact my argument against t-shirt sizing could easily be applied also to the current proposal. I guess my thinking was that the current proposal was negligibly harder to get used to than the completely abstract size scale. But I think it's still wide open. Need a quorum of votes and then I say let the majority rule.

**Comment by benguhin** [comment]
Yeah I don't think we'll ever be able to confidently say "changes to this breakpoint will affect X type of device" anymore, and device resolutions are only going to get more varied in the next five years.

Whether we use t-shirt sizes, types of dogs, or raw numbers, I think we're better off with something that communicates relative size.

**Comment by jimmynotjim** [comment]
@KimberlyMunoz I disagree because a device on your lap can range greatly, but fit a "general" range of sizes. You don't use a device on your arm, so I really don't think that name works.

@Scotchester On your suggestions, `lap-portrait` and `lap-landscape` put us right back at device centric naming, so if we do go with `lap`, I'd recommend `lap` and `lap-wide` to match the `desk` variables.

**Edit:** Wanted to point out, because while re-reading this thread I realized there seems to be some confusion. The `palm`, `lap`, `desk` and `wall` aren't meant to match a specific device or even necessarily a size of devices. The real purpose is to get us thinking in terms of how our users interact with the site while using a device in those situations.

**Comment by Scotchester** [comment]
## Big news! We have a new proposal.

I had a big virtual powwow with the other FEWDs yesterday via chat. Here's the tl;dr:

``` less
@bp-xs-max:  600px;
@bp-sm-min:  601px;
@bp-sm-max:  900px;
@bp-med-min: 901px;
@bp-med-max: 1020px;
@bp-lg-min:  1021px;
@bp-lg-max:  1230px;
@bp-xl-min:  1231px;
```

### Because reasons
- Breakpoints should be set at intervals where a 1px difference will not make or break the experience for a particular kind of device. Therefore, the breakpoints are no longer tied to common resolutions.
- The 900px and 1020px values were set based on where we think that the primary navigation should switch from the "mobile" style to the "desktop" style (900px), and where we think that the sidebar subnavigation should start to be allowed (1020px). We chose these values by testing the navigation and sidebar at different widths and just choosing what felt right.
- These are the core **major breakpoints** where we will standardize large-scale changes, like the ones described above. _We fully endorse the use of other breakpoints in individual projects as necessary for better responsiveness of specific content modules._
- Since we're no longer breaking based on any particular common devices/resolutions, it made sense to go with the completely relative naming scheme.
- These changes shouldn't materially impact the way designers currently create their mockups.

Any questions? Comments? Dissent? Speak now, or forever hold your peace!

**Comment by marteki** [comment]
This UXer's viewpoint: :+1:

> These are the core major breakpoints where we will standardize large-scale changes, like the ones described above. **We fully endorse the use of other breakpoints in individual projects as necessary for better responsiveness of specific content modules.**

Thank you! :dancer: :dancer: :dancer:

**Comment by benguhin** [comment]
:+1:

**Comment by Scotchester** [comment]
Last call for dissent before we [implement this in our variables file](https://github.com/cfpb/cf-core/pull/44)!

**Comment by Scotchester** [comment]
Sold! :hammer:

[RIP gavel emoji :cry:]

**Comment by mebates** [comment]
@Scotchester playing catchup: should we add this thinking / these breakpoints to the 'grid' page of the Design Manual in any way? Along with the _"We fully endorse the use of other breakpoints in individual projects as necessary for better responsiveness of specific content modules."_ caveat?

**Comment by Scotchester** [comment]
Sure!

**Comment by jimmynotjim** [comment]
Late status update, but since implementation started in v1, we've realized main nav and side-nav need to happen at the same time. We've since changed our recommendation that sidebars enter in at `@bp-med-min` aka `901px`. We've found there's a few places the `1020px` value works so we're not recommending changing the variables themselves.

**Comment by mebates** [comment]
Working on adding the breakpoints to the Grid section of the Design Manual here: https://github.com/cfpb/design-manual/pull/376
