### ISSUE TITLE
Alerts, validation and error messaging

### ISSUE THREAD

**Issue by benguhin** [cfpb/design-manual#343]
@duelj posted has some great designs in the Getting Started with Flapjack repo that still haven't made it out to the public one yet (I think)

**Comment by mebates** [comment]
https://pages.18f.gov/govt-wide-patternlibrary/components/#alerts

**Comment by duelj** [comment]
@benguhin - thanks and wanted to share the link to Getting Started with Flapjack 

[Form error states](https://github.cfpb.gov/flapjack/Getting-started-with-Flapjack/issues/31#issuecomment-44549)

**Comment by jimmynotjim** [comment]
These form states are in the public repo ([view the PR here](https://github.com/cfpb/cfgov-refresh/pull/589)), and will become a CF component as soon as I have time finishing it.

**Comment by cafescience** [comment]
These are a few use cases for page level notifications that I've found on websites or in discussions. Please let me know any additional cases I'm missing.
1. Validate multiple fields at once
2. Errors for filter out of range. Example: http://build.consumerfinance.gov/owning-a-home/explore-rates/

![screen shot 2015-09-15 at 10 24 51 am](https://cloud.githubusercontent.com/assets/4876320/9879287/b78f8f16-5b94-11e5-9ae7-743783705271.png)
1. From the gov-uk alerts page: http://govuk-elements.herokuapp.com/errors/example-form-validation-multiple-questions
- As a notification that keeps people informed of the status of the system and which may or may not require the user to respond. This includes errors, warnings, and general updates.
- As a validation message that alerts someone that they just did something that needs to be corrected, or as confirmation that a task was completed successfully.

**Comment by cafescience** [comment]
Colors for the alerts given in the public repo: https://github.com/cfpb/cfgov-refresh/pull/589
- These run into problems when links are contained in the notifications because there's a lack of contrast with the pacific blue

Using the lighter colors from hex values given by @designlanguage the contrast check at https://github.com/cfpb/cfgov-refresh/pull/589 still gives a failure response. Example:

![screen shot 2015-09-15 at 10 38 02 am](https://cloud.githubusercontent.com/assets/4876320/9879551/e0a6e5c4-5b95-11e5-89ab-32f6eaf23f79.png)

One option maybe to use a deeper blue for the links inside notifications?

**Comment by cafescience** [comment]
Guidelines for when to use page-level errors are nicely laid out on the 18F page:
https://github.com/18F/web-design-standards/blob/18f-pages-staging/_components/alerts.md

Do we have a comparable page with guidelines or should our alerts guidelines be some form of paraphrasing this?

![image](https://cloud.githubusercontent.com/assets/4876320/9879843/0eea7080-5b97-11e5-882d-accb1384ac4b.png)

**Comment by cafescience** [comment]
Quick note: @cafescience = David Fenigstein

**Comment by benguhin** [comment]
![99526508-57d1-11e5-8e7a-815ef38feffa](https://cloud.githubusercontent.com/assets/6953063/9890394/b111920e-5bcd-11e5-95d7-8a3effe8d3aa.png)

**Comment by benguhin** [comment]
<img width="1578" alt="screen shot 2015-09-15 at 5 20 05 pm" src="https://cloud.githubusercontent.com/assets/6953063/9890464/0adbbd50-5bce-11e5-8d4f-ea652cee0c59.png">

**Comment by duelj** [comment]
@cafescience - in regards to the notifications/alerts containing links at the page level, its a good point about the accessibility of the color used. We moved forward with those colors because our impression was that alerts at the page level shouldn't contain a CTA, thus the link contrast was not an issue. I would be interested to hear some UX thinking on whether it makes sense to include links in a page level notification, in the example from @benguhin what was the interaction that got the user to this point and is a page level error state the best way to share this information with the user? 
<img width="765" alt="screen shot 2015-09-17 at 1 15 15 pm" src="https://cloud.githubusercontent.com/assets/6873734/9940506/446c59a0-5d3e-11e5-9cc8-487a9ae3be79.png">

**Comment by cafescience** [comment]
A Google doc containing a (very) rough wireframe of Alerts usage is located at https://docs.google.com/document/d/1ugZ4uEM26pDSFNEQWRALgJdJfSiUMCTBbvFogApG3Co

**Comment by cafescience** [comment]
@benguhin @nataliafitzgerald : Can you guys take a look at the current doc and let me know if it's ready to build a design manual page? Thanks!

https://docs.google.com/document/d/1ugZ4uEM26pDSFNEQWRALgJdJfSiUMCTBbvFogApG3Co/edit

**Comment by nataliafitzgerald** [comment]
@cafescience - I added my feedback to the GoogleDoc. Let me know if you have any questions or alert me when you have updated the document. Thanks!

**Comment by benguhin** [comment]
From a UI perspective, this looks great and ready

**Comment by cafescience** [comment]
Thanks @benguhin and @nataliafitzgerald. I've coded up the page, and would love for you guys to give it a quick once-over before I make the pull request. The url is http://cafescience.github.io/design-manual/ui-toolkit/notifications.html

Thanks!

**Comment by nataliafitzgerald** [comment]
This looks good. I have some copy edits that shouldn't be too cumbersome. 
- Change the main title to sentence case: "Alerts, validation, and error messaging". (CFPB standard)
- Under uses, instead of bolding the words of the thing you are highlighting, can you add a header? This is more consistent with what we do throughout the manual and it will help when skimming. So, it could be Header: "Alerts" Content: "Alert notifications communicate..." (with no bolding). 
- For consistency, we could change "Error notification" to "Error messaging" in the Use section. 
-  Under Alerts, the second sentence isn't reading right: "Think about how much context to provide with your message."...I would add something to the effect of "Consider the amount of context that is necessary to..." or "Think about how much context is needed..." OR "Consider the complexity of your message when deciding on how much context to provide." OR ""Consider the complexity of your message when deciding how much context you should provide."
- Change colon to an em dash (for consistency): Be careful not to overdo it—too many notifications will either overwhelm or annoy the user, and are likely to be ignored." 
- Space above "Adding hyperlinks" header feels tight. 
- Overall make sure that you keep the same order for the 3 types of notifications that we are talking about. Currently this is switching around throughout the page. 
- Change "Above Content" and "Covering Content" to sentence case.  (CFPB standard)
- Space above "Covering content" header feels too tight. 
- In the styling section, add the names of the colors, rather than the hex codes. Look here for reference: https://cfpb.github.io/design-manual/ui-toolkit/buttons.html
- For font names, the weight should be capitalized, for example "Avenir Next Medium"
- Swap in this revised copy: "Use distinct icons, contrasting colors, prominent placement, and text to indicate errors. Don’t rely on just one method as users can have many different accessibility needs (for example, color blindness, visually impairment, or motor control issues).

**Comment by cafescience** [comment]
I've completed all changes except the color names. The hex numbers are all from the new palette, and I'm not sure what the percentages are for each color, or if any of the names have been changed from the "Buttons" page.

**Comment by Scotchester** [comment]
@cafescience You can refer to the table in [this comment](https://github.com/cfpb/design-manual/issues/327#issuecomment-144744768) for the new naming scheme. Cross-reference it with the first table in [this comment](https://github.com/cfpb/design-manual/issues/327#issuecomment-140925068) to pair the hex code with the name.

**Comment by caheberer** [comment]
Closing this issue, we're adding this update to the manual as part of the form fields exploration in #346.
