### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by benguhin** [cfpb/design-manual#345]
Note that the Flapjack folks have already started working on this for the newsroom section. Assigning to @ohsk and the other folks on Complaint Analytics

**Comment by duelj** [comment]
Here is the exploration that Flapjack has on [filters](https://github.cfpb.gov/flapjack/Getting-started-with-Flapjack/issues/40) so far for our use cases. You can see examples on [blog](http://beta.consumerfinance.gov/blog/), [Newroom](http://beta.consumerfinance.gov/newsroom/), and [Activity Log](http://beta.consumerfinance.gov/activity-log/)

**Comment by ielerol** [comment]
Here's a collection of filters examples from the current site, as well as in development.

### Ask CFPB:

![ask cfpb filter 1](https://cloud.githubusercontent.com/assets/10562543/9776907/65599fce-5712-11e5-8704-4c50b4b7f352.png)
http://www.consumerfinance.gov/askcfpb/search/?selected_facets=category_exact:mortgages&selected_facets=tag_exact:reverse%20mortgage

### HMDA:

![hmda filters](https://cloud.githubusercontent.com/assets/10562543/9776920/87e61ef0-5712-11e5-8786-e3bd528f620b.png)
http://www.consumerfinance.gov/hmda/explore

## Redline Risk Assessment Tool

![fair lending visualization 1](https://cloud.githubusercontent.com/assets/10562543/9908430/700e87c8-5c48-11e5-8afb-bac34b1f06d1.png)
http://flc.demo.cfpb.gov/institutions/

### Flapjack (V1?):

![flapjack filter 1](https://cloud.githubusercontent.com/assets/10562543/9776954/07787ce4-5713-11e5-98f6-5b5e2f58acc1.png)
http://beta.consumerfinance.gov/blog/

### Complaint Analytics:

![complaint analytics filters](https://cloud.githubusercontent.com/assets/10562543/9776970/2967ad7a-5713-11e5-9945-c4affbbb59d6.png)

**Comment by mistergone** [comment]
Hello! This might be a bit premature, but I wanted to ask how the filter discussion affects tables (#153). Filters are included in the tables specification, so eventually I'd like to talk about whether the filters code will work on tables, or if tables needs its own implementation, etc. If someone can get in touch with me to discuss, I'd appreciate it! :smile:  :dancer: :octopus:

**Comment by marteki** [comment]
I hear that the FEWD devs in general agreed last week that code for our Design Manual components should only be written once in one place, and should work with any needed use cases (tables, etc.)

The code for tables is being buttoned up _this week_. Whoever will be developing this, please reach out personally to @mistergone to make sure that our different teams' assumptions about how filtering works with tables are the same.

**Comment by ielerol** [comment]
A first draft of filter recommendations is [available here.](https://docs.google.com/a/cfpb.gov/document/d/1EwRStR8sRUM_NXcdjXOcDeqMvdXh6GoJtvzhQwCHvjA/edit?usp=sharing) Please let me know what you think!

Questions I have right now: 
- Is this the right level of detail for recommendations on how the filters themselves work? A lot of filtering situations are fairly complex and specific, so I didn't want to go too deep in dictating whether, for example, a sidebar vs. the Flapjack style should be used, in what situations. I have opinions, but I don't know how prescriptive the design manual should be on this topic, so right now it's more a collection of best practices for keeping filters usable. 
- What's the right number of items to recommend for filtering? Sometimes it's really obvious, like with the big databases we maintain, but for tables of information on content pages, we should probably have some guidelines. My inclination is to base it around pages rather than numbers of items, because if you can see 50 rows of data at a time, a 150-row table is not so bad to scan through, but if you can only see 10 rows, 15 pages becomes a lot of clicking and it's difficult to compare information across pages. Or for blog posts and articles, you'll probably never see more than a few at a time on one page, so searching and filtering becomes important at even smaller numbers of posts.

**Comment by ohsk** [comment]
Good work @ielerol! I think this is a really great start. I'm in favor of keeping things more on the use-case / best practices side of things that you've outlined, rather than prescribing layouts and structures at this point. The implementation of filters can vary so much depending on the nature of the content that's being filtered. But the example use cases can provide a really good starting point for folks.

@adinneen had some [research on filter truncation and other best practices](https://github.cfpb.gov/ConsumerResponse/complaint-analytics-search-tool/issues/4#issuecomment-48230) that we could reference as well:

#### [The Current State Of E-Commerce Filtering](http://www.smashingmagazine.com/2015/04/20/the-current-state-of-e-commerce-filtering/) by Christian Holst

> Take aways: 
> - 1) contextual filtering is an industry leading practice but quite complicated; 
> - 2) provide users with thematic filters; 
> - 3) there are three main ways to deal with long lists of filtering values: a) display all values in a long list, b) create an inline scrolling area, c) truncate the filtering value. A and B yielded the worst usability issues. REI provides a really good model for option C - the preferred way. The optimal number of truncated values is between 6 and 10 and styling the truncation link so it is very visible is hugely important. Also the standard is to display truncated values alphabetically so that the user knows truncation has happened; 
> - 4) People view categories as something they need to select and filters as purely optional.

**Comment by ielerol** [comment]
Thanks @ohsk! That article is great. I will look around to see if anyone has tested entirely collapsed filters against the truncated list. Everything we have currently either shows all options all the time, or allows for hiding sections entirely, and I don't know whether we'd have time in the current effort to code something appropriate, but if it makes enough difference it might be worth looking at for future implementation.

**Comment by ielerol** [comment]
Here's an initial draft of the design manual page, with some of the changes incorporated: http://ielerol.github.io/design-manual/ui-toolkit/filters.html

when @ascott1 and I are both in the office at the same time, we should talk about the possibility of getting live code for the guidelines sections.

**Comment by ascott1** [comment]
> when @ascott1 and I are both in the office at the same time, we should talk about the possibility of getting live code for the guidelines sections.

Agreed! 

Also, here's a list of jQuery filtering plugins. We may want to look to these as an example for how to build something that is applicable to different use cases http://www.unheap.com/section/user-interface/filter-sort/

**Comment by benguhin** [comment]
This is great – I love how it builds off of the work we've done with form fields

**Comment by caheberer** [comment]
We have filters in V1 and documented on the DM. From DM perspective we can close this issue.

@jimmynotjim @Scotchester  have filters been made a CF component? Curious if I should close or tag this as Add to CF-Backlog.

**Comment by jimmynotjim** [comment]
@caheberer Filters are just regular form fields within generic layout components and have been updated for the v4 release. I think if they're documented here, we can close this out.
