### ISSUE TITLE
Defining the use of Avenir Next vs. Georgia

### ISSUE THREAD

**Issue by nataliafitzgerald** [cfpb/design-manual#347]
Up until now the use case for Avenir Next paragraph versus Georgia paragraph has been loosely defined. In working through our various web products, designers have been left to rules of thumb, design discretion, and guess work. I have received feedback from at least one of our front ends @Scotchester that more definition would be very helpful. So, I'm kicking off this conversation with the end goal of pushing us toward some concrete guidelines. 

Looking through different products, the approaches are varied. 
#### Design Manual

The Design Manual has what feels like a clear approach/hierarchy basis for when Georgia is used. 
- Avenir Next is used for all headers. 
- For paragraph text that sits under H1 or H2, the Avenir Next paragraph style is used. 
- For paragraph text that sits under H3-H6, Georgia paragraph text is used. 
- Paragraph text in gray boxes is in Avenir Next. 
- For expandables, Georgia paragraph text is used for the body copy with the exception of gray text boxes which have Avenir Next paragraph text. 

![screen shot 2015-08-07 at 3 29 58 pm](https://cloud.githubusercontent.com/assets/6887128/9144167/2fcd1be6-3d19-11e5-8c10-77c144c0bf36.png)
https://cfpb.github.io/design-manual/identity/logo.html @ohsk 
#### consumerfinance.gov refresh
- Avenir Next is used for all headers. 
- Georgia is used for paragraph text on the Blog and Press Release pages. 
- As a rule of thumb, Georgia is used for "long body copy". Basing the font decision on the length of copy (something that can change) poses problems. It works best when applied more specifically/globally, like what we do on Blog and Press Release. 
- Paragraph text in gray boxes is in Avenir Next. 
- For expandables, Georgia paragraph text is used for the body copy with the exception of gray text boxes which have Avenir Next paragraph text. 
##### Careers

![screen shot 2015-08-07 at 3 38 40 pm](https://cloud.githubusercontent.com/assets/6887128/9144408/b68745de-3d1a-11e5-8e9d-f6d1e9bd50d9.png)
##### Blog

![screen shot 2015-08-07 at 3 40 25 pm](https://cloud.githubusercontent.com/assets/6887128/9144406/afdaba9a-3d1a-11e5-98db-a1a267a3c3ad.png)
##### The Bureau
- On this page I am not sure what the logic is for when Georgia is used. I am also not sure that what I'm seeing on build fully reflects the graphic design layouts. @ajbush @duelj 
  ![screen shot 2015-08-07 at 4 27 23 pm](https://cloud.githubusercontent.com/assets/6887128/9145665/707828ce-3d24-11e5-84f8-6ab675f218db.png)
#### Owning a Home
- Georgia is not used at all. 

![screen shot 2015-08-07 at 3 28 21 pm](https://cloud.githubusercontent.com/assets/6887128/9144133/f83412a2-3d18-11e5-8ea5-6631618acebd.png)
http://www.consumerfinance.gov/owning-a-home/ @stephanieosan 
#### Retirement - Before you claim
- Georgia is not used at all. 

![screen shot 2015-08-07 at 3 56 56 pm](https://cloud.githubusercontent.com/assets/6887128/9144746/0adc0528-3d1d-11e5-94dd-6ca8b7a9596c.png) @caheberer 
#### Everyone has a story
- Georgia is used for paragraph text under H3. There are no instances of H4-H6 so it is unclear as to whether this matches the Design Manual layout approach.

![screen shot 2015-08-07 at 3 58 34 pm](https://cloud.githubusercontent.com/assets/6887128/9144786/54c41c2a-3d1d-11e5-925a-f380212376d9.png)
#### To summarize my findings from this limited landscape review, here are the consistencies:
- Avenir Next is used for all headers. 
- Paragraph text in gray boxes is in Avenir Next. 
- For expandables, Georgia paragraph text is used for the body copy with the exception of gray text boxes within the expandable. Paragraph text in these boxes is in Avenir Next paragraph text (this is a pattern in CF/DM).
##### Design Manual layout and Everyone has a story page
- For paragraph text that sits under H1 or H2, the Avenir Next paragraph style is used. 
- For paragraph text that sits under H3-H6, Georgia paragraph text is used (H4-H6 approach is assumed for EHAS). 
##### Consumerfinance.gov refresh
- Georgia is used for paragraph text on the Blog and Press Release pages. 
- As a rule of thumb, Georgia is used for "long body copy". How is this defined? Anything more than 2 paragraphs?  

Defining the use of the Georgia paragraph based on the length of the content does not feel sustainable, unless this gauge is being used to define the styling approach for entire sections/content types (eg. Blog body copy, Press Release body copy). But, there could be a way that even in our Blog and Press Release pages there is some greater logic so that the rule isn't simply that these pages have long body copy. We must define our parameters more concretely. Going with the Design Manual approach would mean a lot more Georgia on our web products. And, no one is crazy about Georgia. There is the option of introducing a new, more desirable serif font in the future, of course, but we know those changes take time. And consistency and an approach to applying the correct styling is needed sooner rather than later. 

And here I open the floor for discussion....

**Comment by stephanieosan** [comment]
@nataliafitzgerald We use Georgia on Owning a Home, just not on the landing page. That said, I don't think we have a great rational for when we use it. We use it on our content-heavier pages, check out cf.gov/loan-options  (expand to find) or [buildserver]/owning-a-home/process/prepare (expand to find).

**Comment by Dnpizarro** [comment]
At yesterday's Falling Water working session I brought this issue up to the group. Generally, some of the consensus that we came to is that we should limit the use of Georgia. How exactly, that has yet to be determined, but the existing rule being used in FJ is that we use Georgia for multiple paragraphs, meaning 2 paragraphs or more. This works well in certain cases but isn't a tight enough rationale moving forward. @duelj will be looking into this issue from FJ's perspective, but it would helpful to have input from other teams dealing with web projects. 

@nataliafitzgerald @klocraft @huetingj @ajbush @caheberer

**Comment by cfarm** [comment]
As a developer I would appreciate some consistency for font use with specific design patterns. I sometimes find an existing Capital Framework pattern that I can reuse for OAH, except that the font will be different. 

Ideally we'll define the use case for each font style, and then code those patterns for Capital Framework and I'll never have to write a CSS font declaration ever again :smile_cat:

**Comment by duelj** [comment]
#### When does FJ use Georgia?

Our working rule was that when a section of body copy was going to be long (roughly defined as 3 or more sentences) we were employing the use of Georgia for legibility. This resulted in pages such as [the bureau](http://beta.consumerfinance.gov/the-bureau/) which seem to be using Georgia randomly.  More recently we have moved away from using Georgia at all for this reason. An example of this would be most any of the office sub pages such as Ombudsman's office [charter page](http://flapjack.demo.cfpb.gov/sub-pages/ombudsman-charter/) Additionally, as we look to build in a more modular fashion we are looking to more clearly define the specs of a given module, which also doesn't play well with the above guideline.

#### Did this 3+ sentence guideline work anywhere?

This did seem to work well on pages dedicated to long sections of text content ([blog post](http://beta.consumerfinance.gov/blog/managing-someone-elses-money-virginia/), [news article](http://beta.consumerfinance.gov/newsroom/cfpb-and-new-york-department-of-financial-services-sue-pension-advance-companies-for-deceiving-consumers-about-loan-costs/), [bio page](http://beta.consumerfinance.gov/the-bureau/about-rich-cordray/), or [events](http://beta.consumerfinance.gov/events/fall-community-bank-advisory-council-meeting-in-washington-dc/)) We could count on these pages having longer passages of text and the Georgia use seemed fitting for these more editorially focused pages. 

#### What might work better?

We have generally moved away  from using Georgia unless it is on an editorial page as mentioned above. Perhaps a page type approach would be useful, but I can also see it making for a very narrow use case.

**Comment by benguhin** [comment]
@duelj to update these guidelines

**Comment by duelj** [comment]
### Update after design manual monthly 10/20/15:
- Have a couple of solutions in mind for when Georgia should be used on the web.
  - Contextually - when page is known,  and will primarily be editorial or a long passage of text. 
  - Hierarchy based - certain combinations of headers paragraph copy will use Georgia as that paragraph font. 
  - Content length - Georgia would only be used on paragraph copy of certain lengths (e.g. 3+ sentences, or 2+ paragraphs)
- Need to resolve pros and cons of each solution and pick one to move forward with. 
- Agreed we do not want to fully get rid of Georgia use, but need clearer guidelines on when it should be used. 
- General agreement that Georgia use is better for longer sections of copy (for legibility) and works better lower on the page (used more be supplemental or detail information).

**Comment by duelj** [comment]
I wanted to share some thoughts around each of the proposed solutions sharing their merits and flaws but will focus most of the detail on the contextual solution which I feel could be the best solution to move forward with. **If others feel more strongly about one of the other solutions please feel free to share more examples of that solution style.**

### Hierarchy Based -

In this solution certain combinations of headers & paragraph copy would use Georgia as the paragraph font. Not sure on the proposed details of this format please chime in @nataliafitzgerald. Headers 1-4 would use Avenir paragraph and headers 5 & 6 would use Georgia paragraph

##### Pros:
- Clear system for when and when not to use Georgia (very little grey area)
- Could carry across standard between web & print easily

##### Cons:
- Headers are used in many different contexts that don't all work cleanly with using Georgia, because they are short sections of copy high on the page. An example of this is sidebar modules (which mostly use h5) which can be followed by a short description rather than a long passage of copy. 
- Could lead to a lot more intermixing sections of Avenir and Georgia paragraph copy on the same page.

---

### Content Length

In this solution the length of the paragraph copy used would dictate wether Avenir or Georgia is used. There would be some threshold that would define when a section of copy was considered 'long' and Georgia would be used in those instances (e.g. 3+ sentences or 2+ paragraphs = long).

##### Pros:
- As a group we agree that Georgia is most effective for longer passages of text and this guideline focuses on that use case. 

##### Cons:
- Web content changes frequently and until you get final copy for a page it is hard to know if a section should use Avenir or Georgia. 
- Hard to build consistent molecules with this format (e.g. introduction sections with long text may use Georgia and short ones would use Avenir) this can seem inconsistent from page to page. 
- Could lead to a lot more intermixing sections of Avenir and Georgia paragraph copy on the same page.

---

### Contextual

In this solution  Georgia would be used for paragraph text on certain page types and use cases. In the V1 page templates this would mean that we could reserve use of Georgia text to Browse and Learn pages which would feature more detailed content. This would reserve the 

##### Pros
- Basing the use on the template allows us to target page types that contain more editorial content and not have Georgia on landing pages, which mainly function to direct users down different pathways.
- Because we want to be intentional with when we are using Georgia this guideline allows us to focus most closely on the way we want to use it.
- Can curate the use of Georgia for specific use cases (e.g. blog post copy, tool tip copy) on a given page type. 
- Keeps Georgia use off of Landing pages and out of browse pages where it doesn’t seem as effective, while allowing freedom of use for different scenarios in appropriate page types. 

##### Cons
- Not a hard and fast rule, allows flexibility depending on needs of page/project which makes it a little more abstract. 
- Harder guideline to use for those who are not currently using the V1 pages styles (landing,browse,learn). This should only improve as people adopt this framework

**Comment by nataliafitzgerald** [comment]
@duelj - Thanks for your detailed exploration. I haven't had a chance to read through it carefully but I will. Perhaps we can talk through this at the next Graphic Design meeting.

**Comment by ajbush** [comment]
I dunno if this has been brought up and it would be a pretty big shift for us but I wonder if we could allow this decision to be up to the user?

I've noticed a couple sites that allow toggling of sans-serif and serif fonts. We could default to Avenir but allow users to change to serif fonts on extremely long reads like in the blog. I know there's a lot of suggestion to use serif fonts for long reads but I wonder if it's really the case today if every other site users are coming in contact with are using mostly sans-serif fonts?

I know we had on the backlog for maybe a future release of the site to incorporate a button to increase font size so I wonder if this could be a part of that work?

**Comment by duelj** [comment]
@ajbush - that's a cool idea. I could see the type size and style molecule working well together too. It could be kinda like the text options on an e-reader or ibooks uses on a more basic level? 
![ibooks-scrolling](https://cloud.githubusercontent.com/assets/6873734/11275281/eec3bc34-8eaa-11e5-9d9f-0c94435e0933.jpg)

**Comment by caheberer** [comment]
Notes from DM meeting 1/23:
Avenir is default sitewide. 

When should GDs use Georgia if at all?
Do users desire a sans serif font? Is Georgia more readable?

Where are we now in documenting the use of Georgia? 
Has anything come up in testing that long paragraphs of content in avenir is difficult?

Seems like print is also moving towards getting rid of Georgia. 

Next Steps:

- Update DM to remove Georgia. 
- Test Avenir for long paragraphs (Possibly test on Money As You Grow Book Club)
- Talk with Jennifer Horan 
- Review testing from Dynamic Disclosures (How to ask about size of type, etc. without asking about it)

**Comment by nataliafitzgerald** [comment]
Georgia has now been removed from the Design Manual so I'm closing this one out.
