### ISSUE TITLE
Featured content module visual design

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-manual#351]
This issue is to explore the visual design for featured content modules.

For more information about the featured content use case, check out this issue: [natalie's use case issue]

**Comment by duelj** [comment]
#### Exploration on [Bureau Page](http://beta.consumerfinance.gov/the-bureau/)

_Still based on the 1290-800,799-600, and 599-320 breakpoints just wanted to highlight potential pain point widths_

| 1290 | 768 | 320 |
| --- | --- | --- |
| ![screen shot 2015-08-27 at 4 19 21 pm](https://cloud.githubusercontent.com/assets/6873734/9532094/7abfc798-4cd7-11e5-97dd-8e510d7011f4.png) | ![screen shot 2015-08-27 at 4 19 33 pm](https://cloud.githubusercontent.com/assets/6873734/9532093/7abeb128-4cd7-11e5-8db0-5b9ccd396c38.png) | ![screen shot 2015-08-27 at 4 19 47 pm](https://cloud.githubusercontent.com/assets/6873734/9532095/7ac6d880-4cd7-11e5-80e3-b8b2ab634c4e.png) |

##### Module only - spacing ideas to keep type managable

| 1290 | 768 | 600 | 320 |
| --- | --- | --- | --- |
| ![screen shot 2015-08-27 at 3 53 30 pm](https://cloud.githubusercontent.com/assets/6873734/9531842/18f24b7c-4cd6-11e5-9cf1-e20501f2c457.png) | ![screen shot 2015-08-27 at 3 53 41 pm](https://cloud.githubusercontent.com/assets/6873734/9531862/32346638-4cd6-11e5-94ed-1740485df7b0.png) | ![screen shot 2015-08-27 at 3 53 49 pm](https://cloud.githubusercontent.com/assets/6873734/9531861/32287dbe-4cd6-11e5-9080-5a01a32da34b.png) | ![screen shot 2015-08-27 at 3 55 12 pm](https://cloud.githubusercontent.com/assets/6873734/9531870/3d30b6cc-4cd6-11e5-8cd5-6cdd889ab388.png) |

#### Thoughts
- When using images in this style we will have to be careful on the available safe zone for how the image will get cropped on responsive sizes but it seems like it could be manageable. Below is an example of the safe zone for the example above:
  ![screen shot 2015-08-27 at 4 22 40 pm](https://cloud.githubusercontent.com/assets/6873734/9532166/ddf8b432-4cd7-11e5-9b53-abe499d50b8f.png)
- For the module height to stay the same, there will have to be pretty strict text limits. If module is to be flexible height images will have to have more available space for cropping (maybe there are other options?)

**Comment by ajbush** [comment]
:+1:  
I really like this new direction it's working nicely. And the safe zone would be really nice to have and make it easier to repeat images with the same ratio across different breakpoints.

**I had two questions though...**
- I wonder if/how it would change the presence of the Featured Content module if the full intro + body paragraph was include above this module. On Beta that paragraph that starts with "Above all, this..." is tied to the Introduction section. Would this be one of those things we'd recommend Content to avoid?
- Also I wonder if flipping the position of the card to the right might give a little visual break between the intro copy and the copy in the card. Just wanted to compare. It does make your eye have to jump around a lot more than with the content on the left...

| 1290 | 320 |
| --- | --- |
| ![de](https://cloud.githubusercontent.com/assets/6931351/9548437/754747cc-4d6e-11e5-8f75-6789b1cd1f42.png) | ![chin](https://cloud.githubusercontent.com/assets/6931351/9548639/a65f164a-4d6f-11e5-9ca0-8cd8f6652f7d.png) |

**Comment by schaferjh** [comment]
I'd advocate against including a body paragraph above the featured item. I'm okay with the idea that if/when we implement this module we'll have to tweak some content (like the two intro graphs on The Bureau) to create a more compact introduction. Otherwise, if we allow body paragraphs above, we risk the featured item getting pushed too far down that page and feeling less special.

I like flipping the card to the right! It provides a nice visual break for the eye.

**Comment by duelj** [comment]
+1 to flipping the card good call! I like it on the narrow screen width as well. Looking at it like that makes me think of the inset modules that we have been talking about recently on FJ. Maybe this would be a good use for something like that, I will try to mock something up to show what I mean.

**Comment by duelj** [comment]
This is what came to mind with the [inset module](https://github.cfpb.gov/flapjack/Modules-V1/issues/2#issuecomment-52961) style. Thought maybe this would make the module feel lighter and match some of the thinking AJ did for the ["breakout sidebar for featured tools"](https://github.cfpb.gov/flapjack/Modules-V1/issues/15#issuecomment-52037) but I like the sort of well version also (just food for thought)

| 1290-800 | 799\600 | 599-320 |
| --- | --- | --- |
| ![screen shot 2015-08-28 at 12 58 32 pm](https://cloud.githubusercontent.com/assets/6873734/9552426/f27c2b7e-4d85-11e5-9117-69f64896baa5.png) | ![screen shot 2015-08-28 at 12 58 42 pm](https://cloud.githubusercontent.com/assets/6873734/9552427/f6752e42-4d85-11e5-854e-0b3d28f5598e.png) | ![screen shot 2015-08-28 at 12 58 55 pm](https://cloud.githubusercontent.com/assets/6873734/9552428/fa2939ca-4d85-11e5-81f4-689c7cb7c7e5.png) |

**Comment by jenn-franklin** [comment]
Great exploration, @duelj! I've been going down a similar path of having boxed text on the left with an opaque background. 

One a minor style note, one question that popped up for me is if gray will work for the box when the module is on a page with a left sidebar. Is it too much gray? I guess in that instance we could make it white— or leave it up to designers if they want to use a different light color without getting too crazy. Here it is with the sidebar, though in a lighter shade of gray. 

![screen shot 2015-08-29 at 9 49 41 am](https://cloud.githubusercontent.com/assets/10562530/9562198/51d4aef4-4e33-11e5-9dc9-7c1ebe9f3de1.png)

Good investigation of what happens with photo cropping. Totally agree about creating a safe space guide. We also were wondering if the copy needs to go on the module area/to the side anymore. Started experimenting with it on top. Here's a mockup (without much styling):

| 1290 left nav | 1290 sidebar | 768 | 600 | 320 |
| --- | --- | --- | --- | --- |
| ![screen shot 2015-08-29 at 9 18 32 am](https://cloud.githubusercontent.com/assets/10562530/9562097/c722b9f2-4e2f-11e5-9235-0523f28a5ea9.png) | ![screen shot 2015-08-29 at 9 18 49 am](https://cloud.githubusercontent.com/assets/10562530/9562082/68bf1770-4e2f-11e5-9aed-5c06a94ccbf9.png) | ![screen shot 2015-08-29 at 9 19 02 am](https://cloud.githubusercontent.com/assets/10562530/9562083/743887e4-4e2f-11e5-8e4c-21533aba7b7d.png) | ![screen shot 2015-08-29 at 9 19 20 am](https://cloud.githubusercontent.com/assets/10562530/9562084/7a33e904-4e2f-11e5-82d5-d6511e6e3d8b.png) | ![screen shot 2015-08-29 at 9 19 31 am](https://cloud.githubusercontent.com/assets/10562530/9562087/7f67bab8-4e2f-11e5-8f4d-7f5963ca0785.png) |

If we go that route, we'll definitely need to think about the height of the image, character restrictions, etc. to ensure we don't get too uncomfortably tall. 

On another point, we've been throwing around the idea of tagging different types of content in the module. Maybe a system like, "featured video, featured event, featured blog post..." I'm not sure if we have enough different content types to sort and if this organizing would be helpful to the user. But it's an interesting idea to explore. Or the tags could be directional like "New feature, Get started..." or something along those lines to reinforce that the user should turn to the module first. May not be necessary since the module is clearly dominant from a visual standpoint. Also, we could write the title/copy of the module to be more directional if we think it'd be helpful. 

Here are basic visual explorations of the tagging and the module's styling in general.

<h4>Experiment 1: Adopting Flapjack's related links pattern</h4>

Could change the color/differentiate it while still relating to the existing pattern. 

| 1290 left nav | 1290 sidebar | 768 | 600 | 320 |
| --- | --- | --- | --- | --- |
| ![screen shot 2015-08-29 at 9 28 20 am](https://cloud.githubusercontent.com/assets/10562530/9562186/91f482bc-4e32-11e5-8dbd-ff62a59bcd9c.png) | ![screen shot 2015-08-29 at 9 28 31 am](https://cloud.githubusercontent.com/assets/10562530/9562188/9c7f109e-4e32-11e5-84f6-bb6d978de8f1.png) | ![screen shot 2015-08-29 at 9 28 41 am](https://cloud.githubusercontent.com/assets/10562530/9562190/a268b672-4e32-11e5-8b3a-6f7033dbc2ce.png) | ![screen shot 2015-08-29 at 9 28 58 am](https://cloud.githubusercontent.com/assets/10562530/9562191/a87db436-4e32-11e5-96b8-6249ff0323b0.png) | ![screen shot 2015-08-29 at 9 28 49 am](https://cloud.githubusercontent.com/assets/10562530/9562192/ae5b890a-4e32-11e5-9fe8-8070439aecad.png) |

<h4>Experiment 2: Using a tag</h4>

| 1290 left nav | 1290 sidebar | 768 | 600 | 320 |
| --- | --- | --- | --- | --- |
| ![screen shot 2015-08-29 at 9 31 16 am](https://cloud.githubusercontent.com/assets/10562530/9562163/cfb202ba-4e31-11e5-90b8-90548fde1d5e.png) | ![screen shot 2015-08-29 at 9 31 26 am](https://cloud.githubusercontent.com/assets/10562530/9562166/d83d0088-4e31-11e5-81f5-b2cf1d3c22ff.png) | ![screen shot 2015-08-29 at 9 31 34 am](https://cloud.githubusercontent.com/assets/10562530/9562167/de79569a-4e31-11e5-9b41-4b4196875b3e.png) | ![screen shot 2015-08-29 at 9 38 19 am](https://cloud.githubusercontent.com/assets/10562530/9562168/e61fe40e-4e31-11e5-9fdc-ab62b2849e1c.png) | ![screen shot 2015-08-29 at 9 31 45 am](https://cloud.githubusercontent.com/assets/10562530/9562169/eb2d9ed2-4e31-11e5-9be0-d44487664b59.png) |

<h4>Experiment 3: Using a minicon</h4>

| 1290 left nav | 1290 sidebar | 768 | 600 | 320 |
| --- | --- | --- | --- | --- |
| ![screen shot 2015-08-29 at 9 40 49 am](https://cloud.githubusercontent.com/assets/10562530/9562172/2fe5fcb8-4e32-11e5-84e1-cf58c5c2a36c.png) | ![screen shot 2015-08-29 at 9 40 57 am](https://cloud.githubusercontent.com/assets/10562530/9562173/36c8d604-4e32-11e5-8bec-e7dae64ebf18.png) | ![screen shot 2015-08-29 at 9 41 08 am](https://cloud.githubusercontent.com/assets/10562530/9562174/3f7aeecc-4e32-11e5-861c-817c53cbab84.png) | ![screen shot 2015-08-29 at 9 41 19 am](https://cloud.githubusercontent.com/assets/10562530/9562178/4f30169e-4e32-11e5-9c42-dbb80ee9fc20.png) | ![screen shot 2015-08-29 at 9 41 29 am](https://cloud.githubusercontent.com/assets/10562530/9562179/5517726e-4e32-11e5-9f94-cab47ff51115.png) |

**Comment by jenn-franklin** [comment]
Hi! Was just looking at this issue again and realized for whatever reason AJ and Jess's comments and Justin's new exploration didn't load for me when I posted. Cool that you're arriving at a similar place re: the featured video tag.

**Comment by mebates** [comment]
I like it when the module reaches over and touches the left sidebar. I think it could do the same with the right gray panel. The last gray box posted by @ajbush and @duelj's exploration with the green bar above 'featured video' are my preferred designs.

**Comment by kurzn** [comment]
I really dig where this is heading. Nice work everyone! One comment - on the version that @duelj  did with the "inset module style" the text feels a bit disconnected from the video, almost like a standalone sidebar. I think the versions where the content is "touching" the video (through boundary lines or background colors, etc) feel more cohesive and connected. 

I'm very interested in the top content idea as it doesn't relegate content to a narrow box, which can be difficult for length and text wrapping, while also creating a fresh way to display the content - doesn't resemble anything else (like a sidebar) and helps set it apart.

**Comment by nataliafitzgerald** [comment]
The explorations are looking good! @huetingj and I plan to meet tomorrow to walk through the full issue.

**Comment by jenn-franklin** [comment]
:+1: and i'll be posting a refined design/recommendation reflecting these explorations this afternoon.

**Comment by jenn-franklin** [comment]
Hello! I've dug deeper, and here's what I've found. 

<h4>First, I want to articulate that the featured content module (FCM) is a "mini story" and never simply a dominant visual.</h4>

By this I mean that it contains perhaps a video for a user to interact with, an illustration with a paragraph and link pointing to another page, an event callout with details, etc. It never has a visual unaccompanied by text; that situation would be a simple dominant image, and I address that further in this post. 

<h4>Second, the FCM has a little sister called a "featured tool."</h4>

In looking closely at the featured tool "module" Flapjack (ahh remind me of your team's name sorry) designed, it becomes clear that the two types are extremely similar in terms of the content they handle. Here is the featured tool design:

![featured_tool_desk top](https://cloud.githubusercontent.com/assets/10562530/9744937/c885beb0-563c-11e5-8e53-91740f0b2bb9.png)

Here it is on tablet and mobile:

![screen shot 2015-09-08 at 3 19 15 pm](https://cloud.githubusercontent.com/assets/10562530/9744973/0067f7bc-563d-11e5-99bb-025bb644b466.png)

<h4>This leads me to believe the FCM design should relate as closely as possible to the featured tool design. </h4>

Here is a mockup of the FCM design I am proposing using the Rulemaking page so you can easily visualize the similarities and and differences in style. 
![fcm_desktop](https://cloud.githubusercontent.com/assets/10562530/9744997/2b54de40-563d-11e5-8d4a-19ade6a94216.png)

<h4>Thoughts:</h4>
- This is essentially the same as the featured tool treatment except it's given greater dominance.
- I have gotten over my "too much grey on a page with a sidebar" hesitation and have put this content in a grey box to make it clear to the user that the text is related to the visual. (I think this is more so important on mobile than on desktop.)
- I have picked up styling for the tag and header from the featured tool design--- however, notice that I've flipped the styles. We'll need to reconcile that if we continue down this direction. 
- The text is on the left to follow the natural line of reading. The reason I did this: I see this text as its own little story. When putting the text on the right, it appears secondary to the image and more caption-like in my mind. This is ok in some situations but not all, such as on the Events page where we want the title/date/location/etc. to be the primary focus. Let's spend some more time discussing this. I think there are good reasons for both the left and right. And are there other specific situations like the Events page that could influence our thinking? 

<h4>Here is an exploration of visual handling with other content on desktop.</h4>

![fcm_more_desktop](https://cloud.githubusercontent.com/assets/10562530/9745118/f744954a-563d-11e5-9077-efd1c7af07f2.png)

<h4>Here is an exploration of how it translates to tablet + mobile using the Rulemaking page again.</h4>

![fcm_tablet_mobile](https://cloud.githubusercontent.com/assets/10562530/9745136/0b9a3626-563e-11e5-96b1-ba0a8d8f35c1.png)

<h4>The FCM can't be our everything. And we shouldn't make it try.</h4>

In looking at other potential use cases, I examined the "Working at the CFPB" page. 
![dominant_image_1](https://cloud.githubusercontent.com/assets/10562530/9745160/2cc3973e-563e-11e5-8c23-d0b706e25d19.png)

This is a situation where the dominant image is not featured content— it's simply setting a tone and visually defining the page. It does not fit into the FCM approach. 

![dominant_image_2](https://cloud.githubusercontent.com/assets/10562530/9745187/4993d1f8-563e-11e5-9c00-bf04ff14b184.png)

I think this raises a bigger page layout question of how dominant images are handled and that this is not directly tied to our hero exploration. A "larger" image doesn't need to be at the top of a page; it could be embedded in content, appear multiple times on a page, etc. I started doing basic mockups, so I'm happy to share those at any point if helpful. Here are a few wireframes. 

![dominant_image_3](https://cloud.githubusercontent.com/assets/10562530/9745233/809e5b28-563e-11e5-998a-8f94df91703d.png)

<h4>Let it be known.</h4> I'd like to get thoughts and look further at character restrictions— in the intro paragraph, in the FCM text area, etc. For example, with the FCM mockup on the Events page, I cut content from what is on the current beta page. Part of this was an attempt to keep the FCM at 300px height to match and not surpass the height of the hero currently being designed in #348

**Comment by duelj** [comment]
### Big & little sister solution

I like your thinking around trying to bring the FCM inline more with the breakout sidebar organism (what you called little sister) and had an idea that might pair well with some of the issues you noted.  When you said: 

> The FCM can't be our everything. And we shouldn't make it try.

I really starting thinking about the needs of the different page types and the purposes they are intended to serve. I think there is an opportunity to feature content differently for different page types so that the featured content works better in the page's hierarchy, overall page type composition, and purpose. This is what I'm thinking ([quotes are pulled from here](https://github.cfpb.gov/flapjack/Modules-V1/wiki/Page-types-for-v.1)):
- Large FCM could be used on Browse template pages. These page types have left side navigation and intended to: 
  
  > Skimming for necessary information. Provide specific information in an easily browseable format, with sibling and sub pages within the given site subsection easily accessible in left nav so user can easily move around within the topic.
- Small FCM (AKA Little sister, featured tool, or breakout sidebar) could be used on Sub-Landing pages. These pages can have sidebars which use more horizontal space to highlight dynamic and related content. The lower level of the featured tool style works well since the idea of these pages is for users to explore interior sections:
  
  > Show the big picture. For major sections within each navigation vertical, provide an additional level of user friendly explanation about the content within this specific section. User is still primarily in "explore" mindset -- main content of this page should be directing users to the specific content that will help them.
- This system would function on the idea that Sub-Landing and Browse pages serve different functions and therefore may have different needs when it comes to featuring a specific piece of content. The same types of content could be featured in either format (video, article, event, tool).
- Because of the nature of the 5 main Level 1 (landing) pages featuring a specific piece of content is not necessary and only the hero would be employed on these pages (just a thought - could use UX input)

#### Sub Landing Template (w/o hero) - Small FCM

| 1290 | 800 | 768 | 320 |
| --- | --- | --- | --- |
| ![sm_fcm_1290](https://cloud.githubusercontent.com/assets/6873734/9799332/79eb5a78-57d4-11e5-8e84-a84c0f3e01c7.png) | ![sm_fcm_800](https://cloud.githubusercontent.com/assets/6873734/9799334/81803006-57d4-11e5-9eea-b08b8c00330e.png) | ![sm_fcm_768](https://cloud.githubusercontent.com/assets/6873734/9799336/86fe93f6-57d4-11e5-9186-ce6be92f1f02.png) | ![sm_fcm_320](https://cloud.githubusercontent.com/assets/6873734/9799338/8c1c0efe-57d4-11e5-88dc-7ecd9281da40.png) |

#### Sub Landing Template (w/ hero) - Small FCM

| 1290 | 800 | 768 | 320 |
| --- | --- | --- | --- |
| ![sm_fcm_hero_1290](https://cloud.githubusercontent.com/assets/6873734/9799357/aac336a2-57d4-11e5-91e4-8ac242b09fd4.png) | ![sm_fcm_hero_800](https://cloud.githubusercontent.com/assets/6873734/9799359/aed1cbd2-57d4-11e5-9d67-cd3e357ade13.png) | ![sm_fcm_hero_768](https://cloud.githubusercontent.com/assets/6873734/9799363/b48f1a2a-57d4-11e5-9e99-7652495ee3fa.png) | ![sm_fcm_hero_320](https://cloud.githubusercontent.com/assets/6873734/9799368/b972a7aa-57d4-11e5-885b-0a387436bf00.png) |

#### Browse Templates - Large FCM

| 1290 | 800 | 768 | 320 |
| --- | --- | --- | --- |
| ![lg_fcm_1290](https://cloud.githubusercontent.com/assets/6873734/9799382/cf3aa8f8-57d4-11e5-9fa8-4908d0791911.png) | ![lg_fcm_800](https://cloud.githubusercontent.com/assets/6873734/9799387/d66b779c-57d4-11e5-8b72-791de93aa1db.png) | ![lg_fcm_768](https://cloud.githubusercontent.com/assets/6873734/9799396/db851742-57d4-11e5-9934-31dfb8f302b8.png) | ![lg_fcm_320](https://cloud.githubusercontent.com/assets/6873734/9799398/e187ea66-57d4-11e5-8a47-d81ad3c244e8.png) |

**I have some more notes on the V1 intended us of "little sister," dominant visuals, and why I think multiple FCM styles is a good way forward, but the post was already overwhelming. Would be happy to chat more to see what you think.**

**Comment by kurzn** [comment]
Thanks @duelj for the feedback! We are closing in on a strong recommendation that we feel really good about and will discuss more at today's design review meeting. We think keeping the FCM in the well of the page (as opposed to the sidebar), in addition to standardizing the design regardless of the page type it appears on, helps keep things easy to implement and consistent for the user, while still fulfilling the goals of the FCM. 

If there are additional sidebar modules that you feel are necessary to develop, we'd love to open up a new issue to discuss those as needed.

**Comment by kurzn** [comment]
We also think that the rules behind using dominant images on a page (not within a FCM) should be explored in a separate issue as well.

**Comment by duelj** [comment]
Look forward to hearing about your idea in the meeting today, look forward to the discussion to come. I am all for ease of implementation as long as it is still serving the needs of the user and the intended purpose of the page as specified by the revised IA.

**Comment by schaferjh** [comment]
Definitely looking forward to seeing the recommendation the afternoon, @kurzn. Just want to mention, all the FCM mock ups I've seen thus far are on pages with a sidebar, but sub-landing pages are not required to have a full top-to-bottom sidebar. 

The V1 team will be developing a "breakout sidebar organism" within our project work -- once we've worked on it in our context, we can figure out if it should be integrated into the DM!

**Comment by kurzn** [comment]
@schaferjh Can you give us an example of a sub-landing page that would have a FCM on it? So we can consider it in our recommendations. Thanks!

**Comment by schaferjh** [comment]
@kurzn Sadly we don't have one built or mocked up yet. :cry: We are working through our templates from landing page down the hierarchy. Looking ahead in our project scope, I could imagine the Research Reports page, destined to be a sub-landing page under Data & Research having an FCM, but we haven't done more than scratch the surface of the content for that page. 

**Thus is the ongoing timing frustration we all share!!!! It's gonna get better eventually!**

It may be simplest, for our larger immediate purposes, to decide that an FCM should only appear on pages with a sidebar (either left nav or right content). Then, within the V1 project work, our team will determine if we need an option for sub-landing pages without a sidebar and if necessary we can noodle on that and see if it needs to be raised to a DM discussion.

**Comment by kurzn** [comment]
@schaferjh I think that sounds like a brilliant plan! :+1:  Part of our biggest impediment has been trying to design for the potential "what if." I think we're at a point to cover 90% of use cases, and as we encounter those edge cases in the future, we can either tweak the recommendation or find an alternate solution to the problem at hand.

**Comment by jenn-franklin** [comment]
Hi @nataliafitzgerald and @benguhin. Can you please review for approval? Thanks!

<h2>Style at desktop size</h2>

<strong>FCM on page with right sidebar</strong>
![desktop_1](https://cloud.githubusercontent.com/assets/10562530/10063755/315e718a-623f-11e5-82c6-d399c59a434e.png)

<strong>FCM on page with left nav</strong>
![desktop_2](https://cloud.githubusercontent.com/assets/10562530/10063758/36de18ae-623f-11e5-8e1b-bfd6c37f5fe6.png)

<h4>Module/background</h4>
- Module is 270px total in height with 30px top and bottom margins. It appears 60px underneath the header/intro paragraph of the page
- Background color of module is Gray 5 with a 1px Gray 50 stroke
- Module bleeds to edge of page, right sidebar and left nav 
  <h4>Text</h4>
- Text spans 3 columns and is left- and top-aligned. When on a page with a right-hand sidebar, the text area has 60px of left margin and 30px of right margin. When on a page with left-hand navigation, the text area has 30px of left and right margin.
- Tag is an 18pt black minicon and H4 text, appears 30px from top
- Headline is H2, appears 30px below tag and is 1 to 2 lines
- Body copy is 16pt, appears 30px underneath headline, is 2 to 4 lines
- A CTA may be used and appears 30px underneath body copy. If a link, standard link styles apply. If a button, standard primary button styles apply. 
  <h4>Visual</h4>
- Visual spans 5 columns and bleeds into right sidebar.  

<h2>Style at tablet size</h2>

<strong>Example 1</strong>
![tablet_1](https://cloud.githubusercontent.com/assets/10562530/10063509/8f0e2abc-623c-11e5-94e6-61bfd7391335.png)
<strong>Example 2</strong>
![tablet_2](https://cloud.githubusercontent.com/assets/10562530/10063511/91882086-623c-11e5-8b8c-35eb070388eb.png)

<h4>Changes in style</h4>
- Text spans 5 columns
- Visual spans 7 columns
- Visual's height is fixed, and cropping will occur on both the left and right sides. 

<h2>Style at mobile size</h2>

<strong>Example 1</strong>
![fcm_mobile_1](https://cloud.githubusercontent.com/assets/10562530/10063574/808441d8-623d-11e5-96ad-40712a294819.png)
<strong>Example 2</strong>
![fcm_mobile_2](https://cloud.githubusercontent.com/assets/10562530/10063577/88b233f6-623d-11e5-8e94-0eced92dab46.png)

<h4>Changes in style</h4>
- Module appears 30px underneath the header/intro paragraph of the page
- Header becomes H2
- Body text becomes 16pt
- Tag becomes H5, minicon drops off
- Visual drops below text
- 30px space between text and top of visual

**Comment by jenn-franklin** [comment]
Hi, @nataliafitzgerald and @benguhin! Any chance you might be able to check this out today? Thanks!

**Comment by stephanieosan** [comment]
You can see a design manual page version of this here: https://stephanieosan.github.io/design-manual/ui-toolkit/featured-content-module.html

**Comment by jenn-franklin** [comment]
Hey, @duelj and @ajbush! I'm assigning minicons to the five tag categories. Based on what I've seen on beta and in the cf.gov AI file, I've pulled this together: 
![screen shot 2015-09-25 at 1 38 05 pm](https://cloud.githubusercontent.com/assets/10562530/10107674/ad1f4ffa-638a-11e5-8704-a08364121ccc.png)
Any you think I should change? Thanks!

**Comment by duelj** [comment]
The category labels look good to me :+1:

**Comment by jenn-franklin** [comment]
Thanks, @duelj!

**Comment by schaferjh** [comment]
@huetingj do you think "news" could be expanded/generalized to include report or guide? I don't really want to expand your universe of minicons, but I can easily see using the FCM to highlight a research report, an educational guide, a notice open for comment, or a new rule implementation guide. I don't think we want to create category tags for all of these, so maybe some kind of generalized "action" or "announcement" category could be used in place of "news" so it can be applied more broadly? 

_Note: I'm not trying to open up a whole new discussion! -- We can't anticipate everything and the categories you've got are a good starting point. Whatever team is implementing a new content type in the FCM can be responsible for innovating a category label if the 5 you have here don't work for their use case. Just seems like it might be helpful to have a more general option as one of these 5._

**Comment by ajbush** [comment]
You could also reuse one minicon that we deem is used for featured content.

Maybe the "Favorite" minicon could work if you went this route?

![ss](https://cloud.githubusercontent.com/assets/6931351/10108125/2dd26950-638d-11e5-8e1d-8f0aac9373d6.png)

<img width="194" alt="screen shot 2015-09-29 at 11 19 04 am" src="https://cloud.githubusercontent.com/assets/6931351/10169087/7184fe66-669d-11e5-8124-a59566730eb2.png">

**Comment by jenn-franklin** [comment]
Ah! Makes sense to me to have a general-ish tag. Maybe we just call it "Featured content or "Featured item" (or perhaps even just "Featured") for now? And then we can assess what label makes most sense (i.e. report, announcement, etc.) when a specific situation pops up. Can definitely see modifying/adding as we gain more perspective on our types. @kurzn, thoughts?

I like the black star!

**Comment by nataliafitzgerald** [comment]
@huetingj - This is looking good! I also looked at the layout of the DM page and that looks close to done too. Can we meet sometime today do a detailed final review? 30 minutes should be enough.

One note, for the space under the H2, 30px is too much space. It means that the H2 ends up sandwiched right in the middle between the tag and the body copy. Can we address this?

**Comment by kurzn** [comment]
I do think the 5 specific minicons/categories are helpful both to the user in setting quick context for what the content is and for us in managing the implementation of this (basically keeping this somewhat locked down so that stakeholders can't request everything become a FCM). For users, some FCM will be more obvious than others - video for instance is pretty recognizable on sight. But the different between a blog and news will not be immediately obvious, which is where I see the 5 specific minicons being very helpful. 

That being said, I also agree we need to be flexible for other defined content types, ie. reports, etc. What about adding a 6th generic category of "Featured" using the star for more one-off instances? If then we discover that an additional content type is being featured frequently, we can devise a specific minicon/category for it down the line. 

Thoughts?

**Comment by benguhin** [comment]
> If then we discover that an additional content type is being featured frequently, we can devise a specific minicon/category for it down the line.

:+1:

**Comment by jenn-franklin** [comment]
We have submitted pull requests to the design manual and capital framework with these designs. 

<h3>Deskop</h3>

Page with sidebar
![fcm_desktop_1](https://cloud.githubusercontent.com/assets/10562530/10177614/035f6094-66c9-11e5-8d66-b111330810f6.png)
Page with left nav
![fcm_desktop_2](https://cloud.githubusercontent.com/assets/10562530/10177615/07f78faa-66c9-11e5-9cbc-11f955a57bd7.png)

<h3>Tablet</h3>

![fcm_tablet_1](https://cloud.githubusercontent.com/assets/10562530/10177631/16859f6c-66c9-11e5-8d48-67c303e9f5cb.png)
![fcm_tablet_2](https://cloud.githubusercontent.com/assets/10562530/10177636/1c08e6f6-66c9-11e5-86aa-234a95f1f0de.png)

<h3>Mobile</h3>

![fcm_mobile_1](https://cloud.githubusercontent.com/assets/10562530/10177652/2932d72e-66c9-11e5-9990-04be42f1a6a6.png)
![fcm_mobile_2](https://cloud.githubusercontent.com/assets/10562530/10177655/309755f8-66c9-11e5-89ec-8aae645ed0c0.png)

<h3>Changes and considerations since my last post</h3>
- Links are underlined. They continue not to include an arrow. 
- The tag will remain at the H4 level with a minicon at all breakpoints. @duelj @ajbush From what I can see, you are currently keeping tags at the same level, and I'd like to fall in line with this approach. Let me know if this is incorrect/any thoughts. Tag staying at an H4 level:
  ![fcm_mobile_1](https://cloud.githubusercontent.com/assets/10562530/10178274/c3276c20-66cc-11e5-9c21-c7b85a153b26.png)
- The featured video minicon is now the black circle with white play button. 
  <br/>
  ![screen shot 2015-09-29 at 4 51 59 pm](https://cloud.githubusercontent.com/assets/10562530/10177881/8c5c7912-66ca-11e5-88c5-9b748291f303.png)
  <br/>
- We are using the following tags to categorize content:
  <br/>
  ![tags_1](https://cloud.githubusercontent.com/assets/10562530/10177913/bd391022-66ca-11e5-8660-bf5bff041013.png)
  <br/>
- In the case that the content does not fit in one of these categories, the designer can use the following tag:
  <br/>
  ![tags_2](https://cloud.githubusercontent.com/assets/10562530/10177928/d1425038-66ca-11e5-96ef-5097388f19ba.png)
  <br/>
- After a lot of thought, we have decided to follow the spacing guidelines V1 has proposed here: https://github.com/cfpb/design-manual/issues/269 I've mocked up different spacing possibilities and will contribute any thoughts to that issue as standards are ironed out. 
- The FCM is extending to the edge of the page and not bleeding beyond. This falls in line with what is on beta:
  ![screen shot 2015-09-29 at 5 06 00 pm](https://cloud.githubusercontent.com/assets/10562530/10178213/6d785d8e-66cc-11e5-9065-4e53c1f88120.png)

**Comment by jenn-franklin** [comment]
Also, the background and link colors reflect the new values in https://github.com/cfpb/design-manual/issues/327

**Comment by stephanieosan** [comment]
Pull request here: https://github.com/cfpb/design-manual/pull/362

**Comment by kurzn** [comment]
Can FCM ever appear on a page with a hero? I don't believe we ever discussed this scenario, but I think it's worth including in the language of how these are used in the DM, either way we decide. We do specify you can use these on "any page type" which would include landing pages, which typically have heroes.

Thoughts?

**Comment by schaferjh** [comment]
@kurzn the only place where this is a possibility is a sub-landing page. For V1 templates we created three options for the top of a sub-landing page: 
- Hero 
- Text intro + breakout sidebar 
- Text intro w/ option for FCM

https://[GHE]/flapjack/Modules-V1/wiki/Sub-landing-page-template#ia-guidelines

**Comment by caheberer** [comment]
@kurzn do you have recommended text for the edit?

**Comment by Scotchester** [comment]
The FCM design has recently been revised and #627 is underway to document the updates. This very outdated issue can be closed.
