### ISSUE TITLE
[Typography] Bulleted list

### ISSUE THREAD

**Issue by Dnpizarro** [cfpb/design-manual#382]
Jeff and I are working on the Publications Overhaul and came across an issue with the bullets and wanted to open it for discussion. In looking at it carefully the spacing for the bullets feels too dense when there is long copy. In the example below, it creates an awkward visual imbalance where the left column seems much denser than the right despite the leading being the same for the bulleted copy on both columns. I have seen other examples of this in reports and other handouts. Is the leading differentiation necessary? If so, what was reasoning for not making the bulleted list 11/16?

@nataliafitzgerald @klocraft 

<img width="739" alt="screen shot 2015-12-03 at 12 04 28 pm" src="https://cloud.githubusercontent.com/assets/6852363/11568149/933cd47c-99b8-11e5-8d8e-59c7f6b97156.png">

**Comment by nataliafitzgerald** [comment]
@Dnpizarro 
In the example you have posted, it would make sense to use consistent leading for all bullet lists on the page. 11/16 would probably give the longer list items some breathing room. I would also suggest removing the bullets from the content on the left side and just making it paragraphs with headings. These headings could be numbered 1-2-3 since the heading is "Three options to consider." Although, I don't know that the numbering is relevant to the content (since this isn't an ordered list really). In which case you could go with "Options to consider" and then just 3 subsections with headings. 

I see this issue is over a year old. Is there a need to keep it open?

**Comment by caheberer** [comment]
@Dnpizarro with the new handout template, do you still feel this is an issue?

**Comment by caheberer** [comment]
Determined that this is more of a content issue versus an issue with our bulleted lists.
