### ISSUE TITLE
Featured content module centered map image crops Google copyright

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/design-manual#386]
The centering of the featured content module image crops out the lower-right Google copyright notice. This is likely legally a problem.

![image](https://cloud.githubusercontent.com/assets/704760/12150308/1b858ada-b477-11e5-81df-c824929a8b94.png)

**Comment by jimmynotjim** [comment]
cc @huetingj and @stephanieosan.

I was trying to think of possible solutions, but other than pushing the maps only to the left, I'm coming up empty. We can't reduce the image to the width of the provided area because it'll be shorter than the content. Does anyone have other ideas that could work with the existing layouts?

**Comment by jenn-franklin** [comment]
Thanks @anselmbradford and @jimmynotjim— I'm looking into it and will report back!

**Comment by jenn-franklin** [comment]
Ok, here are my thoughts:

We're placing a Google map in the FCM as a static image screenshot. The placement of Google's attribution is dependent on how the designer has the browser window sized when snapping the shot. Here I've shot it with the attribution below "Washington."

![screen shot 2016-01-12 at 10 25 26 pm](https://cloud.githubusercontent.com/assets/10562530/12284159/7ddbf76a-b97b-11e5-8f0d-fc6b3bbd25ea.png)

This is somewhat unattractive because you have elements such as the zoom buttons and "Terms" which are not needed for our purposes. (I'm doubting that you can hide/rearrange these elements, but I also didn't try.)

Because of this, I think we should create our own attribution text. According to <a href="https://www.google.com/permissions/geoguidelines/attr-guide.html">Google's attribution guidelines</a>, we can customize the styling and placement of the attribution. From that page:

> What does the attribution text need to say?
> 
> If you are not using the text provided directly on Google Maps and Google Earth imagery, the text of    your attribution must say the name “Google” and the relevant data provider(s), such as “Map data: Google, DigitalGlobe”. You may customize the style and placement of the attribution text, just so long as the text is legible to the average viewer or reader. Note that Google logos cannot be used in-line (e.g. "These maps from [Google logo].")"

For the design of this, we should follow whatever style is our standard for photo credits. @nataliafitzgerald Do you know if we've established a font size/color/weight for photo credits? I'm not seeing any guidelines on our <a href="http://cfpb.github.io/design-manual/identity/photography.html">Photography page</a>, probably because the majority if not all of the photos we use are shot by our own photographers. 

Having said all this... Do you guys think it's best to display a map as a static image? Or should we instead embed a "live" Google map? Is this possible within FCM's structure and do you see any drawbacks? Maybe it's not an MVP but something to consider in the future.

**Comment by jimmynotjim** [comment]
I definitely don't recommend using a dynamic map, mostly because it will be cropped and narrow as certain sizes and because of the additional data/page requests of embedded maps. Adding our own attribution to a static image sounds like a good middle ground.

**Comment by jenn-franklin** [comment]
Ok, sounds good! :+1:

**Comment by stephanieosan** [comment]
:+1:

**Comment by amycesal** [comment]
There's other cropping issues with this, especially when you're trying to have a worksheet as the featured tool and show something with text. Take a look at the payday playbook page for example:

![screen shot 2016-05-16 at 1 45 30 pm](https://cloud.githubusercontent.com/assets/1656046/15326741/27d13704-1c1d-11e6-94a9-ba85751cd3cf.png)

There's another page is also facing the same issue right now. @Scotchester pointed it out.

A quick solution would for it to just crop from one side when reduced, not both, but I don't know if that's the correct long term solution.

**Comment by jimmynotjim** [comment]
We're going to be converting the Hero and FCM during the Atomic Design Workshop. If you have any interest in the future of the FCM, I highly recommend you attend both days so that your input can help improve it.

**Comment by caheberer** [comment]
@jimmynotjim has this been resolved?

**Comment by jimmynotjim** [comment]
Yes, by default it will be aligned to the left edge with options for center or right alignment.

https://github.com/cfpb/capital-framework/blob/prerelease-ver-4/src/cf-layout/src/organisms/featured-content-module.less#L74-L105

**Comment by caheberer** [comment]
Great!
