### ISSUE TITLE
[DATA VIZ] Bar Chart Bonanza! 

### ISSUE THREAD

**Issue by amycesal** [cfpb/design-manual#401]
@designlanguage and I are taking a set of data and pushing the boundaries of bar chats to see what we can do and where we want to go with style. 

Raw data:
##### comparison of new york state and metro area complaints compared to the us

| Product | NY metro area | NY state | US |
| --- | :-: | --: | --: |
| Mortgage | 27% | 25% | 27% |
| Debt collection | 20% | 21% | 26% |
| Credit reporting | 17% | 17% | 16% |
| Credit card | 14% | 15% | 11% |
| Bank acct/services | 13% | 13% | 10% |
| Other | 10% | 10% | 11% |
##### breakdown of complaints in other financial services category

| other financial service complaint sub Issue | % Total |
| --- | :-: |
| Fraud or Scam | 46% |
| Customer service or customer relations | 21% |
| Excessive Fees | 7% |
| Unexpected or other Fees | 7% |
| Advertising and marketing | 6% |
| Other | 5% |
| Disclosures | 5% |
| Lost or stolen check | 2% |
| Lost or stolen money order | 1% |
| Incorrect exchange rate | 1% |

**Comment by amycesal** [comment]
Data set 1 in 7 different ways. Not all of them are good, or in a direction that we would want to go in, but this is a starting point for discussion. 

![bar-chart-bonanza_cesal_01-02](https://cloud.githubusercontent.com/assets/1656046/13591139/d2b64aca-e4b3-11e5-9693-216f62ac3273.png)
![bar-chart-bonanza_cesal_01-03](https://cloud.githubusercontent.com/assets/1656046/13591141/d2bf6dc6-e4b3-11e5-9946-98d3d682e686.png)
![bar-chart-bonanza_cesal_01-04](https://cloud.githubusercontent.com/assets/1656046/13591140/d2bf0a98-e4b3-11e5-9088-4446dfd9fbcc.png)
![bar-chart-bonanza_cesal_01-05](https://cloud.githubusercontent.com/assets/1656046/13591143/d2c94710-e4b3-11e5-8d11-13da6bc9e02a.png)
![bar-chart-bonanza_cesal_01-06](https://cloud.githubusercontent.com/assets/1656046/13591144/d2ca60dc-e4b3-11e5-84f7-76fc38fde612.png)
![bar-chart-bonanza_cesal_01-07](https://cloud.githubusercontent.com/assets/1656046/13591142/d2c92302-e4b3-11e5-8f76-d5929dc253cf.png)
![bar-chart-bonanza_cesal_01-08](https://cloud.githubusercontent.com/assets/1656046/13591145/d2d29b9e-e4b3-11e5-94d9-9c1564fe853a.png)

**Comment by amycesal** [comment]
the second data set. 

![bar-chart-bonanza_cesal_01-12](https://cloud.githubusercontent.com/assets/1656046/13592635/1bec4b0a-e4c2-11e5-8359-f9a7632de434.png)

![bar-chart-bonanza_cesal_01-11](https://cloud.githubusercontent.com/assets/1656046/13592634/1bea2de8-e4c2-11e5-85f2-c4e5a2115f3d.png)

![bar-chart-bonanza_cesal_01-10](https://cloud.githubusercontent.com/assets/1656046/13592632/1bdc2176-e4c2-11e5-9f28-122bdb95fb85.png)

![bar-chart-bonanza_cesal_01-09](https://cloud.githubusercontent.com/assets/1656046/13592633/1bde0072-e4c2-11e5-9983-ad0d77d0b0a9.png)

**Comment by piccocesar** [comment]
Great examples Amy! All of the bars do a mostly great job telling the story. The one I keep coming back to is figure 2b. I cannot tell if I love or hate figure 2b and I think this confusion is a good thing.  At first I was not crazy about the neural trick your mind plays where the bar gets lost behind the text on the shorter bars.  It is as if you can only see either the text or the bar.  At the same time I see it as amazingly efficient.  Adding the value to the label is genius.  I wonder if it would work best with an audience that is used to a more text based delivery of data.  Where they can almost turn off the visual by just focusing on the label. I cannot wait to try this with some of my clients like those in the legal field.

I try to stay away from charts like 2d as much as possible if I cannot add labels to within each slice of the stacked bar.  It always seems like too much work for the reader when a legend is involved.

**Comment by JenniferHoran** [comment]
I kind of love 2B, I've never seen that done before.

**Comment by amycesal** [comment]
@JenniferHoran is 2B going to be accessibility terrible though?

**Comment by JenniferHoran** [comment]
I think that actually if the contrast colours are chosen correctly, since the percentage is right there in text and the items are arranged in sequence, it would not be terrible for 508. You wouldn't even need alt text if done in HTML and not as an image.

**Comment by amycesal** [comment]
@piccocesar I agree about 2D. Do you have alternative chart types that you use that we're missing? 

I also realized I'm missing any sort of axis labels and time period/date. I think date is an important point to advocate for since graphs often get re-used, and things live on the internet seemingly forever.

**Comment by amycesal** [comment]
Trying the other data set in the style-ish of 2B. And adding a date line at the bottom. 

![bar-chart-bonanza_cesal_01-14](https://cloud.githubusercontent.com/assets/1656046/13608532/3625687e-e523-11e5-87c6-2048865ed962.png)

**Comment by JenniferHoran** [comment]
I like it.

**Comment by piccocesar** [comment]
@amycesal I am a big fan of your updated chart (8A)!

You had asked about other charts that may not be listed.  These are variants of the bar chart with some added complexity. I immediately thought of the bullet chart and the likert.  These may need some work but as a quick sample:
The bullet chart
![image](https://cloud.githubusercontent.com/assets/17576915/13652043/173dba42-e618-11e5-84da-7b9a52638fdc.png)

The likert chart (Google image search)
![likert](https://cloud.githubusercontent.com/assets/17576915/13652175/b9cbea5e-e618-11e5-9700-6ca2a5778482.png)

**Comment by designlanguage** [comment]
Here are some explorations of the first data set with a few other variables to discuss.

#### A1

This takes that same complaint data, but shows each as part of the whole (these percentages add up to 101%, but this is more about aesthetics, so we won't worry about numbers too much). Putting the amount inside the bar works here because there are no small percentages. Color options would be limited due to contrast requirements.
![screen shot 2016-03-10 at 11 35 18 am](https://cloud.githubusercontent.com/assets/10562544/13676570/6dc7a822-e6b4-11e5-9bc5-d2a9468b49d6.png)

#### A2

Here's the same chart without values for each complaint type, but adding axis labels.
![screen shot 2016-03-10 at 11 35 28 am](https://cloud.githubusercontent.com/assets/10562544/13676571/6dc84c00-e6b4-11e5-87d5-9e7d9cdbae8f.png)

#### A3

Here's the data grouped by region rather than complaint type. The regions are listed above each grouping, which doesn't allow grid lines to pass through the bars. Instead, the exact amounts are listed to the right.
![screen shot 2016-03-10 at 11 35 43 am](https://cloud.githubusercontent.com/assets/10562544/13676572/6dcbcb00-e6b4-11e5-89cc-f92058e92bd8.png)

#### A4

Grouping these by complaint category, as @amycesal did. Using color here for emphasis of difference. New York state and the Metro area have similar values and overlap to some extent, so picking similar colors for each reflects that. The US as a whole is further separated by color to highlight the difference.
![screen shot 2016-03-10 at 11 35 56 am](https://cloud.githubusercontent.com/assets/10562544/13676573/6dcc2898-e6b4-11e5-9b02-e0158b32a690.png)

#### A5

These complaints are grouped by state, all labeled instead of using a key. There are no values listed, but white axis lines pass through the bars to help indicate their value. Because the lines are only visible on the bars, we can include region labels above each group of bars.
![screen shot 2016-03-10 at 11 36 06 am](https://cloud.githubusercontent.com/assets/10562544/13676574/6dd0f1d4-e6b4-11e5-85e6-3885efc90fbe.png)

#### A6

Vertical bars also work for this set. If the complaint type labels were more descriptive, it might preclude using an option like this.
![screen shot 2016-03-10 at 11 36 13 am](https://cloud.githubusercontent.com/assets/10562544/13676575/6dd4e32a-e6b4-11e5-9f58-183406cafcb4.png)

#### A7

Lastly, This shows each complaint percentage separately as part of 100% (the full width of the graphic). It takes up a lot of room.
![screen shot 2016-03-10 at 11 36 22 am](https://cloud.githubusercontent.com/assets/10562544/13676576/6dd58e06-e6b4-11e5-807d-8b5ff747a04f.png)

**Comment by ekellett** [comment]
![bar chart 3](https://cloud.githubusercontent.com/assets/17163302/13861078/cbb3ce72-ec61-11e5-9d9a-7ecc14b0d69a.png)
![bar chart 2](https://cloud.githubusercontent.com/assets/17163302/13861080/cbb5c1b4-ec61-11e5-997c-1ea0025c59ac.png)
![bar chart 1](https://cloud.githubusercontent.com/assets/17163302/13861079/cbb45f0e-ec61-11e5-98fb-40e750ebfe8c.png)

**Comment by ekellett** [comment]
These are three different bar chart options created quickly in Tableau with the data.  Depends on what you are trying to compare/emphasize.  Feedback is welcome. Looking forward to discussing this!

**Comment by bfongdata** [comment]
Here are a few bar graphs that I made in Tableau.  They look really nice but I want to point out that they do take a lot more clicks than Erin's examples.  My example B1 takes 7-10 clicks more than the bottom graph on Erin's examples.
![bf bar graphs](https://cloud.githubusercontent.com/assets/17927940/13878956/240e9230-eceb-11e5-8804-830ec8607e7a.jpg)

**Comment by bfongdata** [comment]
These are some Tableau bar graphs.  They look nice but I want to emphasize that they take more time than Erin's quick examples.  Some of the steps I had to take to create these are not widely known to users at the Bureau.

![bf bar graphs](https://cloud.githubusercontent.com/assets/17927940/13879051/a3586ec6-eceb-11e5-944a-f467f16f0ad5.jpg)

**Comment by amycesal** [comment]
After our discussion here's what we came up with as some overall conclusions. I tried to do some sorting to work them into categories. 

#### emphasis
- Group for emphasis
- Use color for emphasis
- Use color for grouping
- Limit number of not directly labeled colors
- Avoid random sorting. Sort high to low unless there is a good reason for alphabetical or low to high. 

#### axis
- Use axis interval markers or directly label the values. Not both.
- Axis and axis interval markers use solid lines 
- Trend or reference lines are dashed
- Use important and regular axis interval markers. Limit to 7 max. Use predictive lines to highlight emphasize key points.

#### labeling
- Top or right label stacked bars for maximum horizontal space
- Labels should be the same colors as axis.
- Limit the use of keys. Directly label categories when possible. 
- Value labels outside the bar reduces cognitive burden
- Directly labeled values should be outside the bar (unless there's room)
- Directly labeled values should be inside or outside the bar. Don't mix.
- Limited vertical stacked bars are good. Use a combination of color and direct labeling.

**Comment by JenniferHoran** [comment]
Consistency is great for 508!

Avoid random sorting. Sort high to low unless there is a good reason for alphabetical or low to high. Grouping for emphasis - this is all great because we have to sort using some other indicator then colour. We can still use colour to group if we do these other things. Just watch for contrast :)

Directly labeled values should be inside or outside the bar. Don't mix. - also great for 508.

I really enjoyed watching this exercise unfold.

**Comment by designlanguage** [comment]
@amycesal - I think that unclear comment was related to the vertical stacked bar. We recommended a combination of color coding and direct labeling in that instance as opposed to just one or the other. It'll be interesting to test out some of these recommendations now.

**Comment by amycesal** [comment]
I'm thinking these were our top 5 recommendations/favorites. There are still things to work out with spacing, color, and type, but I think these are generally good, and I updated a few things from our conversation. Next up: talking about type and line charts. Sound like a plan? 

![bar-chart-bonanza_george_01-13](https://cloud.githubusercontent.com/assets/1656046/13997201/5bc75da4-f107-11e5-9c0c-f9c5c48a84f0.png)

![bar-chart-bonanza_george_01-12](https://cloud.githubusercontent.com/assets/1656046/13997211/6491cb2c-f107-11e5-9267-6a09c40fabe4.png)

![bar-chart-bonanza_cesal_01-12](https://cloud.githubusercontent.com/assets/1656046/13997226/750b500e-f107-11e5-918e-ed85155a4d72.png)

![bar-chart-bonanza_cesal_02-16](https://cloud.githubusercontent.com/assets/1656046/13997238/8a404e48-f107-11e5-8e81-c5963c9afb7d.png)

![bar-chart-bonanza_cesal_02-04](https://cloud.githubusercontent.com/assets/1656046/13997319/db28977a-f107-11e5-9d03-94bc83b6f66a.png)

**Comment by Scotchester** [comment]
It seems like this issue has completed its intended purpose. Closing for now!

– The Eye 55 Grooming Crew
