### ISSUE TITLE
Half-width link blob

### ISSUE THREAD

**Issue by ajbush** [cfpb/design-manual#414]
#### What is it?

V1 is looking to add its atomic element documentation to the DM for the use of other teams. Because the primary touchpoint with these elements is through the Wagtail CMS we have focused on the components that will be encountered there. This component is actually a grouping of smaller page components and therefore the page abides by the content guidelines as much as possible but has a few differences. This page will live in the "page components" section of the updated DM.

**Comment by nataliafitzgerald** [comment]
@ajbush @duelj 
<strong>Content edits</strong>
- Change "2-column" to "two column"

<strong>Design edits</strong>
- Can we include more vertical space above the "Style" heading. The content feels crowded there.
- Should "Landing page template" in the first paragraph have the capital "L" or should it be lowercase? Let's be sure to be consistent with what we do across all these pages.

**Comment by sonnakim** [comment]
@schaferjh Providing UX review of this page, thinking about whether a D&D team member would have significant issues understanding this page. Conclusion: They should not. 

My only comments are similar to what I left  <a href="https://github.com/cfpb/design-manual/issues/413#issuecomment-226209228">for the 50/50 image and text component</a>: in the intro section, or somewhere up front, maybe point out related alternate components; also, make clear up front that this is the same as the 50/50 image and text component, just without an image. I'm assuming the two components have dissimilar names for a reason, but if not and it's not too late, maybe even consider renaming one or the other so that it's clear that they are two peas in a pod (e.g. call this "50/50 text component"?).

**Comment by schaferjh** [comment]
@sonnakim great point. I'm holding off on changing the names here until we get them changed in code -- but I'll put it on the team's backlog!

@ajbush looks good, ready to publish!
