### ISSUE TITLE
Wells

### ISSUE THREAD

**Issue by ajbush** [cfpb/design-manual#415]
#### What is it?

V1 is looking to add its atomic element documentation to the DM for the use of other teams. Because the primary touchpoint with these elements is through the Wagtail CMS we have focused on the components that will be encountered there. This component is actually a grouping of smaller page components and therefore the page abides by the content guidelines as much as possible but has a few differences. This page will live in the "page components" section of the updated DM.

**Comment by nataliafitzgerald** [comment]
@ajbush @duelj

Looks good!
- Can we include more vertical space above the "Style" heading. The content feels crowded there.

**Comment by doguin** [comment]
Providing UI review for @schaferjh 
- [x] Are the existing elements helpfully explained? **Yes**
- [x] Does it present an MVP set of information primarily written for the D+D audience in order to support usage of new elements and templates as quickly as possible? **Yes**

Thumbs up.

Other feedback:
- Other component pages contain screenshots of example component elements. It might be helpful to include those here too in addition to the wireframes.
- If a well contains imagery should there be stricter guidance over using a featured content module vs. a well?

**Comment by schaferjh** [comment]
@ajbush looks good, ready to publish.
