### ISSUE TITLE
Email sign-up

### ISSUE THREAD

**Issue by ajbush** [cfpb/design-manual#417]
#### What is it?

V1 is looking to add its atomic element documentation to the DM for the use of other teams. Because the primary touchpoint with these elements is through the Wagtail CMS we have focused on the components that will be encountered there. This component is actually a grouping of smaller page components and therefore the page abides by the content guidelines as much as possible but has a few differences. This page will live in the "page components" section of the updated DM.

**Comment by nataliafitzgerald** [comment]
@ajbush @duelj 

<strong>Design and content feedback</strong>
- Under "Use case" can we make this a single paragraph? 
- Can we include more vertical space above the "Style" heading. The content feels crowded there.
- Could we write these in the same way, so "Breakpoints 900 - 601" and "Breakpoints 600 and less"?
  <img width="912" alt="screen shot 2016-06-15 at 2 35 41 am" src="https://cloud.githubusercontent.com/assets/6887128/16070232/dfbda736-32a1-11e6-86bd-014cbc9dac68.png">

**Comment by doguin** [comment]
Providing UI review for @schaferjh 
- [x] Are the existing elements helpfully explained? **Yes**
- [x] Does it present an MVP set of information primarily written for the D+D audience in order to support usage of new elements and templates as quickly as possible? **Yes**

Thumbs up all around.

Other feedback:
- Should the RSS feed portion be defined/explained?
- Should "Email sign ups **allowed** users to stay..." read "Email sign ups **allow** users to stay..."?
- In the Style section the body copy is defined as Avenir paragraph. Should the Heading typeface be defined as well or is that automatically set in wagtail?

**Comment by schaferjh** [comment]
@ajbush Two tweaks:
- [x] Update the Use case paragraph to read:

> Email sign ups allow users to stay engaged on a specific topic or content type produced by the Bureau. Different page types will be connected to the corresponding GovDelivery list based on the page topic (i.e. HMDA) or page type (i.e. blog). 
> 
> This pattern also includes a link to our privacy statement and a an optional call to action to subscribe to an RSS feed.
- [x] In the mock ups at the top and bottom (where I can read text), the slug text should read "Email updates" per the content guidelines on the page.

**Comment by ajbush** [comment]
Updated!

**Comment by schaferjh** [comment]
👍  ready to publish!
