### ISSUE TITLE
Contact info

### ISSUE THREAD

**Issue by ajbush** [cfpb/design-manual#418]
#### What is it?

V1 is looking to add its atomic element documentation to the DM for the use of other teams. Because the primary touchpoint with these elements is through the Wagtail CMS we have focused on the components that will be encountered there. This component is actually a grouping of smaller page components and therefore the page abides by the content guidelines as much as possible but has a few differences. This page will live in the "page components" section of the updated DM.

**Comment by nataliafitzgerald** [comment]
@ajbush @duelj 
This is looking good!
- Can we include more vertical space above the "Style" heading. The content feels crowded there.
- Is there a way to avoid using secondary bullets? If not, we should style the secondary bullets differently than the primary bullets. Changing just the indent isn't substantial enough.

**Comment by doguin** [comment]
Providing UI review for @schaferjh 
- [x] Are the existing elements helpfully explained? **Yes**
- [x] Does it present an MVP set of information primarily written for the D+D audience in order to support usage of new elements and templates as quickly as possible? **Yes**

Thumbs up.

Other feedback:
- Current opening sentence reads: "The contact information component is used to display phone and/or email, fax information for offices within the Bureau." Suggested sentence: The contact information component is used to display phone, email, mailing address, and fax information for offices within the Bureau.
- Noticed a small typo under Use case > When to use > second bullet: ...when contact information **os** of extra significance...

**Comment by schaferjh** [comment]
@ajbush Minor tweak: Add a hard return in the Content guidelines so that "Mailing address:" (currently at the end of the email address paragraph) shows up on a new line.

**Comment by ajbush** [comment]
Updated!

**Comment by schaferjh** [comment]
👍 ready to publish!
