### ISSUE TITLE
25/75 Image and text

### ISSUE THREAD

**Issue by duelj** [cfpb/design-manual#421]
#### What is it?

V1 is looking to add its atomic element documentation to the DM for the use of other teams. Because the primary touchpoint with these elements is through the Wagtail CMS we have focused on the components that will be encountered there. This component is actually a grouping of smaller page components and therefore the page abides by the content guidelines as much as possible but has a few differences. This page will live in the "page components" section of the updated DM.

**Comment by nataliafitzgerald** [comment]
@ajbush @duelj 

<strong>Content feedback</strong>
- Change "Content Guidelines" to "Content guidelines" (sentence case)
- The "half width link blob" is an unfortunate name for this thing. Were there any alternatives? Also, on this page I see this written in sentence case (half width link blob) and title case (Half Width Link Blob). We should stick to sentence case. 

<strong>Design feedback</strong>
- Can we include more vertical space above the "Style" heading. The content feels crowded there.
- Based on the pattern used throughout the DM, we should use Avenir Next for the intro text. Georgia is currently being used on this page instead.

**Comment by keelerr** [comment]
Also providing UX feedback/review, but most of my questions are based on my own personal questions from other projects.
- In general, could you include an example or two of how this module is being used to feature a specific link or create a hierarchy? I know you're not trying to be overly prescriptive in the text, but personally, I'd love to see a few examples from different parts of the site that—in your mind—use this module in the BEST possible way.
- The intro mentions it can be "used on higher-level template pages", does this mean landing and sub-landing only? Where are you drawing the line? And, does this mean there are no imagery modules for browse or learn pages?

**Comment by schaferjh** [comment]
@keelerr I think your content strategy usage of this module on the pre-paid browse page we discussed is a good addition to the thinking about the module. Would you mind articulating your use case and purpose so we can think about how to make sure that doesn't feel "out of bounds"?

**Comment by schaferjh** [comment]
For the MVP version of this page, we're going to hold off on loading up on specific examples while folks try out all these new pages. We'll gather feedback and if they still feel necessary in a few months, compile examples. In the meantime, some examples include [Policy & compliance](http://www.consumerfinance.gov/policy-compliance/) and [Students and graduates](http://www.consumerfinance.gov/about-us/careers/students-and-graduates/).

We'll take out the reference to "high-level template pages" in order to avoid confusion since in the use case section we indicate that this can definitely be used on browse pages, as can the 50/50 image and text component.

**Comment by schaferjh** [comment]
@ajbush looks great, ready to publish!
