### ISSUE TITLE
Filterable list control panel

### ISSUE THREAD

**Issue by duelj** [cfpb/design-manual#422]
#### What is it?

V1 is looking to add its atomic element documentation to the DM for the use of other teams. Because the primary touchpoint with these elements is through the Wagtail CMS we have focused on the components that will be encountered there. This component is actually a grouping of smaller page components and therefore the page abides by the content guidelines as much as possible but has a few differences. This page will live in the "page components" section of the updated DM.

**Comment by nataliafitzgerald** [comment]
@ajbush @duelj

<strong>Design and content feedback:</strong>
- Based on the pattern used throughout the DM, we should use Avenir Next rather than Georgia for the intro text. 
- Change "Content Guidelines" to "Content guidelines" (sentence case)
- In this sentence: "Headings and answer options should be sentence case (unless specifically Proper Nouns or Titles)" - Change "Proper Nouns or Titles" to "proper nouns or titles")
- Can we include more vertical space above the "Style" heading. The content feels crowded there.

**Comment by schaferjh** [comment]
@ajbush A few tweaks:
- [x] In the intro paragraph, please link "browse filterable template" to the [filterable list template page](http://ajbush.github.io/design-manual/global-elements/filterable-list-pages.html).
- [x] Could you break up the initial mock up so we show collapsed and expanded states in two seperate images? I don't want to imply that two filter panels would be next to each other on the same page.
- [x] In the mock up at the top and the bottom of the page (where you can read text) -- the "Date Range" label should read "Date range" sentence case. (Actually something that needs to be updated on our live site too!)

**Comment by ajbush** [comment]
Updated!

**Comment by schaferjh** [comment]
@ajbush The "expanded" mock up image at the top of the page needs to be updated so it has "Date range". Oh the details...

**Comment by ajbush** [comment]
Good catch! Updated.

**Comment by schaferjh** [comment]
Fabulous!
