### ISSUE TITLE
Landing page template

### ISSUE THREAD

**Issue by duelj** [cfpb/design-manual#423]
#### What is it?

V1 is looking to add its atomic element documentation to the DM for the use of other teams. Because the primary touchpoint with these elements is through the Wagtail CMS we have focused on the components that will be encountered there. 

This page will live in the "global elements" section of the updated DM.

**Comment by nataliafitzgerald** [comment]
@duelj @ajbush 
The design looks good! Just a few copy edits: 
- Change "Its" to "Their" in the following sentence: Their main function is to preview the different sub-pages within that section and help users quickly skim section topics and select the category that interests them."
- Change "Content Guidelines" to "Content guidelines" (i.e. sentence case)
- We are inconsistent in how we refer to certain terms, for example: "Top-level page" versus "top level page". 
- Can we include more vertical space above the "Style" heading. The content feels crowded there.

**Comment by keelerr** [comment]
It's looking good. I have a few comments, though...
- Other than the (obvious) difference in placement within the site, is there significant differentiation between landing and sub-landing pages? I see that some modules cannot be used within the landing page, but in general they seems almost identical. I wonder if there are any design or content strategy nuances that would be helpful to identify.
- I like that you give examples to 2 landing page, but the links don't seem to work. I also think this could be its own bullet.
- Why do you suggest this format for campaign pages rather than sub-landing pages?

**Comment by schaferjh** [comment]
Responding to @keelerr's feedback, I've updated the page intro to clarify the difference between this page type and the landing page type. Certainly welcome more feedback from @sarahsimpson09, but I think this will be serviceable as the page introduction for now:

**Landing page types provide an overview of a main navigation section and helps users situate themselves within the site and the subject matter. Their main function is to preview the different sub-pages within that section and help users quickly skim section topics and select the category that interests them.**

We suggest this page type for campaign pages because thus far our campaign pages usually gather users in at a single focus point and then send them elsewhere in the site for more information, which matches the use case for this page type. As we do more campaigns, we'll find out if that alignment needs to be adjusted.

**Comment by schaferjh** [comment]
@ajbush Looks great, ready to publish!
