### ISSUE TITLE
Document detail page template

### ISSUE THREAD

**Issue by duelj** [cfpb/design-manual#427]
#### What is it?

V1 is looking to add its atomic element documentation to the DM for the use of other teams. Because the primary touchpoint with these elements is through the Wagtail CMS we have focused on the components that will be encountered there. 

This page will live in the "global elements" section of the updated DM.

**Comment by nataliafitzgerald** [comment]
@ajbush @duelj

Design edit:
- Based on the pattern used throughout the DM, we should use Avenir Next, rather than Georgia, for the intro text. 
- Can we include more vertical space above the "Style" heading. The content feels crowded there. 
- For the sidebar, we should consider listing the links on their own line rather than letting them sit side by side. Sometimes we're using a break character and sometimes we aren't. It's creating some visual confusion. 

For example (this is what we have): 
Area 1
Item introduction

Area 2
Full width text field Table Expandable

Area 3
Metadata / Related posts / 
Related links Contact 
information Email sign up

Instead we could do this: 
Area 1
Item introduction

Area 2
Full width text field 
Table 
Expandable

Area 3
Metadata 
Related posts 
Related links 
Contact information 
Email sign up

Copy edits:
- Change "Post Preview" to "Post preview" (sentence case)

**Comment by schaferjh** [comment]
@ajbush Just two small tweaks:
- in the Behavior section, change the "Post Preview" subheader to "Post preview" sentence case to match other instances on the page.
- In the Content guidelines, under Post preview, swap the 1st and 2nd bullet points so the first bullet point is "Function of the post preview..." and the 2nd is "May use up to two categories..."

**Comment by ajbush** [comment]
Updated!

**Comment by schaferjh** [comment]
@ajbush great, ready to publish!
