### ISSUE TITLE
Safe Illustration

### ISSUE THREAD

**Issue by duelj** [cfpb/design-manual#44]
Here are a couple of concepts for the safe. I feel like the door and lock style kinda comes down to preference, there are a million ways we could style it but these were a couple that I liked. I didn't know if there were any specifics that we should consider for the style, I assumed a closed door was mainly what we were looking for. 
![safe_2](https://f.cloud.github.com/assets/6873734/2399987/fa05ac9c-aa04-11e3-91eb-07472446f64c.png)
![safe_1](https://f.cloud.github.com/assets/6873734/2399988/fa07d88c-aa04-11e3-9929-0d81f7576207.png)

**Comment by stephanieosan** [comment]
The second safe feels more safe-like to me! I also like it's knob better. 

The one thing that appears on both safes that bothers me is that the knob face recedes and feels like it's a part of the background, since the background's exact color and highlight is carried over to it. I think this is especially problematic for the first safe, since the door is circular and gets a curved highlight, although the knob is also a circle, but gets a straight highlight.

**Comment by mebates** [comment]
Awesome! I agree that the second one says 'safe' faster.

**Comment by duelj** [comment]
I was having some issues with the cast shadows, my hang-up was whether the shape was supped to be a curved or flay surface vs. the shape being round. I imagined the door 'domed' but the front of the combination lock to be flat. I have an example below that shows two curved shadows and it seems cluttered. Maybe you all have some other ideas? 
![safe_3](https://f.cloud.github.com/assets/6873734/2400341/44e4d4aa-aa09-11e3-9c5c-1483c766785d.png)

Another thought was the amount of stroke use. I think it seems effective here, but it's more than we've used in other places, so this is a version that doesn't lean on stroke use so heavily. 
![safe_4](https://f.cloud.github.com/assets/6873734/2400350/65b74bb8-aa09-11e3-8f42-4993b455ac4b.png)

**Comment by nataliafitzgerald** [comment]
Looking at the larger context of our illustration style, the last option you posted here, with fewer strokes makes the most sense. The handle dimensionality (created by the two gray tones) is working well to give the sense of the material of a safe. Is there a way to bring in this dimensionality to other parts of the safe, for example the combination lock? The legs on the bottom are tripping me up a bit and making this look like the back of a truck to me (those would be the wheels). Does it work without the legs?

**Comment by duelj** [comment]
Heres a little more detail on the stroke-less version, I tried to address the shading on the center dial as well. 
![safe_5](https://f.cloud.github.com/assets/6873734/2402620/90eb5bce-aa24-11e3-9e7b-bbdad797b5f8.png)

**Comment by mebates** [comment]
I'm good with this if everyone else is. Can we close?

**Comment by nataliafitzgerald** [comment]
There were some additional comments made at last week's Design Crit that are not reflected here. I would try coloring the hinges with a lighter shade of gray so they don't stand out so much. Also, take another pass at the knob - Elizabeth mentioned in the crit that it looked like an eye. Can we add something to show depth around the perimeter of the interior square? The interior square is much lighter than the rest, do we have one shade darker that can be used there?

**Comment by nataliafitzgerald** [comment]
I went ahead and made adjustments to the safe, based on my comments above. I changed the corners to curved, simplified the detailing of the knob, reduced the highlights and lowlights to just the knob, and adjusted the coloring. I removed the highlight on the handle because the added detailing was starting to feel too complex when placed with other illustrations.   

![screen shot 2014-03-26 at 10 29 44 am](https://f.cloud.github.com/assets/6887128/2525786/28c2cc88-b4f3-11e3-95de-b756fbe671dd.png)

In the specific project we are working on we also needed a way to visualize a data in the knob (shown below):

![screen shot 2014-03-26 at 10 29 13 am](https://f.cloud.github.com/assets/6887128/2525790/30941084-b4f3-11e3-8bbf-9874c162fee0.png)

**Comment by mebates** [comment]
Looks good to me. How do we reach agreement to 'close' an issue like this? Next step should be to pass it to Stephen to add to the illustration library, correct? 
@ohsk @stephanieosan @elizbond @nataliafitzgerald

**Comment by elizbond** [comment]
@ohsk Remove the shadow on the dial and add to the library.

**Comment by nataliafitzgerald** [comment]
@ohsk The shadow should only be removed from version 2 that includes the data visualization element. And, version 2 is quite specific and will likely not be included in the library. Version 1 is all set as is, with the shadow/highlight.
