### ISSUE TITLE
Shadows and Highlights/Reflections in illustrations

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-manual#50]
Watching the car #46 , wallet #48 and safe #44 illustrations shape up has me thinking about the way we're using shadows and highlights in our illustrations. Do we have any guidelines (or thoughts) about when and how to use those yet?
#### Shadows-related questions
- For shadows, do all of our illustrations have a consistent light source? If so, what is it? 
- When are shadows implemented, just when elements sit on top of one another (which is how they're being used in the wallet) or within objects too? I'm looking at the shadows on those tires (unless we're considering those highlights?), and they're creating definition of the rounded tires itself, versus in the wallet, the pocket of the wallet casts a shadow on the dollar? Also, the closed wallet isn't casting a shadow on the dollar. And nothing on the purse is casting a shadow. What's our thinking about that?

![screen shot 2014-03-18 at 1 39 43 pm](https://f.cloud.github.com/assets/6433178/2451314/49aa1a0c-aec5-11e3-8f9c-c2136c5a8f05.png)
![screen shot 2014-03-18 at 1 43 26 pm](https://f.cloud.github.com/assets/6433178/2451315/4c5adf7a-aec5-11e3-9b80-c3a06c9cbdf2.png)
![screen shot 2014-03-18 at 1 43 07 pm](https://f.cloud.github.com/assets/6433178/2451317/4ecc34b6-aec5-11e3-820f-666f20a0aab7.png)
![screen shot 2014-03-18 at 1 47 58 pm](https://f.cloud.github.com/assets/6433178/2451375/a5a35526-aec5-11e3-8c33-c465e74d73a3.png)
#### Highlight/Reflection questions
- Have we defined what gets a reflection? Just certain types of materials? Plastics, metals, glass, etc?
  ![screen shot 2014-03-18 at 1 45 36 pm](https://f.cloud.github.com/assets/6433178/2451321/5402367e-aec5-11e3-8d0e-c683bb3780dc.png)
  ![screen shot 2014-03-18 at 1 43 07 pm](https://f.cloud.github.com/assets/6433178/2451325/58a34754-aec5-11e3-8edf-ca72902fa80d.png)
  ![screen shot 2014-03-18 at 1 47 23 pm](https://f.cloud.github.com/assets/6433178/2451332/6668ed1c-aec5-11e3-9420-acdda9b99103.png)
#### Then there's also where we use two-tones to create dimension.

Not sure if those should be considered shadows or highlights or a separate thing entirely. 
On the safe: 
![screen shot 2014-03-18 at 1 50 02 pm](https://f.cloud.github.com/assets/6433178/2451387/cb6287c8-aec5-11e3-97ea-dcd2f88a530c.png)

I'm not necessarily saying we need to get into this much detail with our definition of standards and illustration style, since overall, these illustrations still feel like a set, but it does seem like we're beginning to use our shadows and highlights in different types of ways.

**Comment by mebates** [comment]
Thanks Stephanie - I'm working on some new objects for the video (washing machine, locket) and I definitely have these questions.

**Comment by mebates** [comment]
When should the highlight/shadow curve naturally, and when should it be straight or geometric?

**Comment by nataliafitzgerald** [comment]
I have these same questions. Setting baseline standards is a good idea. This does not mean that designers cannot deviate from those standards if their layouts require modifications. But it does ensure that our illustrations maintain a level of consistency within the base library. 

##### Light source

For our standard, objects should be lit from the left side. This is consistent with the beam in our logo and our simple beam graphic.

##### Shadows

In our front-facing illustrations, shadows should be contained within the object. Shadows are appropriate when objects overlap but should not extend outside of objects. The dollar bill on the closed wallet should have a shadow (cast by the wallet). 

In top-facing illustrations, shadows are appropriate when objects overlap as well as when objects overlap a surface. In top-facing illustrations, shadows can fall on the surface that the objects are sitting on. 

##### Highlights

@mebates asked when we use a curved rather than a diagonal highlight. My understanding is that the curved highlight is used for curved objects (yarn ball, pig) and the diagonal is used for more rectangular objects. But, the coin is curved and has a diagonal shadow so there is a contradiction. There is also another type of highlight I am seeing which splits the object in half. @ohsk do you have any thoughts on this? 

##### Two-tones

We should talk through this further. I don't see a pattern so far. I think this is proving problematic on the safe where some elements suggest dimension and other elements are very flat. @ohsk Do you have any thoughts on this?

**Comment by duelj** [comment]
These are good thoughts for sure. I was trying to hunt down the guidelines presentation that @nataliafitzgerald and @elizbond  put together for the 10 hour project stuff because it should have some of the details we figured out on this. I urged to have fewer restrictions on illustration guidelines and rather just give recommendations for defaults which maybe in this case needs to be flushed out more. 

#### The following are my opinions and/or understanding of the guidelines:

My understanding for when to have curved vs. flat I believe was left to designer discretion in our presentation (not 100% on this). My take on it was that the surface shape would dictate the shadow shape. If it is a curved or complex shape the curved shadow can be used, where I imagined if the surface is simple (flat, rectangle, polygon, etc.) the flat shadow would be used. 

The angle of the flat shadow was also left to designer discretion, as some vertically oriented shapes (such as the phone) might be best served with the 9 degree angle shadow where as more horizontal shapes such as the calculator screen could have a corner to corner shadow. I think the main thought was all illustration pieces used in a composition should be consistent in their use. This might mean that illustrations have to be tweaked when being used in a composition. 

My thoughts on the curved shadows are that they get a bit muddy when there are two curved shapes are on top of each other (issues I had with the early safe dial). Maybe this is just something to collectively note and decide on a resolution for. 

#### Sounding some ideas given my take on the guidelines:

Given my thoughts on the shadows I would say I would picture the locket (complex or curved shape and surface) to use the curved shadow. Curved shadow might also be appropriate for dials or the glass door on a front loading washing machine. The flat shadows might be used on the main "body" of the washing machine (assuming its boxy), a screen on the washing machine, etc.

**Comment by mebates** [comment]
@nataliafitzgerald is the Light Source from the upper left or lower left?

**Comment by elizbond** [comment]
This discussion has moved to #192
