### ISSUE TITLE
Document the color generation process

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/design-manual#505]
I know I won't have time to do this before I leave, but maybe someone else can, or I can when I get back. The gist of it is to 

1. take the table of colors from George and Natalia's colors doc, convert it to CSV, and save it to https://github.com/cfpb/design-manual/blob/gh-pages/_data/cfpb-brand-colors.csv
2. Run `npm run colors`, this will auto-generate a new `brand-palette.less` file https://github.com/cfpb/design-manual/blob/gh-pages/src/static/css/brand-palette.less
3. Run `grunt build` (you may need the `-f` flag because of linting issues)
4. Run `npm start` and check `/design-manual/brand-guidelines/color-principles.html` locally
5. Commit the changes and open a PR.

**Comment by cfarm** [comment]
question for designers especially @designlanguage and @nataliafitzgerald: instead of updating the google doc .csv file, can we just keep updating the colors in the [Design Manual .csv](https://github.com/cfpb/design-manual/blob/gh-pages/_data/cfpb-brand-colors.csv)*? Is that easier?

*This is how @nataliafitzgerald made changes for her PR here https://github.com/cfpb/design-manual/pull/504

**Comment by nataliafitzgerald** [comment]
Yes, I think updating the [Design Manual .csv](https://github.com/cfpb/design-manual/blob/gh-pages/_data/cfpb-brand-colors.csv) is easier but not sure of what the logic was with maintaining the Google Doc .csv file instead. I actually made the changes locally to the [Design Manual .csv](https://github.com/cfpb/design-manual/blob/gh-pages/_data/cfpb-brand-colors.csv) and then updated the Google Doc after the fact.

**Comment by jimmynotjim** [comment]
Finally opened a PR for this.
