### ISSUE TITLE
Create icon standard hypothesis

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/design-manual#547]
Analyze the current set of icons for:

- line weights
- sizes with and without circles
- relationship to inline text, both with and without circles

**Comment by designlanguage** [comment]
@Dnpizarro -
I'm currently exploring icon sizing and placement, specifically related to Avenir and the icon circle. 

Since they all have to fit in the same size circle, I don't think there should be much variation in the size of the icons. This diagram proposes how vertical and horizontal they should get.

My theory is that icons should be centered within the x-height, not sitting on the baseline. We need to test out this theory and see if it looks good, but it's a starting point.

| Shape | Image |
| --- | --- |
| Circle icon | ![screen shot 2017-12-22 at 1 40 11 pm](https://user-images.githubusercontent.com/10562544/34309029-f9cb72f2-e71d-11e7-9439-281541a216f9.png) |
| Max horizontal | ![screen shot 2017-12-22 at 1 40 29 pm](https://user-images.githubusercontent.com/10562544/34309031-f9ec38d4-e71d-11e7-9829-0e1a6443589b.png) |
| Horizontal icon | ![screen shot 2017-12-22 at 1 40 41 pm](https://user-images.githubusercontent.com/10562544/34309032-f9ff53ce-e71d-11e7-96bd-ac6a9a62c675.png) |
| Square icon | ![screen shot 2017-12-22 at 1 41 06 pm](https://user-images.githubusercontent.com/10562544/34309034-fa284c98-e71d-11e7-9df8-573de3f3412d.png) |
| Vertical icon | ![screen shot 2017-12-22 at 1 40 53 pm](https://user-images.githubusercontent.com/10562544/34309033-fa1407e2-e71d-11e7-848b-716ed2394a4d.png) |
| Max vertical | ![screen shot 2017-12-22 at 1 40 20 pm](https://user-images.githubusercontent.com/10562544/34309030-f9de087c-e71d-11e7-954c-c7500dca526d.png) |

**Comment by designlanguage** [comment]
For the icons outside of circle, it may be more important for them to sit on the baseline than correspond to the positioning they would have in the circle. If that's the case, the grid could be something like this:

![screen shot 2018-01-10 at 2 48 00 pm](https://user-images.githubusercontent.com/10562544/34792416-f1ae7554-f615-11e7-8211-21bf024c082d.png)

**Comment by jimmynotjim** [comment]
We came up with an initial standard and need to revisit canvas size, icons size, and line weights. Those will all go into a new hypothesis.
