### ISSUE TITLE
Graphic Designers - Test 10 draft minicons in a print docs

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/design-manual#558]
Test in both a print form and handout

**Comment by Dnpizarro** [comment]
Below is the comparison between our explorations for 30pt and 40pt stroke width. There are a couple other explorations that I plan to compare, but I wanted to post this so that we can begin the conversation.

@designlanguage @jimmynotjim 

![artboard 1](https://user-images.githubusercontent.com/6852363/34793263-c023c748-f618-11e7-9778-a5ad51e2181f.png)

**Comment by Scotchester** [comment]
At a glance, I like the 30pt better. It feels less heavy, which feels more in keeping with our overall design philosophy.

Out of curiosity, when you say 30 and 40pt, what is that in reference to? Initially drawing the icons on a very large canvas?

**Comment by Dnpizarro** [comment]
@Scotchester sorry for not clarifying but its in reference to the line weight of the icon relative to our artboard. The artboard is a different size, so the weight of the icon in context of the print handouts is not actually 30pt, if that makes sense.

**Comment by jimmynotjim** [comment]
@Dnpizarro I think Scott means what's the baseline. The icons in that doc aren't 30pt and 40pt thick at that scale correct?

**Comment by Dnpizarro** [comment]
Below is an updated comparison for print of the 3 sets of icons we've developed. I cropped the documents to pull them in closer for better comparison.
@designlanguage @jimmynotjim @Scotchester 

![set_comparison-01](https://user-images.githubusercontent.com/6852363/34845482-f87b742c-f6e2-11e7-89af-01d72daa37b3.png)
