### ISSUE TITLE
Update group 1 icons - Financial Products

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/design-manual#573]
Update the first group of icons and export for print and web. Ensure the file names match the names used in the Design Manual, the paths are grouped into a top-level group, and everything is converted to outlines.

**Comment by jimmynotjim** [comment]
We're going to split this group in half because it's so large and most likely to have unexpected issues with the standard. 

@designlanguage @Dnpizarro could you post here with a list of what icons each of you are updating?

**Comment by designlanguage** [comment]
![screen shot 2018-01-22 at 11 19 33 am](https://user-images.githubusercontent.com/10562544/35231215-328015c0-ff66-11e7-94f4-153a73d6e304.png)

**Comment by designlanguage** [comment]
Here are the icons I've worked on. They haven't been fully outlined yet as I want to make sure there aren't any other tweaks to our guidelines. 

Overall, the intent behind our sizing grid is to give every icon a similar visual prominence, so one doesn't feel much larger than another. This grid doesn't strictly apply when you have oddly-shaped icons, so I've noted below where there are exceptions. Here's an example:
![screen shot 2018-01-22 at 6 22 05 pm](https://user-images.githubusercontent.com/10562544/35249745-3518c440-ffa1-11e7-8776-7b75823cb362.png)

| Name | Symbol | In circle | Notes |
| --- | --- | --- |  --- |
| Credit-card | ![screen shot 2018-01-22 at 5 59 57 pm](https://user-images.githubusercontent.com/10562544/35249141-eef1a984-ff9e-11e7-8941-dafcd46728db.png) | ![screen shot 2018-01-22 at 6 00 23 pm](https://user-images.githubusercontent.com/10562544/35249142-ef0106ea-ff9e-11e7-8c00-b29b9c1431ba.png) |  |
| Building-credit | ![screen shot 2018-01-22 at 6 00 28 pm](https://user-images.githubusercontent.com/10562544/35249144-ef131236-ff9e-11e7-82ce-e767f71acfa7.png) | ![screen shot 2018-01-22 at 6 00 34 pm](https://user-images.githubusercontent.com/10562544/35249145-ef234c50-ff9e-11e7-89a4-8f0b906ed991.png) | Broke the grid for visual balance. |
| Prepaid-cards |  ![screen shot 2018-01-22 at 6 35 31 pm](https://user-images.githubusercontent.com/10562544/35250148-24e033ea-ffa3-11e7-9bf3-af2387bd7695.png) | ![screen shot 2018-01-22 at 6 35 38 pm](https://user-images.githubusercontent.com/10562544/35250149-24f0c2be-ffa3-11e7-9a0b-64c421cd50b8.png) | New dollar symbol that works better at small sizes. |
| Contract | ![screen shot 2018-01-22 at 6 00 41 pm](https://user-images.githubusercontent.com/10562544/35249146-ef2fcd36-ff9e-11e7-9623-7a82e4611c1e.png) | ![screen shot 2018-01-22 at 6 01 47 pm](https://user-images.githubusercontent.com/10562544/35249147-ef404616-ff9e-11e7-8ef8-9c39adb7c85a.png) |  |
| Getting-credit-card | ![screen shot 2018-01-22 at 6 01 55 pm](https://user-images.githubusercontent.com/10562544/35249148-ef4f76fe-ff9e-11e7-95fc-98ceaeb6c41a.png) | ![screen shot 2018-01-22 at 6 02 01 pm](https://user-images.githubusercontent.com/10562544/35249149-ef5c6ff8-ff9e-11e7-99b7-dc780ef18d00.png) | This uneven shape breaks the grid to keep it visually balanced. |
| Money | ![screen shot 2018-01-22 at 6 02 23 pm](https://user-images.githubusercontent.com/10562544/35249152-ef8e22b4-ff9e-11e7-8620-ea36482b1dea.png) | ![screen shot 2018-01-22 at 6 02 29 pm](https://user-images.githubusercontent.com/10562544/35249153-efa3b28c-ff9e-11e7-893b-2644718426b9.png) | Added a circle to the dollar bill symbol. |
| Money-transfer | ![screen shot 2018-01-22 at 6 02 12 pm](https://user-images.githubusercontent.com/10562544/35249150-ef6eba96-ff9e-11e7-854c-38da5996ea1a.png) | ![screen shot 2018-01-22 at 6 02 16 pm](https://user-images.githubusercontent.com/10562544/35249151-ef808d84-ff9e-11e7-9253-2d9af96a57e1.png) | Broke the grid here. |
| Quick-Cash | ![screen shot 2018-01-24 at 9 40 46 am](https://user-images.githubusercontent.com/10562544/35338017-c0764afe-00ea-11e8-9aa2-16e572e3513b.png) | ![screen shot 2018-01-24 at 9 40 52 am](https://user-images.githubusercontent.com/10562544/35338018-c08b1bb4-00ea-11e8-8034-8f6e5f1766cf.png) |
| Debt | ![screen shot 2018-01-22 at 6 02 38 pm](https://user-images.githubusercontent.com/10562544/35249154-efb0ac12-ff9e-11e7-9934-86101827e65a.png) | ![screen shot 2018-01-22 at 6 02 44 pm](https://user-images.githubusercontent.com/10562544/35249156-efc0898e-ff9e-11e7-95e5-d99e2947953a.png) | This will need a new concept after MVP is complete. |
| Mortgage | ![screen shot 2018-01-22 at 6 02 51 pm](https://user-images.githubusercontent.com/10562544/35249157-efcd6fa0-ff9e-11e7-84f6-943ebd4e7a35.png) | ![screen shot 2018-01-22 at 6 02 56 pm](https://user-images.githubusercontent.com/10562544/35249158-efd97336-ff9e-11e7-8cec-ca8e2d7889ec.png) | We should avoid using text if possible, but this concept needs it. We'll revisit this after MVP. This also breaks the grid. |
| Buying-car | ![screen shot 2018-01-22 at 6 03 06 pm](https://user-images.githubusercontent.com/10562544/35249159-efe3b602-ff9e-11e7-82b5-7688fa4abf50.png) | ![screen shot 2018-01-22 at 6 03 10 pm](https://user-images.githubusercontent.com/10562544/35249160-eff5df44-ff9e-11e7-8259-0716c2a09625.png) |  |
| Debt-collection | ![screen shot 2018-01-22 at 6 03 17 pm](https://user-images.githubusercontent.com/10562544/35249162-f00a3796-ff9e-11e7-8783-c4388f3a3e38.png) | ![screen shot 2018-01-22 at 6 03 24 pm](https://user-images.githubusercontent.com/10562544/35249163-f0169662-ff9e-11e7-94c5-3837514b9f2e.png) | Spaces between fingers are a little thinner than our guidelines. This may have to be an exception. |
| Complaint | ![screen shot 2018-01-22 at 6 03 36 pm](https://user-images.githubusercontent.com/10562544/35249164-f0232a1c-ff9e-11e7-9057-9ad7388af9aa.png) | ![screen shot 2018-01-22 at 6 03 40 pm](https://user-images.githubusercontent.com/10562544/35249165-f033384e-ff9e-11e7-81aa-14840a195aff.png) | New exclamation point here that better matches the other symbols. Breaks the grid due to the triangle at the bottom. |

**Comment by designlanguage** [comment]
Here is a large chunk of group 2:

| Name | Symbol | In circle | notes |
| --- |  --- |  --- |  --- |
| External-link | ![screen shot 2018-01-23 at 1 40 11 pm](https://user-images.githubusercontent.com/10562544/35294163-e720210e-0043-11e8-88e0-837924da3924.png) | ![screen shot 2018-01-23 at 1 40 16 pm](https://user-images.githubusercontent.com/10562544/35294164-e72a8022-0043-11e8-91ee-e615da75402e.png) | Because of the first few icons in this group, i think we need to add a thinner line-weight for simple icons (100pt in addition to 130). Open to other ways to solve this. |
| Link | ![screen shot 2018-01-23 at 1 39 49 pm](https://user-images.githubusercontent.com/10562544/35294161-e700e7f8-0043-11e8-8d1b-0efd468069dd.png) | ![screen shot 2018-01-23 at 1 40 05 pm](https://user-images.githubusercontent.com/10562544/35294162-e7122fea-0043-11e8-8676-d85f01736089.png) | Unusual shape breaks the grid to maintain visual balance with other icons. |
| Share | ![screen shot 2018-01-23 at 1 40 23 pm](https://user-images.githubusercontent.com/10562544/35294166-e7446bd6-0043-11e8-81c9-c7f5a7393fe9.png) | ![screen shot 2018-01-23 at 1 40 28 pm](https://user-images.githubusercontent.com/10562544/35294167-e751702e-0043-11e8-9113-ac4aee842099.png) | Unusual shape breaks the grid to maintain visual balance with other icons. |
| Bookmark | ![screen shot 2018-01-23 at 1 40 34 pm](https://user-images.githubusercontent.com/10562544/35294168-e75f5fb8-0043-11e8-9108-0d1653800b91.png) | ![screen shot 2018-01-23 at 1 40 38 pm](https://user-images.githubusercontent.com/10562544/35294169-e76f1908-0043-11e8-97e2-ccd924fd5eea.png) |  |
| Unbookmark | ![screen shot 2018-01-23 at 1 40 43 pm](https://user-images.githubusercontent.com/10562544/35294170-e78240e6-0043-11e8-9adc-19121aa87051.png) | ![screen shot 2018-01-23 at 1 40 48 pm](https://user-images.githubusercontent.com/10562544/35294171-e791cdcc-0043-11e8-88a7-32c73c1be583.png) |  |
| Favorite | ![screen shot 2018-01-23 at 1 40 58 pm](https://user-images.githubusercontent.com/10562544/35294172-e7a67362-0043-11e8-86f5-889122c8aa08.png) | ![screen shot 2018-01-23 at 1 41 02 pm](https://user-images.githubusercontent.com/10562544/35294173-e7b425e8-0043-11e8-9d71-fdc7e2ea2901.png) | Breaks the grid for visual balance. |
| Unfavorite | ![screen shot 2018-01-23 at 1 41 09 pm](https://user-images.githubusercontent.com/10562544/35294174-e7e9e6ce-0043-11e8-82b3-77716eee089b.png) | ![screen shot 2018-01-23 at 1 41 14 pm](https://user-images.githubusercontent.com/10562544/35294176-e80f5cc4-0043-11e8-9190-0d17757e0b69.png) | " |
| Information | ![screen shot 2018-01-23 at 1 41 22 pm](https://user-images.githubusercontent.com/10562544/35294177-e82abe38-0043-11e8-8ff8-e63ba7aab7d1.png) | ![screen shot 2018-01-23 at 1 41 27 pm](https://user-images.githubusercontent.com/10562544/35294179-e869bb88-0043-11e8-93a9-660d085e8b43.png) | Used an upside-down exclamation point to maintain style. |
| Audio-max | ![screen shot 2018-01-23 at 1 41 39 pm](https://user-images.githubusercontent.com/10562544/35294180-e8831c5e-0043-11e8-897f-0fed23982743.png) | ![screen shot 2018-01-23 at 1 41 46 pm](https://user-images.githubusercontent.com/10562544/35294181-e89e0320-0043-11e8-93a1-f2a7359586f8.png) |  |
| Audio-medium | ![screen shot 2018-01-23 at 1 41 51 pm](https://user-images.githubusercontent.com/10562544/35294182-e8adc83c-0043-11e8-9d55-05f84f7318c5.png) | ![screen shot 2018-01-23 at 1 41 56 pm](https://user-images.githubusercontent.com/10562544/35294183-e8cb35de-0043-11e8-9483-b8736f54bd40.png) |  |
| Audio-low | ![screen shot 2018-01-23 at 1 42 02 pm](https://user-images.githubusercontent.com/10562544/35294184-e8e0859c-0043-11e8-8c72-b191bf0ebc4d.png) | ![screen shot 2018-01-23 at 1 42 07 pm](https://user-images.githubusercontent.com/10562544/35294185-e8f23864-0043-11e8-8a68-f2e7bf9b5a93.png) |  |
| Audio-mute | ![screen shot 2018-01-23 at 1 42 13 pm](https://user-images.githubusercontent.com/10562544/35294186-e901e9e4-0043-11e8-8803-6cd506d89b8e.png) | ![screen shot 2018-01-23 at 1 42 20 pm](https://user-images.githubusercontent.com/10562544/35294187-e9131fd4-0043-11e8-88c0-e686ddc35253.png) | Added an "x" to indicate better indicate mute. |
| Double-quote |  ![screen shot 2018-01-23 at 1 42 37 pm](https://user-images.githubusercontent.com/10562544/35294188-e928e1a2-0043-11e8-890c-1ef4a1793cea.png) | ![screen shot 2018-01-23 at 1 42 41 pm](https://user-images.githubusercontent.com/10562544/35294189-e93e16c6-0043-11e8-935c-daaa7e6ce406.png) | Tried to keep this style more in line with our simple icons. |
| _unnamed in design manual_ | ![screen shot 2018-01-23 at 1 42 46 pm](https://user-images.githubusercontent.com/10562544/35294190-e954c218-0043-11e8-9ee8-9a1f541ed413.png) | ![screen shot 2018-01-23 at 1 42 52 pm](https://user-images.githubusercontent.com/10562544/35294191-e962d59c-0043-11e8-9802-b509d63fb2ce.png) |  |
| Clock | ![screen shot 2018-01-23 at 1 43 03 pm](https://user-images.githubusercontent.com/10562544/35294192-e973d1bc-0043-11e8-9cd1-14482d6aa7d9.png) | ![screen shot 2018-01-23 at 1 43 09 pm](https://user-images.githubusercontent.com/10562544/35294193-e989201c-0043-11e8-80ac-4f2ee7774076.png) | Hands feel a little thin with our rules, but maybe it's okay. |
| Lock | ![screen shot 2018-01-23 at 1 43 17 pm](https://user-images.githubusercontent.com/10562544/35294194-e9a1e8d6-0043-11e8-9e44-ee257eabd06d.png) | ![screen shot 2018-01-23 at 1 43 22 pm](https://user-images.githubusercontent.com/10562544/35294195-e9b431da-0043-11e8-85fd-ac27f38104ef.png) |  |
| Unlock | ![screen shot 2018-01-23 at 1 43 29 pm](https://user-images.githubusercontent.com/10562544/35294196-e9cc59b8-0043-11e8-8cee-2961084708d4.png) | ![screen shot 2018-01-23 at 1 43 34 pm](https://user-images.githubusercontent.com/10562544/35294197-e9fe6962-0043-11e8-95e3-f4e623bc7c24.png) |  |
| Search | ![screen shot 2018-01-23 at 1 44 17 pm](https://user-images.githubusercontent.com/10562544/35294198-ea1ace0e-0043-11e8-949b-ad3bc64c8dd4.png) | ![screen shot 2018-01-23 at 1 44 25 pm](https://user-images.githubusercontent.com/10562544/35294199-ea301908-0043-11e8-9235-722d667aa755.png) |  |
| Menu | ![screen shot 2018-01-23 at 1 45 40 pm](https://user-images.githubusercontent.com/10562544/35294200-ea41192e-0043-11e8-80b2-f68a8ca6a3d8.png) | ![screen shot 2018-01-23 at 1 45 46 pm](https://user-images.githubusercontent.com/10562544/35294201-ea5312b4-0043-11e8-97be-04c06d48fd40.png) |  |

**Comment by Dnpizarro** [comment]
Below is my half of the financial products icons. Also, @designlanguage you might want to post the web icons you've worked on in issue #574.

| Name | Symbol | In circle | Notes |
| --- | --- | --- |  --- |
| Credit-report | ![artboard 2 copy 7](https://user-images.githubusercontent.com/6852363/35298687-f3d29988-0050-11e8-8759-6249710ae35a.png) | ![artboard 2 copy 15](https://user-images.githubusercontent.com/6852363/35298704-03113a62-0051-11e8-98f7-b45dda461899.png) |  |
| Bank_account | ![artboard 2 copy 11](https://user-images.githubusercontent.com/6852363/35298756-2802f41e-0051-11e8-95e2-c795c46bb929.png) | ![artboard 2 copy 19](https://user-images.githubusercontent.com/6852363/35298781-34b9ef14-0051-11e8-9636-6a1a42a25239.png) |  |
| Loan |  ![artboard 2 copy 8](https://user-images.githubusercontent.com/6852363/35298826-54011e4c-0051-11e8-88d5-6090c50919ee.png) | ![artboard 2 copy 16](https://user-images.githubusercontent.com/6852363/35298833-5e14a49e-0051-11e8-8d6b-d40ee35cf668.png) |  |
| Payday-loan | ![artboard 2 copy 9](https://user-images.githubusercontent.com/6852363/35298873-81c0bc0c-0051-11e8-9374-2ad4a26608ff.png) | ![artboard 2 copy 17](https://user-images.githubusercontent.com/6852363/35298886-8b8892be-0051-11e8-89e9-157c472f5f7e.png)| Lines in the circle version had to be manual adjusted to create a balanced visual match to the symbol |
| Paying-college | ![artboard 2 copy 6](https://user-images.githubusercontent.com/6852363/35298960-d2d30686-0051-11e8-8d15-7f5dd0dfd680.png) | ![artboard 2 copy 14](https://user-images.githubusercontent.com/6852363/35298991-e25cd186-0051-11e8-9c74-d8f32c78f041.png) | It was easier to just draw a newer version. We can change this once we get some feedback. |
| Retirement | ![artboard 2 copy 10](https://user-images.githubusercontent.com/6852363/35299054-149e7d16-0052-11e8-84ec-324a8ceabb30.png) | ![artboard 2 copy 18](https://user-images.githubusercontent.com/6852363/35299064-1e24e42e-0052-11e8-9706-d4b342f6ded4.png) |  |

**Comment by designlanguage** [comment]
@Dnpizarro - thanks, I moved my group 2 set to the other page.

I like these. My only comment is that there shouldn't be hard edges on the bank (similar to how we changes the house).

**Comment by Dnpizarro** [comment]
Below are the notes from our working session earlier today:

**Prepaid:** Center circle icon, and make coin larger.
**Contract:** Make the top of pen more rounded.
**Getting credit card:** Center the circle icon. 
**Money Transfer:** Reconsider a lower stroke weight, 35pt=symbol, 30pt=circle
**Bank account:** Round the edges on both symbol and circle version
**Loan:** Check stroke weight
**Payday-loan:** This will be redrawn at a later sprint. 
**Paying for college:** Bottom part too long and looks like paceman. Also, the negative space on the symbol is too big, make 50pt stroke.
**Retirement:** Make tail smaller and curve the ear shape.

**Comment by Dnpizarro** [comment]
The updated full set for the Financial Product Icons is below. @jimmynotjim @Scotchester @designlanguage 

| Name | Symbol | In circle | Notes |
| --- | --- | --- |  --- |
| Credit-card | ![artboard 2 copy 53](https://user-images.githubusercontent.com/6852363/35364274-3868fe5c-013c-11e8-85e9-ff3939734e4c.png) | ![artboard 2 copy 54](https://user-images.githubusercontent.com/6852363/35364283-42ab0e82-013c-11e8-94e0-294d84179e59.png) |  |
| Building-credit | ![artboard 2 copy 68](https://user-images.githubusercontent.com/6852363/35364292-50a0d9ae-013c-11e8-946a-c2c040eb6861.png) | ![artboard 2 copy 67](https://user-images.githubusercontent.com/6852363/35364297-57e07580-013c-11e8-8f4e-35f5fb2e5e41.png) |  |
| Prepaid-cards | ![artboard 2 copy 47](https://user-images.githubusercontent.com/6852363/35364312-6e2fdee8-013c-11e8-997c-1f7164c0a01b.png) | ![artboard 2 copy 48](https://user-images.githubusercontent.com/6852363/35364318-791cd518-013c-11e8-8d9b-7ed4f8313076.png) | Made the coin in the circle larger and centered the icon |
| Contract | ![artboard 2 copy 72](https://user-images.githubusercontent.com/6852363/35364333-9325a962-013c-11e8-9f34-72c04d07fa65.png) | ![artboard 2 copy 71](https://user-images.githubusercontent.com/6852363/35364338-9c1c67fe-013c-11e8-9164-e1cc355a93b8.png) | Made the tip of the pen 60pt for the symbol and 50pt in the circle version  |
| Getting-credit-card | ![artboard 2 copy 49](https://user-images.githubusercontent.com/6852363/35364720-ae2c7d10-013e-11e8-9441-449432940201.png) | ![artboard 2 copy 70](https://user-images.githubusercontent.com/6852363/35364736-c4c52144-013e-11e8-94bf-6ae3fdf5a039.png) |  |
| Money | ![artboard 2 copy 51](https://user-images.githubusercontent.com/6852363/35364742-d6d2cef4-013e-11e8-9eb0-b5034cdd13fa.png) | ![artboard 2 copy 52](https://user-images.githubusercontent.com/6852363/35364752-e2769f7e-013e-11e8-8da0-a99e806e151d.png) | Dollar line weight for symbol is 50pt and 30pt for circle |
| Money-transfer | ![artboard 2 copy 56](https://user-images.githubusercontent.com/6852363/35364794-1f07c404-013f-11e8-9928-bd5c6f1d9d64.png) | ![artboard 2 copy 55](https://user-images.githubusercontent.com/6852363/35364800-27c9b0d4-013f-11e8-8355-45a79caccc76.png) | Dollar line weight for symbol is 40pt and 30pt for circle |
| Quick-Cash | ![artboard 2 copy 20](https://user-images.githubusercontent.com/6852363/35364834-55494c68-013f-11e8-91db-9bbd98caa7a2.png) | ![artboard 2 copy 2](https://user-images.githubusercontent.com/6852363/35364843-5f1e374e-013f-11e8-9c61-468f7709b12d.png) | |
| Debt | ![artboard 2 copy 57](https://user-images.githubusercontent.com/6852363/35364856-6ba85166-013f-11e8-8a7b-1865d2861517.png) | ![artboard 2 copy 58](https://user-images.githubusercontent.com/6852363/35364865-7d76ae38-013f-11e8-87ef-cbdb65de3888.png) |  |
| Mortgage | ![artboard 2 copy 59](https://user-images.githubusercontent.com/6852363/35364886-921db6e2-013f-11e8-8e0c-6bb52244642b.png) | ![artboard 2 copy 60](https://user-images.githubusercontent.com/6852363/35364892-9c649a6c-013f-11e8-944b-f799f19d3363.png) |  |
| Buying-car | ![artboard 2 copy 61](https://user-images.githubusercontent.com/6852363/35364923-d257763a-013f-11e8-8a82-4e24b6d59331.png) | ![artboard 2 copy 62](https://user-images.githubusercontent.com/6852363/35364933-da9a806c-013f-11e8-8f71-5954ce50e3f9.png) |  |
| Debt-collection | ![artboard 2 copy 63](https://user-images.githubusercontent.com/6852363/35364941-e3d1f458-013f-11e8-901b-c9cd0697bf12.png) | ![artboard 2 copy 64](https://user-images.githubusercontent.com/6852363/35364949-ebbef5f8-013f-11e8-8ac6-dd4b3b11a912.png) |  |
| Complaint | ![artboard 2 copy 65](https://user-images.githubusercontent.com/6852363/35364973-0597542a-0140-11e8-862c-5a64ac8d5531.png) | ![artboard 2 copy 66](https://user-images.githubusercontent.com/6852363/35364984-0ff2170c-0140-11e8-923a-b4eb919ca740.png) | We'll need to test the fidelity on the exclamation mark |
| Credit-report | ![artboard 2 copy 27](https://user-images.githubusercontent.com/6852363/35365021-4b7a1aea-0140-11e8-873b-9586219e76d3.png) | ![artboard 2 copy 28](https://user-images.githubusercontent.com/6852363/35365025-53063e60-0140-11e8-8918-fa4f47e3fba9.png) | corrected the rounded edges on the circle to 20pt |
| Bank_account | ![artboard 2 copy 34](https://user-images.githubusercontent.com/6852363/35365052-74d32c38-0140-11e8-93c6-9867a8351b1b.png) | ![artboard 2 copy 33](https://user-images.githubusercontent.com/6852363/35365059-80dc18f0-0140-11e8-84b2-2b9321c13a59.png) |  |
| Loan | ![artboard 2 copy 29](https://user-images.githubusercontent.com/6852363/35365080-93039a6c-0140-11e8-9c01-2a865800cdd1.png) | ![artboard 2 copy 30](https://user-images.githubusercontent.com/6852363/35365085-9d2f03fa-0140-11e8-870d-ffcaeb35c75b.png) |  |
| Payday-loan | ![artboard 2 copy 31](https://user-images.githubusercontent.com/6852363/35365099-a97e5e3a-0140-11e8-9fb4-3670b6bcf87f.png) | ![artboard 2 copy 32](https://user-images.githubusercontent.com/6852363/35365111-b955abba-0140-11e8-9852-989e9330b8ee.png) |  |
| Paying-college | ![artboard 2 copy 25](https://user-images.githubusercontent.com/6852363/35365119-ca8792fe-0140-11e8-90e8-7b2ba927236e.png) | ![artboard 2 copy 26](https://user-images.githubusercontent.com/6852363/35365130-d2b8121e-0140-11e8-8722-5ceb7e61e9d1.png) | Reworked the bottom edge to be rounded and changed the stroke weight between the cap and bottom part to 50pt |
| Retirement | ![artboard 2 copy 35](https://user-images.githubusercontent.com/6852363/35365193-18375c78-0141-11e8-9f25-4ffba833d291.png) | ![artboard 2 copy 36](https://user-images.githubusercontent.com/6852363/35365198-23cad5b0-0141-11e8-833e-e9b7c13a0fb7.png) | Made the tail smaller and added a curve to the ear |
