### ISSUE TITLE
Update group 2 icons - Web Icons

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/design-manual#574]
Update the second group of icons and export for print and web. Ensure the file names match the names used in the Design Manual, the paths are grouped into a top-level group, and everything is converted to outlines.

**Comment by jimmynotjim** [comment]
We're also going to split this group in half because it's so large and somewhat likely to have unexpected issues with the standard.

@designlanguage @Dnpizarro when you get to this one, could one of you post here with a list of what icons each of you are updating?

**Comment by designlanguage** [comment]
Here is a large chunk of group 2:

| Name | Symbol | In circle | notes |
| --- |  --- |  --- |  --- |
| External-link | ![screen shot 2018-01-23 at 1 40 11 pm](https://user-images.githubusercontent.com/10562544/35294163-e720210e-0043-11e8-88e0-837924da3924.png) | ![screen shot 2018-01-23 at 1 40 16 pm](https://user-images.githubusercontent.com/10562544/35294164-e72a8022-0043-11e8-91ee-e615da75402e.png) | Because of the first few icons in this group, i think we need to add a thinner line-weight for simple icons (100pt in addition to 130). Open to other ways to solve this. |
| Link | ![screen shot 2018-01-23 at 1 39 49 pm](https://user-images.githubusercontent.com/10562544/35294161-e700e7f8-0043-11e8-8d1b-0efd468069dd.png) | ![screen shot 2018-01-23 at 1 40 05 pm](https://user-images.githubusercontent.com/10562544/35294162-e7122fea-0043-11e8-8676-d85f01736089.png) | Unusual shape breaks the grid to maintain visual balance with other icons. |
| Share | ![screen shot 2018-01-23 at 1 40 23 pm](https://user-images.githubusercontent.com/10562544/35294166-e7446bd6-0043-11e8-81c9-c7f5a7393fe9.png) | ![screen shot 2018-01-23 at 1 40 28 pm](https://user-images.githubusercontent.com/10562544/35294167-e751702e-0043-11e8-9113-ac4aee842099.png) | Unusual shape breaks the grid to maintain visual balance with other icons. |
| Bookmark | ![screen shot 2018-01-23 at 1 40 34 pm](https://user-images.githubusercontent.com/10562544/35294168-e75f5fb8-0043-11e8-9108-0d1653800b91.png) | ![screen shot 2018-01-23 at 1 40 38 pm](https://user-images.githubusercontent.com/10562544/35294169-e76f1908-0043-11e8-97e2-ccd924fd5eea.png) |  |
| Unbookmark | ![screen shot 2018-01-23 at 1 40 43 pm](https://user-images.githubusercontent.com/10562544/35294170-e78240e6-0043-11e8-9adc-19121aa87051.png) | ![screen shot 2018-01-23 at 1 40 48 pm](https://user-images.githubusercontent.com/10562544/35294171-e791cdcc-0043-11e8-88a7-32c73c1be583.png) |  |
| Favorite | ![screen shot 2018-01-23 at 1 40 58 pm](https://user-images.githubusercontent.com/10562544/35294172-e7a67362-0043-11e8-86f5-889122c8aa08.png) | ![screen shot 2018-01-23 at 1 41 02 pm](https://user-images.githubusercontent.com/10562544/35294173-e7b425e8-0043-11e8-9d71-fdc7e2ea2901.png) | Breaks the grid for visual balance. |
| Unfavorite | ![screen shot 2018-01-23 at 1 41 09 pm](https://user-images.githubusercontent.com/10562544/35294174-e7e9e6ce-0043-11e8-82b3-77716eee089b.png) | ![screen shot 2018-01-23 at 1 41 14 pm](https://user-images.githubusercontent.com/10562544/35294176-e80f5cc4-0043-11e8-9190-0d17757e0b69.png) | " |
| Information | ![screen shot 2018-01-23 at 1 41 22 pm](https://user-images.githubusercontent.com/10562544/35294177-e82abe38-0043-11e8-8ff8-e63ba7aab7d1.png) | ![screen shot 2018-01-23 at 1 41 27 pm](https://user-images.githubusercontent.com/10562544/35294179-e869bb88-0043-11e8-93a9-660d085e8b43.png) | Used an upside-down exclamation point to maintain style. |
| Audio-max | ![screen shot 2018-01-23 at 1 41 39 pm](https://user-images.githubusercontent.com/10562544/35294180-e8831c5e-0043-11e8-897f-0fed23982743.png) | ![screen shot 2018-01-23 at 1 41 46 pm](https://user-images.githubusercontent.com/10562544/35294181-e89e0320-0043-11e8-93a1-f2a7359586f8.png) |  |
| Audio-medium | ![screen shot 2018-01-23 at 1 41 51 pm](https://user-images.githubusercontent.com/10562544/35294182-e8adc83c-0043-11e8-9d55-05f84f7318c5.png) | ![screen shot 2018-01-23 at 1 41 56 pm](https://user-images.githubusercontent.com/10562544/35294183-e8cb35de-0043-11e8-9483-b8736f54bd40.png) |  |
| Audio-low | ![screen shot 2018-01-23 at 1 42 02 pm](https://user-images.githubusercontent.com/10562544/35294184-e8e0859c-0043-11e8-8c72-b191bf0ebc4d.png) | ![screen shot 2018-01-23 at 1 42 07 pm](https://user-images.githubusercontent.com/10562544/35294185-e8f23864-0043-11e8-8a68-f2e7bf9b5a93.png) |  |
| Audio-mute | ![screen shot 2018-01-23 at 1 42 13 pm](https://user-images.githubusercontent.com/10562544/35294186-e901e9e4-0043-11e8-8803-6cd506d89b8e.png) | ![screen shot 2018-01-23 at 1 42 20 pm](https://user-images.githubusercontent.com/10562544/35294187-e9131fd4-0043-11e8-88c0-e686ddc35253.png) | Added an "x" to indicate better indicate mute. |
| Double-quote |  ![screen shot 2018-01-23 at 1 42 37 pm](https://user-images.githubusercontent.com/10562544/35294188-e928e1a2-0043-11e8-890c-1ef4a1793cea.png) | ![screen shot 2018-01-23 at 1 42 41 pm](https://user-images.githubusercontent.com/10562544/35294189-e93e16c6-0043-11e8-935c-daaa7e6ce406.png) | Tried to keep this style more in line with our simple icons. |
| _Not specified in design manual_  | ![screen shot 2018-01-23 at 1 42 46 pm](https://user-images.githubusercontent.com/10562544/35294190-e954c218-0043-11e8-9ee8-9a1f541ed413.png) | ![screen shot 2018-01-23 at 1 42 52 pm](https://user-images.githubusercontent.com/10562544/35294191-e962d59c-0043-11e8-9802-b509d63fb2ce.png) |  |
| Clock | ![screen shot 2018-01-23 at 1 43 03 pm](https://user-images.githubusercontent.com/10562544/35294192-e973d1bc-0043-11e8-9cd1-14482d6aa7d9.png) | ![screen shot 2018-01-23 at 1 43 09 pm](https://user-images.githubusercontent.com/10562544/35294193-e989201c-0043-11e8-80ac-4f2ee7774076.png) | Hands in the open symbol feel a little thin with our rules, but maybe it's okay. |
| Lock | ![screen shot 2018-01-23 at 1 43 17 pm](https://user-images.githubusercontent.com/10562544/35294194-e9a1e8d6-0043-11e8-9e44-ee257eabd06d.png) | ![screen shot 2018-01-23 at 1 43 22 pm](https://user-images.githubusercontent.com/10562544/35294195-e9b431da-0043-11e8-85fd-ac27f38104ef.png) |  |
| Unlock | ![screen shot 2018-01-23 at 1 43 29 pm](https://user-images.githubusercontent.com/10562544/35294196-e9cc59b8-0043-11e8-8cee-2961084708d4.png) | ![screen shot 2018-01-23 at 1 43 34 pm](https://user-images.githubusercontent.com/10562544/35294197-e9fe6962-0043-11e8-95e3-f4e623bc7c24.png) |  |
| Search | ![screen shot 2018-01-23 at 1 44 17 pm](https://user-images.githubusercontent.com/10562544/35294198-ea1ace0e-0043-11e8-949b-ad3bc64c8dd4.png) | ![screen shot 2018-01-23 at 1 44 25 pm](https://user-images.githubusercontent.com/10562544/35294199-ea301908-0043-11e8-9235-722d667aa755.png) |  |
| Menu | ![screen shot 2018-01-23 at 1 45 40 pm](https://user-images.githubusercontent.com/10562544/35294200-ea41192e-0043-11e8-80b2-f68a8ca6a3d8.png) | ![screen shot 2018-01-23 at 1 45 46 pm](https://user-images.githubusercontent.com/10562544/35294201-ea5312b4-0043-11e8-97be-04c06d48fd40.png) |  |
| Wifi | ![screen shot 2018-01-23 at 2 24 06 pm](https://user-images.githubusercontent.com/10562544/35296596-91d5de4e-004a-11e8-8c47-18ccdce86fca.png) | ![screen shot 2018-01-23 at 2 24 12 pm](https://user-images.githubusercontent.com/10562544/35296598-91ec67cc-004a-11e8-9922-eddaba9fbeb0.png) | Uses the additional 100pt weight. Breaks the grid because of it's unusual shape. |
| Chart | ![screen shot 2018-01-23 at 2 47 39 pm](https://user-images.githubusercontent.com/10562544/35297262-758564c4-004c-11e8-8c9e-a44ec6958b69.png) | ![screen shot 2018-01-23 at 2 47 47 pm](https://user-images.githubusercontent.com/10562544/35297263-75ce6192-004c-11e8-8666-d7eb47352590.png) |  |
| Bullhorn | ![screen shot 2018-01-23 at 3 04 16 pm](https://user-images.githubusercontent.com/10562544/35298000-c9fc86c0-004e-11e8-8c87-fc0f33be820c.png) | ![screen shot 2018-01-23 at 3 04 22 pm](https://user-images.githubusercontent.com/10562544/35298001-ca14463e-004e-11e8-98bb-8ee7c8ae18f8.png) |  |
| Microphone | ![screen shot 2018-01-23 at 3 14 04 pm](https://user-images.githubusercontent.com/10562544/35298415-225f7cea-0050-11e8-8a9b-d54feae77304.png) | ![screen shot 2018-01-23 at 3 14 10 pm](https://user-images.githubusercontent.com/10562544/35298416-2280c738-0050-11e8-9025-567aba952442.png) |  |

**Comment by Dnpizarro** [comment]
Below is the rest of the group 2 icons:

| Name | Symbol | In circle | notes |
| --- |  --- |  --- |  --- |
| User | ![artboard 2 copy 6](https://user-images.githubusercontent.com/6852363/35309704-c6293c28-007b-11e8-9a2d-864472bdfba0.png) | ![artboard 2 copy 14](https://user-images.githubusercontent.com/6852363/35309717-d14847a2-007b-11e8-97f8-0f32c9849147.png) |  |
| Parent | ![artboard 2 copy 7](https://user-images.githubusercontent.com/6852363/35309733-dfcfa0f4-007b-11e8-814d-a61a1a50e1ce.png) | ![artboard 2 copy 15](https://user-images.githubusercontent.com/6852363/35309741-ea17b218-007b-11e8-9dc5-44921d5261da.png) |  |
| Dialogue | ![artboard 2 copy 8](https://user-images.githubusercontent.com/6852363/35309752-f272dcbc-007b-11e8-9b08-5c4455e0bd80.png) | ![artboard 2 copy 16](https://user-images.githubusercontent.com/6852363/35309762-fa771e5a-007b-11e8-8eb1-78bfb9e2a026.png) |  |
| Speech-bubble | ![artboard 2 copy 9](https://user-images.githubusercontent.com/6852363/35309775-0bb7ef14-007c-11e8-941f-22f7a95191a1.png) | ![artboard 2 copy 17](https://user-images.githubusercontent.com/6852363/35309780-11d01502-007c-11e8-94be-b93b572c0e49.png) |  |
| Date | ![artboard 2 copy 10](https://user-images.githubusercontent.com/6852363/35309786-1a488ff2-007c-11e8-962c-9d7825fe7516.png) | ![artboard 2 copy 18](https://user-images.githubusercontent.com/6852363/35309793-22e9aaa6-007c-11e8-8c29-ec1ed3503c43.png) |  |
| Settings | ![artboard 2 copy 11](https://user-images.githubusercontent.com/6852363/35309800-2a903112-007c-11e8-944d-46b34c776379.png) | ![artboard 2 copy 19](https://user-images.githubusercontent.com/6852363/35309812-33bf0196-007c-11e8-8a70-53800735b83a.png) |  |
| Lightbulb | ![artboard 2 copy 12](https://user-images.githubusercontent.com/6852363/35309828-4345477e-007c-11e8-89af-130b13f74436.png) | ![artboard 2 copy 20](https://user-images.githubusercontent.com/6852363/35309833-4a0ce4b8-007c-11e8-8742-aa274d32734f.png) | I worked on the shape of the bulb several times and I wanted to get some feedback on it. |

**Comment by designlanguage** [comment]
@Dnpizarro - Thanks for posting these. Can you add your file to the drive? A few comments:

* The user in the circle looks slightly off center.
* The speech bubble and dialogue icons should be related to the complaint icon. The triangle coming from each should be a similar size, so I think these are a bit large.
* Do you think we need the numbers in the calendar? If you use the calendar you made for payday (with the rings), or maybe add boxes, that might read enough that we don't need numbers.
* The spaces between the teeth of the gear look a little small, and I worry that they'll disappear at small sizes. Can these be larger?
* I like the lightbulb.

**Comment by Dnpizarro** [comment]
Below are the notes from our working session earlier today:

**External link:** looks like arrow goes too far. Potentially reconsider rethinking this icon.
**Share-icon:** Consider adding an additional share symbol.
**Information:** Lets test at 16pt, the “i” might be too thin.
**Audio mute:** bring “x” in closer to the speaker.
**Clock:** the hands might be too small, reconsider position of the clock hands.
**Parent:** Consider less torso, document the rounded edges for the people.
**Speech bubble:** Make consistent triangle shape with the complaint bubble. 
**Dialogue:** Try both as solid shapes with an outline. 
**Date:** consider a redesign as a calendar, remove the numbers.
**Settings:** the spaces between the gears can be wider, make the teeth smaller.

**Comment by designlanguage** [comment]
@Dnpizarro - FYI, the "Play" and "Newspaper" icons are still missing from this group.

**Comment by Scotchester** [comment]
Most of these are solid now. A few minor issues:

- `lock.svg` is still misnamed `round.svg`
- `link-round.svg` is misspelled, missing the `i`
- `parents-round.svg`'s art isn't in a single group

**Comment by designlanguage** [comment]
These icons should probably live in web:

| Name | Symbol | In circle | notes |
| --- |  --- |  --- |  --- |
| _Not shown in design manual_ | ![screen shot 2018-01-29 at 1 52 47 pm](https://user-images.githubusercontent.com/10562544/35528478-f2b483ae-04fb-11e8-931a-1794ae7e1299.png) | ![screen shot 2018-01-29 at 1 52 53 pm](https://user-images.githubusercontent.com/10562544/35528479-f2cc77fc-04fb-11e8-8452-5b2054766dcd.png) |  |


Maybe this one too:

| Name | Symbol | In circle | notes |
| --- |  --- |  --- |  --- |
| _Not shown in design manual_ | ![screen shot 2018-01-29 at 1 57 20 pm](https://user-images.githubusercontent.com/10562544/35528628-72a99748-04fc-11e8-85ea-80ad2c04a219.png) | ![screen shot 2018-01-29 at 1 57 27 pm](https://user-images.githubusercontent.com/10562544/35528629-72c7509e-04fc-11e8-9a17-0b9795ae35bd.png) |  |

**Comment by jimmynotjim** [comment]
I'm kicking this one back to the backlog. @Dnpizarro after you finish Group 4 can you circle back to this and make the recommended updates? Thanks.

**Comment by designlanguage** [comment]
This icon should also probably live in the web category:

| Name | Symbol | In circle | notes |
| --- |  --- |  --- |  --- |
| _Not specified in the design manual_  | ![screen shot 2018-01-30 at 3 11 07 pm](https://user-images.githubusercontent.com/10562544/35588851-e1647404-05cf-11e8-96aa-3e9a1dee0192.png) | ![screen shot 2018-01-30 at 3 11 12 pm](https://user-images.githubusercontent.com/10562544/35588852-e1722630-05cf-11e8-8157-1ef08e607b66.png) |  |

**Comment by Dnpizarro** [comment]
@jimmynotjim @Scotchester below are the missing icons for this set:
https://drive.google.com/drive/u/1/folders/1PU0jc7hphx_5ZfVnL9MXqpL_eAsaclkh

<img width="285" alt="screen shot 2018-01-30 at 5 12 11 pm" src="https://user-images.githubusercontent.com/6852363/35594604-cd865d14-05e1-11e8-9693-c1ad87860606.png">

**Comment by Dnpizarro** [comment]
@jimmynotjim @Scotchester the updated broadcast icon is below:
https://drive.google.com/drive/u/0/folders/1PU0jc7hphx_5ZfVnL9MXqpL_eAsaclkh
