### ISSUE TITLE
Update examples on Video page

### ISSUE THREAD

**Issue by iuloshi** [cfpb/design-manual#61]
Hey guys! As a heads up, I updated the layout of the Video page. Looks like we need some more example screenshots for the Stylistic Guidelines categories. There are placeholders for now.

http://cfpb.github.io/design-manual/identity/video.html

Thanks! @mebates @stephanieosan @ohsk

**Comment by ohsk** [comment]
We should revisit the possibility of updating these examples using real, embedded videos, but at least reflects the content from the Style Guide now!

**Comment by vz3** [comment]
One other thing worth noting is that embedded videos should include an at least 1px border (Like you've put on the page, @iuloshi). An example of where this is broken can be found on our mortgages page:
http://www.consumerfinance.gov/mortgage/

The lack of a border leads the content with a pure white bg to flow into the page like an overlay (think Clippy circa 1999 or Michael Steel circa 2009).

I'm not familiar yet with how modifications are made to the design manual, but this is something I discussed with @nataliafitzgerald a while back.

**Comment by stephanieosan** [comment]
@vz3 We're working on a path/system for adding/editing the content of our standards. Here's how you should do it:

To get the 1px border included in our standards, you should file an issue in this repo and label it with the milestone "Identity Discussion" (since our Video standards falls under Identity). 

We don't really have a code/execution section under our video standards, so we can discuss how to include that in the issue or during our next branding meeting. Once it's an "approved" content change, we can just add it in.
