### ISSUE TITLE
Add information about the front directory to the README

### ISSUE THREAD

**Issue by ascott1** [cfpb/design-manual#63]
The current README doesn't have the proper instructions for installing dependencies and using Grunt.

**Comment by vz3** [comment]
Yeah, I'm getting pretty concerned about the lack of documentation in getting from cloning our codebase to being able to get it actually functioning/editing code (I'm especially thinking about this because I'm working off of a brand new system right now).

This is more for cf.gov than design-manual, but should be something we improve on across the board.
